{ +block{easylistchina} }
.189\.cn/dns/
.gd\.ct10000\.com/js/ecssstat\.js
.jxad\.jx163\.com[/&:?=_]
/js/utils51\.js
/js/utils78\.js
.91339\.com[/&:?=_]
.log\.hiiir\.com[/&:?=_]
.shurumedia\.com[/&:?=_]
.ttmsg\.qianqian\.com[/&:?=_]
.un\.5d6d\.com[/&:?=_]
.uu456\.com[/&:?=_]
\.com\.cn/js/ad\.
\.info/ad/
/adflash/.*
/attachments/ad/.*
/data/ad/.*
/ggpic/.*
/main/s\?
/pic/ad/.*
/picad/.*
/tan1\.js
.a\.youdao\.com[/&:?=_]
.tuiguang\.178\.com[/&:?=_]
.img\.99sushe\.com/.*/buttom_
.img\.99sushe\.com/cet/banner
.a\.tbcdn\.cn/s/ac\.js
.a\.tbcdn\.cn/s/atp\.js
.blog\.xuite\.net/_public/js/ysmad\.js
.hiad\.myweb\.hinet\.net[/&:?=_]
.hichannel\.hinet\.net/player/radio/hinetAd\.js
.hichannel\.hinet\.net/videoad2/
.p4u\.hinet\.net[/&:?=_]
.p8u\.hinet\.net[/&:?=_]
.town\.xuite\.net/_ad/
.aagw\.sdo\.com[/&:?=_]
.adrs\.sdo\.com[/&:?=_]
.ck\.sdo\.com[/&:?=_]
.sy\.sdo\.com[/&:?=_]
.log\.interest\.mix\.sina\.com\.cn[/&:?=_]
.file\.cloud\.sogou\.com/.*/superzone/
.member\.udn\.com/NEWS/MISC/
.udn\.com/1024/NEWS/INCLUDE/
.udn\.com/images/forumimg/digad\.html
.udn\.com/NEWS/watermark_omo_2010\.js
.js\.kankan\.xunlei\.com/5\.2/mp4/js/kankan_commercial_mp4_563\.js
.l\.yimg\.com/d/lib/bc/bcr_2\.0\.5\.js
.l\.yimg\.com/pq/
.s\.yimg\.com/gs/apex/
.s\.yimg\.com/ja/ap/tw/js/
.tw\.dictionary\.search\.yahoo\.com/beacon/
.tw\.img\.webmaster\.yahoo\.com[/&:?=_].*/ystats\.gif
.tw\.yimg\.com/a/tw/
.l\.yimg\.com/mq/hk/promotions/
.s1\.josho\.yamedia\.tw/f/plugin\.swf[/&:?=_]
.player\.pb\.ops\.tudou\.com/info\.php\?
.tudou\.com[/&:?=_].*/outside\.php
\.cc/js/ads/
\.cn/ads/
\.com/a_d/
\.com/js/ad_
\.in/js/ads/
\.info/ad\.js
\.info/js/ads/
\.net/js/ads/
\.us/js/ads/
/a_tc\.js\?adid=
/acmsd/.*
/adintrs/.*
/AdPreview/.*
/adpuba/.*
/advpic/.*
/ajds/.*
/cache/ad_js/.*
/caches/poster_js/.*
/clicktotal/ClickTotal\.js
/content/plugins/em_ad/.*
/data/cache/myad-
/diantan\.js
/duilian\.
/duilian2\.
/duilian_gg\.
/floatad\.
/floatad2\.
/gaog/.*
/gg1\.
/gg2\.
/ggao\.
/ggao/.*
/ggjs/.*
/guangao/.*
/guangg/.*
/guanggao\.
/guanggao/.*
/ina_ad_
/j/Lad6_2\.js
/jsadv/.*
/module/adsview/.*
/paypic/.*
/piaofu\.js
/proxy\.htm\?id=
/proxy\.html\?id=
/qpxl\.js
/runtime/js/index960\.js
/source/plugin/mama_tips/.*
/static/adsview/.*
/tan\.js
/tanchuang\.
/tuiguang/.*
/u/_sponsor/.*
^http://.*\.cc/ad/
^http://.*\.cn/ad/
^http://.*\.hk/ad/
^http://.*\.in/ad/
^http://.*\.tv/ad/
^http://.*\.tw/ad/
^http://.*\.us/ad/
^http://.*/.*_ad\.js
^http://.*/ad\.js\?sn=
^http://.*/ad\.js\?v=
^http://.*/gg/
^http://.*/js/ad\.
^http://.*/js/ad/
^http://.*/js/tc\.js
^http://acs\.
^http://ad\.
^https://.*/ad/
/adscpv/.*
/AShow\.aspx\?AID=
/code/cpc\.asp\?
/code/cpm\.asp\?
/code/cpv\.asp\?
/code/mypop\.asp\?
/code/pop_cpf\.
/code/popjs\.
.113\.17\.188\.42[/&:?=_]
.116\.55\.227\.242[/&:?=_]
.122\.227\.254\.195[/&:?=_]
.1503\.net/code/
.182\.92\.81\.104[/&:?=_]
.1l1\.cc[/&:?=_]
.211\.167\.105\.131[/&:?=_]
.218\.26\.217\.88[/&:?=_]
.220\.115\.251\.25[/&:?=_]
.221\.204\.213\.222[/&:?=_]
.2m2n\.com[/&:?=_]
.365bibi\.com[/&:?=_]
.365safego\.com[/&:?=_]
.366safego\.com[/&:?=_]
.3g\.990\.net[/&:?=_]
.6dvip\.com[/&:?=_]
.77power\.com[/&:?=_]
.7wen\.cn[/&:?=_]
.88rpg\.net[/&:?=_]
.adm-cnzz\.net[/&:?=_]
.ads\.uc\.cn[/&:?=_]
.ajaxcdn\.org[/&:?=_]
.amazingmagics\.com[/&:?=_]
.apikozakanet-a\.akamaihd\.net[/&:?=_]
.apiscantacknet-a\.akamaihd\.net[/&:?=_]
.appnext-a\.akamaihd\.net[/&:?=_]
.caob5\.info[/&:?=_]
.cb\.baidu\.com[/&:?=_]
.cbjs\.baidu\.com[/&:?=_]
.cnxad\.net[/&:?=_]
.cpcv\.cc[/&:?=_]
.cpms\.cc[/&:?=_]
.cpro\.baidu\.com[/&:?=_]
.cpro\.baidustatic\.com[/&:?=_]
.cpv6\.com[/&:?=_]
.cpva\.cc[/&:?=_]
.crdrjs\.info[/&:?=_]
.crwdcntrl\.net[/&:?=_]
.cyacc\.com[/&:?=_]
.datafastguru\.info[/&:?=_]
.drmcmm\.baidu\.com[/&:?=_]
.duiwai\.baidu\.com[/&:?=_]
.dxssiyi\.com[/&:?=_]
.ecuc123\.net[/&:?=_]
.eiv\.baidu\.com[/&:?=_]
.f1190\.com[/&:?=_]
.fanhao123\.com[/&:?=_]
.fv99\.com[/&:?=_]
.gf1352\.com[/&:?=_]
.guduopu\.com[/&:?=_]
.gzqudou\.com[/&:?=_]
.hao123rt\.com[/&:?=_]
.hdapp1003-a\.akamaihd\.net[/&:?=_]
.hdapp1008-a\.akamaihd\.net[/&:?=_]
.ihualun\.com[/&:?=_]
.jczzjx\.com[/&:?=_]
.jk939\.com[/&:?=_]
.moodoocrv\.com\.cn[/&:?=_]
.mscimg\.com[/&:?=_]
.nextcps\.com[/&:?=_]
.notice\.uchome\.manyou\.com[/&:?=_]
.okm918\.com[/&:?=_]
.p0y\.cn[/&:?=_].*\.swf
.sharedaddomain\.com[/&:?=_]
.spcode\.baidu\.com[/&:?=_]
.tad\.suning\.com[/&:?=_]
.tc600\.com[/&:?=_]
.tg\.1155t\.cn[/&:?=_]
.ubmcmm\.baidustatic\.com[/&:?=_]
.wqsph\.net[/&:?=_]
.xcy8\.com[/&:?=_]
.zgksb\.com[/&:?=_]
\.niusnews\.com/upload/banners/
/18av/adcg/MVAD_imageshack\.swf
/18avdayad/.*
/2kk\.cc-330-50\.gif
/2tu/ads/.*
/adscript/crazyad\.js
/comiis_ydzx/ads/.*
/game/aplus/pptv/.*
/gyw_index/.*/images/ad_
/ifengRotatorAd\.js
/kocpc\.myweb\.hinet\.net[/&:?=_]
/modules/video/player/nuevo/midroll\.php\?
/moneymaker/js/piaopp\.js
/my0538/img/ad/.*
/nddailyfile/webadv/.*
/newhuagg/.*_right
/newhuagg/index_
/nowscore/ad/.*
/sinaLoginReward2014\.
/sinaLoginReward2014_comment\.
/static/btmeegg/.*
/sznews/images/bbsgg
/tonghuacun/skin/zxf/kan_hree\.js
/wallstcn/img/head-event-
/wangyuedeux/imgs/daibang\.jpg
/www\.soft4fun\.net/wp-content/uploads/.*_banner
/xiao1234\.com/ads/.*
/ysm\.ezprice\.net/.*
:88/lighttpd/default/
.020\.com/960_60
.020\.com/960_70
.027down\.com/images/banner760-60\.gif
.03jd\.cn/data/attachment/portal/
.03ssss\.com/js/tou\.js
.0439\.com/.*/RevealTrans_main_banner\.js
.0439\.com/html/js/ad_r_300x220\.js
.0439\.com/html/js/sytl\.js
.0439\.com/html/js/tuiguang\.js
.0439\.com/inc/kf\.js
.0460\.com/images/banner/
.0460\.com/js/txtrec\.js
.05096\.com/jsdoc/ad\.html
.0517w\.com/2013/haina/10/banner\.gif
.0527o\.com/shfqad/
.0575bbs\.com/updateimeags/
.0579\.cn/SHow/Showplacenew\.aspx
.0597kk\.com/js/float\.js
.0597ok\.com/ilike/597/
.05sun\.com/js/comm\.js
.05sun\.com/js/downinfo\.js
.06abc\.com/images/adstr/
.0743ds\.com/data/attachment/portal/201408/29/102918zwy5h9xyeh6agyvw\.gif
.0756\.la/ad-htm/
.0758net\.com/data/attachment/portal/
.07908\.com/images/
.0830bbs\.com/portal/
.0dian8\.org/data/js/
.1000fr\.net/attachments/month_1401/20140120_5207018531e775003b1ceDffO2a0172J\.jpg
.1024cl\.us/down\.js
.102tv\.cn/images/tututool\.gif
.102tv\.cn/js/ad.*\.js
.102tv\.cn/js/desktop\.js
.102tv\.cn/js/index_.*\.js
.10jqka\.com\.cn/public/stock/red\.html\?
.10yan\.com/html/News/xsqx/images/975-80\.swf
.10yan\.com/mmm/
.10yan\.com/skins/video/images/0
.10yan\.com/skins/video/images/qcwsgg\.swf
.11\.mydrivers\.com/drivers/
.11\.mydrivers\.com/myfiles/0.*\.js
.11\.mydrivers\.com/myfiles/myfiles100.*\.js
.11\.mydrivers\.com/news/03\.js
.11\.mydrivers\.com/news/google468x60\.js
.110112119\.com/cc22cc\.jpg
.111cn\.net/gg_ad/
.111cn\.net/js/downc.*\.js
.111cn\.net/js/v8/
.113\.17\.188\.44/.*\.js
.114fw\.com/dagg/
.114la\.com/homeimages/aicai\.png
.114la\.com/homeimages/sjb0702\.png
.114so\.cn/js/nm.*\.js
.115\.com/static/plug/download/images/yun\.jpg
.115img\.com/static/delivery/
.115mm\.com/js/
.117\.79\.236\.111/wj/
.118\.26\.200\.246[/&:?=_]
.119\.167\.73\.60/m_code/
.11ffbb\.com/java/
.120askimages\.com/ask/js/m\.js
.121\.10\.176\.84:1010/openV5\.js
.121down\.com/js/.*\.html
.123cha\.com/712381_com\.gif
.123du\.net/skin/js/dlad\.js
.125\.46\.61\.28/1003/1003031301\.swf
.126disk\.com/www/all_guanggao\.js
.127\.net/m/irpic/.*/promPic\.jpg
.12pe\.com/aajjss/
.131\.com/common/alertwindow\.html
.131\.com/home/resouces/js/
.131458\.com/union/union_index\.js
.133918\.com/business/
.133ip\.com/add/
.133uu\.com/html/
.147rr\.com/js/data\.js
.1518\.com/ss/
.160\.com/160qd_gg/
.160\.com/qdz/images/gg_
.163disk\.com/static/www/
.1677\.net/js/ad.*\.js
.1677\.net/js/cad.*\.js
.1677\.net/js/gb.*\.js
.1688\.com\.au/site1/1688ad/
.16888\.com/ajax/loadcardata\.php
.16sucai\.com/ads/
.17173\.com/2013/new/channel-float\.js
.17173\.com/bd/ifm/allyes/
.17173\.com/if/
.17173\.com/new/
.17173cdn\.com[/&:?=_].*/flash/OnLineTime\.swf
.172\.15\.2\.28:3438/.*\.js
.173\.208\.173\.117/a.*\.gif
.173kt\.com/ads/
.174\.123\.15\.43:8080
.174\.139\.95\.28/ad/
.178\.com/glr\.js
.178\.com/s/js/ngafloatwindow\.js
.17dm\.com/s/common/js/.*AD\.js
.17kk\.cc/scriptAD/
.17kqw\.com/.*\.gif
.17kqw\.com/topgg\.jpg
.17ok\.com/focus/3j/css2013/artical_03\.jpg
.17ok\.com/focus/3j_right_jdt\.shtml
.17pr\.com/batch\.ad\.php\?
.17yy\.com/style/ifra_ad/
.183\.129\.206\.25:18180/i\.php\?z=
.183\.136\.168\.78:8082/ad/
.183\.81\.166\.100/cari/banner/
.183yf\.cn/niuza160\.jpg
.189so\.cn/js/np1\.js
.189so\.cn/js/popup\.js
.189so\.cn/js/qiantan\.js
.189so\.cn/pop\.html
.198\.40\.52\.11/ad/
.198\.40\.56\.242/ad/
.1dot\.cn/spider/1dotAd\.php
.1kejian\.com/js/topA\.js
.1lou\.com/ceo888\.gif
.1m1m\.cn/bar/
.200\.cc/js/zhoujiatian/
.2008xxx\.com:888
.204\.12\.228\.235/.*\.png
.208\.94\.244\.98/.*ts\.js
.211600\.com/data/attachment/portal/
.211600\.com/images/portal/
.219\.153\.41\.154/v1/
.219\.153\.41\.175/.*\.js
.21cnimg\.com/photos/album/20140516/o/6F6B0C1C385DEE68F84243392B599F7E\.jpg
.21ses\.info/t/
.21uscity\.com/zonelist\.php
.21yq\.com/mg/21yq/
.2200book\.com/configs/article/pagebottom1yc\.js
.2200book\.com/themes/v2/images/frxz_tonglan\.gif
.222\.33\.59\.55/show\.js
.222\.45\.224\.77[/&:?=_].*\.js
.222dz\.com/js/
.222mp\.com/imageabc/.*\.js
.224qq\.com/js/ddd\.js
.22mt\.com/js/bd.*\.js
.22mt\.com/js/zj_.*\.js
.2300sjz\.com/liv_loadfile/folder81/fold
.2345\.com/dianyingimg/ads/
.2345\.com/dianyingimg/tv/ivy/taobao/
.2345\.com/duoteimg/duotehtml/
.2345\.com/xiaoimg/swf/flash/
.23us\.com/scripts/.*_tan\.js
.23us\.com/scripts/fmt\.js
.23youku\.com/Runtime/js/
.2500sz\.com/ad20
.2500sz\.com/site/
.258zb\.com/jsData/users\.aspx
.25xz\.com/ads/
.25xz\.com/degeye\.gif
.265\.com/static/pages/img/home_sold_ads\.jpg
.265g\.com/down/yinyue
.27xs\.com/js/mid_
.27xs\.com/js/s_z\.js
.2btu\.com/gg\.jpg
.2ccc\.com/images/show/
.2ccc\.com/images/WebXone\.gif
.2kuai\.com/images/12\.gif
.2kuai\.com/images/vip\.gif
.2muslim\.com/data/attachment/portal/201407/09/185300xlal7nahvvh9sogg\.jpg
.2u\.com\.cn/js/2012_movie\.js
.2zzt\.com/images/3hhost\.jpg
.2zzt\.com/images/ce250\.gif
.2zzt\.com/images/enkj\.gif
.2zzt\.com/images/hczj\.png
.2zzt\.com/images/lxzjnf\.jpg
.2zzt\.com/images/weixiang\.jpg
.2zzt\.com/images/weixinhost\.jpg
.310v\.com/adh\.js
.310v\.com/images/tmp_adpic
.310v\.com/js/f2\.js\.js
.3155\.com/js/ifile
.315che\.com/upload_img/aimg/
.32345sf\.com[/&:?=_]
.32666\.com/ads/
.32666\.com/img/
.33\.autoimg\.cn/t/Adhtmlnet/.*\.jpg
.33\.autoimg\.cn/t/Adhtmlnet/.*\.swf
.3399\.com/act/5599/js/kuang
.3399\.com/Common/OnlineServer\.html
.33lc\.com/lvcha/jquery\.gotop\.js
.33xs\.com/hot/
.33xs\.com/js/g
.33xs\.com/js/mg
.33zxzx\.com/botad\.html
.33zxzx\.com/go\.js
.33zxzx\.com/pv\.js
.356ys\.com/template/tieniudy/images/g_js/
.35zww\.com/zzzjs/
.360-bo\.com/js/float\.js
.360bo\.cc/js/float\.js
.360safego\.com[/&:?=_]
.3634\.com/qq/
.36tv\.cn/ad_pic/
.36tv\.cn/statics/images/jinhuatv/ad
.3boys2girls\.com/newfile/image2010/banner_housead_
.3boys2girls\.com/templates/default/2013/life/160b5\.js
.3d66\.com/gg-swf/
.3d66\.com/gx2013g/
.3dezu\.cn/data/attachment/portal/
.3g\.cn/bookimage/hadpic/201310/1382926339\.jpg
.3g\.cn/bookimage/hadpic/201310/1383013123\.jpg
.3g\.cn/bookimage/hadpic/201405/1401446588\.jpg
.3g\.cn/bookimage/hadpic/201406/1401854026\.jpg
.3g\.cn/bookimage/hadpic/201406/1401854206\.jpg
.3g\.cn/bookimage/hadpic/201406/1401854330\.jpg
.3g518\.com/mb/000000/moban21/js/tcad\.js
.3g518\.com/piaofujs/
.3h3\.com/js/homepage\.js
.3h3\.com/js/listad\.js
.3h3\.com/js/show/
.3iiii\.info/aajjss/
.3sjt\.com/3sjtimg/
.400516\.com/data/attachment/album/
.40407\.com/plus/rpad/
.40407\.com/templets/default/images/index\.js
.40wan\.com/js/www2/
.4399\.com/expire1day/
.4399\.com/loadimg/loading\.htm
.43999\.net\.cn/images/jianfei66\.jpg
.45zw\.com/static/js/xiaoshuo\.js
.46\.com/static/images/banner/
.464mnk\.com/templets/new/static/js/common\.js
.50\.115\.123\.38/ad/
.51\.com/up/bdfmt/
.512ms\.com/js/index_ggw_show\.js
.5156edu\.com/js/lwx\.js
.5173cdn\.com/operation/indexbanner/2014/.*_350122\.jpg
.5173cdn\.com/operation/indexbanner/2014/.*_730222\.jpg
.5184\.com/container/html/news_view_gg
.5184\.com/gk20.*_240\.
.5184\.com/gk2014/.*_315\.
.5184\.com/gk2014/ebuy
.51bczx\.com/attachment/Mon_
.51bczx\.com/img/51bczx/
.51bczx\.com/img/zhibok8/
.51bczx\.com/js/float\.js
.51cto\.com/wyfs02/M00/2B/D0/wKioL1ONKOqR2sQ4AACb4EPqI1I290\.jpg
.51cto\.com/wyfs02/M01/2B/D0/wKioL1ONKCeQxVy1AAFuoDqhXJ0709\.jpg
.51cto\.com/wyfs02/M02/2A/CD/wKioL1OFhmrxjAAjAACeqnBFX5U699\.jpg
.51gaojian\.com/js/tj\.js
.51gugu\.com/popwin/AutoHAdShow\.aspx
.51hanhua\.com/2013/
.51img\.ajiang\.net[/&:?=_].*\.gif
.51netu\.com\.cn/index\.php/index/advShow\?adpid=
.51test\.net/baiduunion/
.51test\.net/js_new/.*_banner\.js
.51test\.net/js_new/.*_content_down\.js
.51test\.net/js_new/.*_content_up\.js
.51test\.net/js_new/.*_right_middle\.js
.51testing\.com/images/sz51com\.swf
.51testing\.com/imagesnew/.*\.swf
.51testing\.com/imagesnew/307x90\.gif
.51testing\.com/imagesnew/642x53\.gif
.51testing\.com/imagesnew/960x101\.jpg
.51testing\.com/imagesnew/indextop\.jpg
.51wan\.com/img/js/xyadjs_
.51wan\.com/web/v1/index/images/spec/
.51ztzj\.com/js/you\.js
.51ztzj\.com/res/web/img/download_sign
.51ztzj\.com/res/web/img/pic/inshow\.jpg
.51zxw\.net/adad/
.51zxw\.net/images/zhaopin\.jpg
.520kankan\.com/960x80\.gif
.520rr\.com.*/baidu/
.52ch\.net/data/advimg/
.52che\.com/Inc/FooterComm_
.52che\.com/NewLocal/TemplateHtml/headflash1_
.52hardware\.com/images/baimg/
.52hardware\.com/topic/a2
.52jifenbao\.net/wp-content/uploads/2014/04/xinren\.jpg
.52jifenbao\.net/wp-content/uploads/2014/06/caibao\.jpg
.52jifenbao\.net/wp-content/uploads/2014/06/lisheng\.jpg
.52kdm\.com/static/52kdm/m/
.52rd\.com/Pic/Click/
.52rd\.com/Pic2/.*_600_60\.
.52tian\.net/qq/
.52waha\.com/static/js/function_bbs\.js
.52zy\.com/other/js/
.54new\.com/da/
.557vv\.com/d/file/p/
.557vv\.com/images/
.557xx\.com/d/file/p/
.557xx\.com/images/
.55bbs\.com/55bbs/201405/haier
.55music\.net/11231\.gif
.55music\.net/dazhe\.jpg
.55xxx\.info/js/t1\.js
.56\.com/js/promo/
.56ads\.com/js/main\.js
.56img\.com[/&:?=_].*/baidu-promotion\.js
.576tv\.com/Scripts/home\.js
.58\.com/ds/jinrong/ban/
.58\.com/ds/tgbrand/
.58\.com/ui7/.*banner_
.58\.com/ui7/fang/list/img/gongyu\.png
.591\.xxx/images/.*\.gif
.591hx\.com/images/0000\.jpg
.591hx\.com/js/dll\.js
.591hx\.com/js/floatbox\.js
.591hx\.com/lunbo/
.5dmail\.net/image/ad_
.5dmail\.net/image/ORF_1000\.gif
.5dmail\.net/js/
.5i\.com/images/5ibbtangct\.js
.5i\.com/include/js/ad_
.5ilog\.com/qq/js/jsgg\.js
.5ips\.net/love/
.5iyq\.com/jinmy/5iyq/af1-
.5iyq\.com/skin/default/js/topad
.5tps\.com/js/al_
.5tps\.com/js/bo_al\.js
.5ydj\.com/js/shop\.js
.600km\.com/source/plugin/rsf_elasticity_pull_screen_adv/
.600km\.com/template/.*/ad/
.61\.128\.121\.99/nsrad/
.61\.147\.92\.251:81/120x160\.asp
.61\.164\.108\.104:4275/ad.*\.gif
.66\.fmx\.cn/js/
.66384\.com/templets/js/stats\.js
.66384\.com/templets/SWFad
.666kv\.com/adstaic/
.66rd\.cn/js/foot\.js
.66rd\.cn/pic/itv130\.jpg
.66rd\.cn/pic/rdrccs2014\.jpg
.66rd\.cn/pic/rdwmh800\.gif
.66rd\.cn[/&:?=_].*1000300\.
.66rd\.cn[/&:?=_].*100060\.
.66rd\.cn[/&:?=_].*120250\.
.66rd\.cn[/&:?=_].*96060
.66rnrn\.com/sxgg/
.66wz\.com/adv2/
.66wz\.com/data/attachment/portal/
.67\.159\.44\.187/js/v1\.js
.67\.198\.134\.10/.*\.js$
.68design\.net/inc/news\.
.6949\.com/ggs_
.69nh\.com/detail/player_
.6park\.com/img/15\.png
.6park\.com/wap/
.6vdy\.com/d/960\.js
.6vdy\.com/d/f.*\.js
.6vhao\.com/d/960\.js
.6vhao\.com/d/f.*\.js
.720pmovie\.com/960\.gif
.73p37\.com/js/bottomall\.js
.75\.125\.41\.29:8080/
.76\.73\.85\.179/js/v1\.js
.766\.com/upbox2/js/.*\.js
.77119\.com/js/
.77bike\.com/img/anemos.*\.jpg
.77bike\.com/img/cycli\.gif
.77bike\.com/img/fnhon\.gif
.77bike\.com/img/fsir\.gif
.77bike\.com/img/ori\.gif
.77bike\.com/img/pacific\.jpg
.77bike\.com/img/sticker\.gif
.77bike\.com/img/tern\.swf
.77ds\.com/js/download\.js
.77pan\.cc/ggad/
.77pan\.cc/templates/default/images/kuping\.gif
.7958\.com/static/disk/images/tija_gif\.gif
.7c\.com/7c_.*\.html\?
.7dsw\.com/web8/js/
.7edown\.com/upload/.*\.gif
.7ey\.net/js/index_
.7m\.cn/b/live_b
.7scs\.com/js/TOP\.js
.7sehu\.com/zy/
.7xdown\.com/adgg/
.7xdown\.com/idcgg/
.7xdown\.com/jkjk/
.8.*\.tianya\.cn[/&:?=_]
.800j\.com\.cn/2013ad/
.800j\.com\.cn/2014ad/
.800j\.com\.cn/api\.php\?op=itemtopbanner&
.800j\.com\.cn/index\.php\?m=poster&
.8090zw\.com/js/Aod/tc\.js
.80txt\.com/js3.*\.gif
.86696\.com/images/indexad\.jpg
.8684\.com/com/sys_ad_
.86file\.megajoy\.com[/&:?=_]
.88gs\.com/agfile/
.88liu\.com/data/attachment/portal/
.8jkx\.com[/&:?=_]
.8vod\.net/detail/play_.*\.js
.8vod\.net/detail/vod_.*\.js
.8zdd\.com/tz\.js
.9000wy\.com/templets/default/script/.*content
.90oo\.com/tp/.*980\.gif
.90oo\.com/tp/90232\.jpg
.90oo\.com/tp/down\.gif
.90oo\.com/tp/msn\.jpg
.90oo\.com/tp/w981\.gif
.911-sss\.com/js/alls_
.91danji\.com/images/.*\.jpg
.91danji\.com/js/lmt\.js
.92dp\.com/dianping/videoad
.92wav\.com/rj/.*\.gif
.93oxo\.com/ggad/
.9553\.com/otherhtml/
.96\.43\.97\.243[/&:?=_]
.962\.net/show/all\.js
.962\.net/show/bt\.js
.962\.net/show/index_
.966266\.com/a-d/
.99770\.cc/jsc/inde\.js
.99bbs\..*/images/zabanner\.gif
.99danji\.com/otherhtml/
.99re\.com/images/close\.gif
.9ht\.com/skin2012/js/tlAd\.js
.9ihome\.com/adimgs/
.9ihome\.com/info/ADTopvnet/
.9ist\.com/others/ad/
.9lala\.com/js/
.9pan\.net/filestores/2013/06/10/f2d0e7719e89e5cc4417a563fd012f00\.jpg
.9sky\.com/_gg/
.9upk\.com/images/95050\.gif
.9w1an\.com/special/
.9ye\.com/Files/Editor/ad/
.a-m-s\.poco\.cn[/&:?=_]
.a\.baomihua\.com[/&:?=_]
.a\.game\.qidian\.com/Layout\.aspx\?
.a\.jiaodong\.net/a/2013/
.a\.xizi\.com[/&:?=_]
.a4\.yeshj\.com[/&:?=_]
.a5\.yeshj\.com[/&:?=_]
.a6\.hujiang\.com[/&:?=_]
.a67\.com/a/.*\.js
.aa\.sdo\.com[/&:?=_]
.aa107\.com/js/ddd\.js
.aa141\.com/js/ddd\.js
.ab\.ahlife\.com[/&:?=_].*\.swf
.abc\.hkepc\.com[/&:?=_]
.abc1\.sdo\.com[/&:?=_]
.ac\.tc\.qq\.com/store_file_download\?.*&dir_path=/admin/swf/
.ac168\.info/bt/ts\.js
.acg\.178\.com/201302/t_
.acg\.178\.com/s/manhua218_140\.html
.acode\.b2b\.cn/JS/
.acsystem\.wasu\.cn[/&:?=_]
.act\.chinatimes\.com/aimg/
.actoys\.net/index\.php\?m=poster&
.actoys\.net/js/beitou\.js
.actoys\.net/statics/js/index/ad\.js
.ad\.17173\.com[/&:?=_]
.ad\.bjmama\.net[/&:?=_]
.adadmin\.house365\.com[/&:?=_]
.adi.*\.cnool\.net[/&:?=_]
.adk\.funshion\.com[/&:?=_]
.adm\.265g\.com[/&:?=_]
.adm\.86wan\.com[/&:?=_]
.adm\.bbcss\.com[/&:?=_]
.adm\.funshion\.com[/&:?=_]
.adm\.jjj8\.cn[/&:?=_]
.adm\.leju\.sina\.com\.cn/get_abp_list/
.adm\.qzbbs\.com[/&:?=_]
.adm\.xmfish\.com[/&:?=_]
.adm\.zbinfo\.net[/&:?=_]
.adm\.zzfish\.cn[/&:?=_]
.admd\.yam\.com[/&:?=_]
.admin10000\.com/skin/lagou_250x100\.jpg
.admin5\.com/daohang/
.admin5\.com/extras/
.admin5\.com/hezuo/action/
.admin5\.com/lib/js/.*_article
.adp\.cnool\.net[/&:?=_]
.adpub\.yaolan\.com[/&:?=_]
.adsame\.liba\.com[/&:?=_]
.adsame\.libaclub\.com[/&:?=_]
.adsclick\.yx\.js\.cn[/&:?=_]
.adspending01\.bwnet\.com\.tw[/&:?=_]
.adwordsing\.com/img/1\.jpg
.adwordsing\.com/img/2\.jpg
.ah\.sina\.com\.cn/iframe/
.ahlife\.com/20140606hd\.swf
.ahlife\.com/api\.php\?mod=adv&
.aibang\.com/\?area=ajax&cmd=adv&
.aibangjuxin\.com/images/home/lscx.*\.jpg
.aid\.chinayk\.com[/&:?=_]
.aikongke\.com/wp-content/uploads/2014/06/0f000KdGOFFPAF_yxHIN76\.gif
.ailu\.me/46860\.js
.aipai\.com/app/www/templates/common/ifr/fans_640_40\.html
.aipai\.com/common/html/commonAdForTfansTo\.html
.aisex\.com/bt/ts\.js
.aitxt\.com/images/gtjtop\.jpg
.aiyidu\.com/aiyidu/adver/
.aiyuke\.com/index\.php\?c=position&
.alicdn\.com/tps/.*-950-90\.
.alixixi\.com/adsview/
.am\.6park\.com[/&:?=_]
.am\.szhome\.com[/&:?=_]
.amd\.cn/yyets\.js
.anhuinews\.com/include/
.anhuinews\.com/zhuyeguanli/.*ad/
.anywlan\.com/link/nyt\.gif
.aoodoo\.feng\.com[/&:?=_]
.aoye\.cc/js/footer\.js
.apas\.aipai\.com/www/api/aipaiPlayFull2\.js\?0\.
.apihousefun\.yam\.com/news\.php
.app\.acm\.dzwww\.com[/&:?=_]
.appinn\.com/images/201407/lcf\.png
.ark\.letv\.com/s\?vid=
.article\.pchome\.net/Index\.php\?c=Intel&
.as\.sinahk\.net[/&:?=_]
.ashow\.pcpop\.com[/&:?=_]
.asp300\.com/2012adjs/
.asp300\.com/2012js/
.aspjzy\.com/jsweb/js/
.asxxg\.cn/Public/config/Couplet/
.atm\.youku\.com[/&:?=_]
.att\.ydss\.cn/attachments/portal/
.autofan\.com\.cn/zhaoning/.*\.gif
.autofan\.com\.cn/zhaoning/20.*\.jpg
.autofan\.com\.cn/zhaoning/GG-
.autos\.udn\.com/topic/car/include/ad\.jsp
.avlang33\.com/js/float\.js
.avtv\.cc/flash2/banner\.swf
.awaker\.hk/wp-content/uploads/2013/12/T2Ao15XgJbXXXXXXXX_
.awaker\.hk/wp-content/uploads/ok/
.ayxz\.com/images/enkj_small\.gif
.ayxz\.com/images/VStart\.gif
.b5m\.com/images/banner\.jpg
.b5m\.com/static/html/.*/popup\.html\?
.backchina\.com/banners/
.badmintoncn\.com/cbo_gg/
.baidu\.com/brands/yxtg/source/yxCoupletsAd\.js
.baidu\.com/cms/rc/adSideConfig\.json\?
.baidu\.com/img/iknow/wenku/ad/
.baidu\.com/static/api/js/view/select_view\.js
.baidu\.com/tb/cms/game/.*_banner\.
.baidu\.com/tb/cms/game/.*_banner_
.baidu\.com/tb/static-common/swf/worldcup_main\.swf
.baidu\.com/ur/scun\?di=contentunion
.baidud\.cn/aoao/down_
.baishulou\.net/html/
.ballive\.com/jsgg/
.bamuyu\.com/skin/js/bgad\.js
.baoshewang\.com/img/bottom\.js
.baoshewang\.com/img/gg\.js
.baoshewang\.com/img/head\.js
.bbs\.5imx\.com/bbs/logo/advimg/
.bbs\.5imx\.com/bbs/logo/image/
.bbs\.a9vg\.com/showit/img_show\.php
.bbs\.csdn\.net/sda/TopicPageTop\.htm
.bbs\.fengbao\.com/image/bingzuan925X80\.jpg
.bbs\.hotavxxx\.com/images/201.*\.gif
.bbs\.voc\.com\.cn/s\.js
.bbs\.winning11cn\.com/temp/.*\.gif
.bbs\.xbaodi\.com/plugin\.php
.bbs\.xiashanet\.com/js/adsview\.js
.bbs\.xinjs\.cn/js/float\.js
.bbs\.yhcgo\.com/attachment/Mon_1112/74_1_5c13cbc5db6ba7c\.jpg
.bcc\.com\.tw/imgs/adv/
.bccn\.net/aaa/
.bdimg\.com/brands/yxtg/source/juhe-v2\.js
.bdimg\.com/newmap/static/common/images/nav-ad_
.bdimg\.com/site/games/yxtg/.*\.js
.bdinfo\.net/bdinfo_skin/xlsgg\.js
.bdstatic\.com/api_hao123AdvHeader\.js
.bdstatic\.com/cms/mbox/audioad/AudioAd\.js
.bdstatic\.com/pc_static/detail/game_promotion/
.bdstatic\.com/tb/cms/com/game/couplet_
.bdstatic\.com/tb/cms/img/tieba_index_banner960x90\.png
.bdstatic\.com/tb/r/image/2014-06-05/3a51a66567d15cb0b6096aecd8086f34\.gif
.bdstatic\.com/tb/static-encourage/widget/worldcup_guess_item/images/wish_card_back_
.bdstatic\.com/tb/static-ucenter/img/cont_sign_card\.gif
.bdstatic\.com/tb/zt/tengfei/gzdialog\.jpg
.beanfun\.com/playweb/adpicpage\.htm
.beephone\.com\.tw/ad-middle\.php
.bego\.cc/img/
.bejson\.com/imgs/tuo\.png
.bestxl\.com/langzi/0403/ld\.jpg
.bf2\.zzc\.cn/b/live_b
.bforu\.info/03\.jpg
.bh111\.com/js/tan_center\.js
.binhuo\.com/bhjs/
.bio-equip\.com/dimg/
.bio-equip\.com/dimgs/
.bio-equip\.com/images/esco06\.swf
.bio-equip\.com/uploadimages/peiqing\.gif
.bitauto\.com/js/sense.*\.js
.bitauto\.com/ResourceFiles/play/play\.swf
.bitautoimg\.com/ResourceFiles/0/0/.*\.swf
.bitautoimg\.com/ResourceFiles/0/1/25/20140812055114956\.jpg
.bitcoin8btc\.qiniudn\.com/wp-content/uploads/.*/500-90\.jpg
.bitscn\.com/pic2009/a.*\.js
.biz.*\.sandai\.net[/&:?=_]
.biz\.gexing\.com[/&:?=_]
.biz\.lyd\.com\.cn/20
.biz\.weibo\.com[/&:?=_]
.biz37\.net[/&:?=_].*\.swf\?uid=
.bj\.house\.sina\.com\.cn/iframe/
.bjmxw\.net/bd/
.bkill\.com/css/abc/
.bkill\.com/css/js/bkill\.js
.bkill\.com/images/di\.js
.blog\.51cto\.com/js/poptop\.js
.blog\.sina\.com\.cn/lm/iframe/article/qing2\.html
.blog\.sina\.com\.cn/lm/iframe/article/searchqing\.html
.blog\.tianya\.cn/tuijian/tanchu\.js
.bmp\.ali213\.net/js/
.bmp1\.ali213\.net/js/
.bokeboke\.net/wp-content/uploads/
.book\.58xs\.com/news_gonggao\.js
.bookabc\.net/js/tt\.js
.bookabc\.net/js/xian
.bookgew\.com/hz1/tcby\.js
.bookgew\.com/ml85/
.bookgew\.com/zj85/
.books\.com\.tw/web/apActivityStick\?
.btn\.onlylady\.com[/&:?=_]
.btn\.pchome\.net[/&:?=_]
.bukade\.com/js/tj2\.js
.bukade\.com/tpl/2/loading\.html
.buy\.sina\.com\.tw/js/sina_popup\.php
.buyhouse\.yam\.com/plugin/newsplugin\.php
.buytong\.cn/images/.*%.*\.swf
.bx0635\.com/downimg/2000\.gif
.bx0635\.com/downimg/ban\.gif
.bxtd\.net/heibing/js/tag\.js
.bxwx\.org/1\.js
.bxwx\.org/downad
.bxwx\.org/js/box_
.bxwx\.org/kuping_down\.html
.bxwx\.org/myabc/
.bytravel\.cn/js/ad_
.bytravel\.cn/js/b_
.bytravel\.cn/js/s_
.c1\.74ch\.com/u/mpf/xyz/fi/bVE3T72\.gif
.c1\.74ch\.com/u/mpf/xyz/fi/ZpE3T72\.gif
.c114\.net/default_inc/a/images/
.c168c\.com/.*adv/
.c2000\.cn/c2000/
.c2cc\.cn/c2ccgg/
.c2cc\.cn/images/images2011/ads_bigbg\.jpg
.cachead\.com[/&:?=_]
.caikuu\.com/ckimages/js/.*_gg_
.caipiao\.cntv\.cn/website/cntv/box_news\.shtml
.caoimg\.com/images/
.caomeinv\.info/images/.*\.gif
.cari\.com\.my/cari/banner/
.cari\.com\.my/cari/daybanner/
.cbber\.com/data/attachment/portal/201401/07/101915x2ez2z4f65cka6fz\.gif
.cbfw\.cn/gonggong/js/cf_flash\.js
.cc134\.com/js/ddd\.js
.ccav1\.com/wp-content/themes/BYMT/images/mengmengdeguanggao\.jpg
.ccoo\.cn/image/banner/960\.jpg
.ccoo\.cn/js/dlv.*\.js
.cctv\.com/Library/a2\.js
.cctv5\.name/data/js/
.cctv5\.name/js/.*foot\.js
.ccwzz\.cc/dmf\.js
.cdn\.dfile\.cn/slot/
.cdn\.v2ex\.com/friends/
.cdndm\.com[/&:?=_].*/js/newtc\.js
.cdyee\.com/external/3550\.files/js/dlxin\.js
.cdyee\.com/external/3550\.files/topad-
.centoscn\.com/money/
.cfanclub\.net/lmimages/.*\.jpg
.cfanclub\.net/lmimages/yinsub\.gif
.chao33\.com/t/
.chcj\.net/comiis_ad/
.chidir\.com[/&:?=_]
.china\.com\.cn/food/node_7094923\.htm
.china\.com\.cn/youxi\.swf
.china\.com/zh_cn/etc/gghead950\.html
.chinaacc\.com/lamu/dl-
.chinadaily\.com\.cn/micro-reading/dzh/bd-taofang\.gif
.chinafpd\.net/js/2012-10/
.chinaiiss\.com/images/jianyu_erweima
.chinaiiss\.com/js/function\.ad\.js
.chinanews\.com/shipin/sptp\.xml
.chinaqking\.com/images/qkw/jobApply1\.jpg
.chinatimes\.com/2007Cti/
.chinatimes\.com/2009Cti/cthead/Scripts-utf8/yahoo\.js
.chinawmrc\.com/images/end\.js
.chinaz\.com/2011code_images/A_
.chinaz\.com/2011code_images/soft
.chinaz\.com/2011code_images/topright\.js
.chinaz\.com/ip_gadsense\.js
.chinaz\.com/newshome/
.chinaz\.com/temp_upfile/ads/
.chiphell\.com/activity/
.chuangshi\.qq\.com/upload/cmsv2/Banner/
.cishuge\.com/static/js/xiaoshuo\.js
.citysbs\.com/no/.*/1190x60-
.citysbs\.com/no/.*/650x50-
.citysbs\.com/no/.*/980x60-
.citysbs\.com[/&:?=_].*swf
.cjn\.cn[/&:?=_].*/ad/
.classbm\.hkgolden\.com[/&:?=_]
.clm02\.com/2014-A/FB-6-14-AA1\.jpg
.clm02\.com/2014-A/FB-rayvivi-5-28-B\.jpg
.cncalc\.org/ti/1-10\.png
.cnchu\.com/aps/
.cnchu\.com/templates/cnchu2014/images/13\.jpg
.cnchu\.com/templates/cnchu2014/images/14\.jpg
.cnchu\.com/templates/cnchu2014/images/15\.jpg
.cncrk\.com/505/
.cndesign\.com/Content/img/.*x90_
.cndesign\.com/Content/img/175x60_
.cndesign\.com/Content/img/356x80_
.cndesign\.com/img/ad/
.cndesign\.com/upload/ad/
.cngoldres\.com/advservice/
.cnhubei\.com.*/g2
.cnjxol\.com/.*\.files/sian\.gif
.cnjxol\.com/include/2011/index/js/index\.js
.cnkang\.com/images/kwgbsy\.jpg
.cnkang\.com/images/sy
.cnkang\.com/zixun/nanke/
.cnnb\.com\.cn/image/xhhc71\.gif
.cnnb\.com\.cn/images/14ny_1\.gif
.cnool\.net/js/.*ad
.cnsat\.net/Pictuer/
.cntvboxnow\.com//ads_
.cnwnews\.com/gg200903/nry02\.js
.cnwnews\.com/gg200903/nrzs\.js
.cnzol\.com/page/
.cnzol\.com/template/style/images/wlfloat\.js
.cnzzla\.com/public/scripts/money\.js
.cococomic\.com/g/
.codepub\.com/wuse/pic/
.colafile\.com/cola3/newdown/join\.png
.com\.webmasterhome\.cn/a1-
.cool3c\.com/sites/all/themes/coolthemes/cwww/ysm_
.coolaler\.com\.tw[/&:?=_].*_300x100\.
.coolaler\.com\.tw[/&:?=_].*_340x80\.
.copy\.ousns\.com[/&:?=_]
.cosersuki\.org/2013/03/20140515091120\.jpg
.cosersuki\.org/2014/06/manjidi-ad\.jpg
.cp\.ifeng\.com/iframe/toquickbet
.cpbl-elta\.cdn\.hinet\.net/assets/images/banner-
.cqfishing\.net/data/attachment/portal/
.cqnews\.net:8080/vplayerAdv/
.cqvip\.com/viewserver/ViewAD
.cr173\.com/js/
.cr173\.com/show/
.cr173\.com/skin/gr/js/.*bt_ty\.js
.creativetop\.com/cn/pic/laogu_adv\.gif
.crs\.baidu\.com[/&:?=_]
.cs\.com\.cn/csad/
.cs\.js\.cn/cs2010/script/ks\.js
.cs360\.cn/js/search_zcw\.js
.csdn\.net/ggmm/
.ctrip\.com/amd/2014/1/3/qz/qz180x320\.jpg
.cupid\.qiyi\.com/policy
.cwan\.com/templets/shouye/misc/js/suspend\.js
.cwan\.com/templets/webgame/misc/js/indextip\.js
.d\.taomato\.com/js/HMTP\.js
.d0\.xcar\.com\.cn[/&:?=_]
.d1\.shenchuang\.com/a\.htm
.d586\.com/new2014/cad\.js
.d7ol\.com/pics/ad/
.d7w\.net/static/d7wad/
.da\.df77\.com/ip\.asp
.dagougou\.cc/js/300x50\.
.dagougou\.cc/js/960x90\.
.dailyfx\.com\.hk/ext/lang-ad
.dailynews\.sina\.com/gb/ads/
.danlan\.org/KFC/
.danyang\.com/statics/banner\.swf
.daqianduan\.com/wp-content/uploads/.*/ads\..*\.jpg
.dasai8\.com/js/duilianjs\.js
.dashuye\.com/data/cache/myad.*\.htm
.db28\.cn/cache/ads\.js
.dbw\.cn/0/06/40/95/6409548_017687\.jpg
.dbw\.cn/0/06/73/98/6739849_212270\.gif
.dbw\.cn/ad\.html
.dbw\.cn/js/lanrenzhijia\.js
.dc\.letv\.com[/&:?=_]
.dcfever\.com/campaigns/
.dclick\.autonet\.com\.tw/90/AC_RunActiveContent\.js
.dd\.xdnice\.com[/&:?=_]
.ddooo\.com/duoduo/
.ddooo\.com/js/
.ddooo\.com/viewimg\.asp\?img=
.ddpan\.com/images/adv
.de\.as\.pptv\.com[/&:?=_]
.dealmoon\.com/data/app/banners/
.dealmoon\.com/hotdeals/
.dealmoon\.com/images/n/.*250\.
.dealmoon\.com/images/ul/13/09/30/2qHlKwU\.jpg
.deyangs\.com/img/
.dfad\.dfdaily\.com[/&:?=_]
.dfafei\.com/Runtime/js/qita\.js
.dfafei\.com/Runtime/js/vod300\.js
.dfafei\.com/Runtime/js/vod960
.dfafei\.com/Runtime/js/vod_xiazai
.dfcfw\.com/js/pinzhong/bd_pz_side_
.dfcfw\.com/js/pinzhong/bdbottom_
.dg\.073img\.com[/&:?=_]
.dh2\.kimg\.cn/v/upload/20140828/eecba9649f92d58114a67684c76b73b7\.swf\?
.dhfun\.cn/dhfun_ad/
.diannaoxitong\.com/js/.*\.gif
.dichan\.com\.au/newhouse/pinnacle/images/bcastr3\.swf
.dig\.chouti\.com/advert
.discuss\.com\.hk/dfp_forum\.php\?au=Discuss_Web_
.discuz\.gtimg\.cn/cloud/scripts/discuz_tips\.js
.dj520\.com/js/stj\.js
.djccc\.com/js/a.*\.js
.djccc\.com/js/b.*\.js
.djccc\.com/js/c.*\.js
.djkk\.com/ak/
.djwma\.com/760x902\.gif
.djwma\.com/qq\.jpg
.djwma\.com/tc\.js
.dm456\.com/install/loading\.html
.dm456\.com/m/
.dmfans\.net/template/haokandemanhhua/images/g_js/
.dn-safe\.qbox\.me/wp-content/themes/HotNewspro/images/a\.gif
.dnwx\.com/pic/.*_978x60-2\.gif
.dnwx\.com/pic_ad/
.do189\.com/zb_users/theme/duoyi/style/images/.*\.gif
.docin\.com/app/a_d/
.docin\.com/jsp_cn/ad/
.domeng\.cn/js/index_
.dospy\.com/hezuo/
.douban\.com/misc/mixed_static/529c8492e26293cb\.js
.douban\.com/view/dale-online/dale_ad
.douban\.com[/&:?=_].*/fm_bgad\.js
.doubleclick\.tv002\.com[/&:?=_]
.douguo\.net/upload/post/d/
.down\.admin5\.com/z/
.down\.it168\.com/ggimg/
.down12\.com/htmlg/D.*\.js
.downbank\.cn/jkzm/
.downbank\.cn/s1/
.downbank\.cn/soft6/
.downxia\.com/haojs/
.downxia\.com/zejs/ad.*\.js
.downxia\.com/zejs/y/
.downyi\.com/tg/
.downza\.cn/2013/js/
.downza\.cn/html/skin/default/ad/
.downza\.cn/soft/js/foor\.js
.downza\.cn/topsoft/
.doyo\.cn/Tpl/web/Public/images/material/www_couplets/
.drivergenius\.com/inc/driverwwwad\.js
.duba\.com/images/.*960_60\.jpg
.duba\.com/info/images/ycepf06\.gif
.duowan\.com/img/ad/
.duowan\.com/index\.php\?r=anuncio/getanuncio
.duowan\.com/public/s/market_count\.js
.duowan\.com/s/v2/topHeziAd\.js
.duowan\.com/s/yuanbao-entrance\.js
.duoxiai\.com\.cn/imgad/
.dvs\.china\.com[/&:?=_]
.dwstatic\.com[/&:?=_].*/p/livetip/
.dxsxs\.com/js/dd
.dychao\.com/movie/static/swf/250-250\.swf
.dychao\.com/movie/static/swf/336-280\.swf
.dychao\.com/movie/static/swf/970-90\.swf
.dygod\.net/js/728\.js
.dyhjw\.com/dyhjw/1\.htm
.dyhjw\.com/dyhjw/1/3/471\.gif
.dyhjw\.com/dyhjw/4\.htm
.dyhong\.com/img/ad/
.e\.hnr\.cn/choose/view/%7B.*%7D\.js[/&:?=_]
.e0421\.com/.*tj\.js
.e0421\.com/css/js/bd
.e0421\.com/css/js/tl
.e0575\.cn/images/v1/dl/
.e0575\.cn/js/float\.js
.e0575\.com/pic/AD_
.e23\.cn/ggimages/
.e23\.cn/js/aaa\.js
.e399\.com/html/
.eap\.enorth\.com\.cn[/&:?=_]
.eastlady\.cn/cssjs/indexbaner
.eastlady\.cn/cssjs/indexgg\.js
.eastlady\.cn/cssjs/indextopad\.js
.eastmoney\.com/js/headbiggg_
.ebiotrade\.com/jslibrary/js
.ebiotrade\.com/newsf/js/inpic\.js
.ebiotrade\.com/newsf/js/news_top_banner\.js
.ebp\.renren\.com[/&:?=_]
.ebrun\.com/jfile/lagou\.js
.ebrun\.com/jfile/position/js/.*\.js
.ebuk\.cn/d/file/book/bl/20131102/0526ab8fbca55994501d3b8dc8f8abaf\.jpg
.ebuk\.cn/d/file/p/20131102/01e3e09c7c0677dc0a3d0115da4517eb\.jpg
.ecma\.bdimg\.com[/&:?=_]
.ed2000\.com/Inc/abase\.js
.ed530\.com/template/pptv\.gif
.edu24ol\.com/web_news/images/cj_news\.jpg
.edu24ol\.com/web_news/js/1100\.jpg
.educity\.cn/self_text/text_disp\.aspx\?id=
.eeyy\.com/otherhtml/js/ad650\.js
.eeyy\.com/templates/js/other/yxj\.js
.eeyy\.com/uploadfile/img/beitou
.elecinfo\.com/upload/community/.*\.gif
.elecinfo\.com/upload/community/2014/07/09/1404886082-71690\.jpg
.emarketing\.bot\.com\.tw/output/vi\.aspx\?
.ems183\.cn/images/kiees725\.jpg
.enet\.com\.cn/home/v6/includes/adv/
.enet\.com\.cn/mem_str_zoneid=
.enshi\.cn/images/20140508/pic_69368\.gif
.enshi\.cn/userfiles/esrb/ads/
.eol\.cn/js/eol/
.eol\.cn/js/global/jQuery_ads\.js
.epinv\.com/wp-content/themes/ep/js/single\.js
.eprice\.com\.tw/js/swfobject-2\.3\.js
.erji\.com/acton\.swf
.erji\.net/photo/
.etdown\.net/images/ad1
.etf88\.com/swf/
.eyuyan\.com/attachment/thumb/Mon_1105/158_25295_7df7dd1884b0ash\.jpg
.eyuyao\.com/yyad/
.ezaozi\.com/detail/.*\.js
.ezprice\.com\.tw/ezysm/
.ezprice\.com\.tw/js/.*_ysm_
.familydoctor\.com\.cn/aiframe/
.fang\.com/afp/door/
.fang99\.com/JavaScript/advjs/
.fangying\.tv/assets/960x90-
.fantizi5\.com/js/ad.*\.js
.fantizi5\.com/js/baiduad
.faxingw\.cn/js/.*0
.faxingw\.cn/js/.*ad
.faxingw\.cn/js/.*gg
.faxingw\.cn/js/detailgcbox\.js
.faxingw\.cn/js/jiafa
.faxingw\.cn/js/wenba\.js
.fbook\.net/images_new/L\.
.fbook\.net/images_new/R\.
.fdc\.com\.cn/cms/js/home_js/.*_move_
.fdc\.com\.cn[/&:?=_].*adv
.feng\.com/aoodoo/
.feng\.com[/&:?=_].*/index_treasure/
.fengbuy\.com/recommend-new\.php
.fftxt\.net/js/baidu
.fhm\.com\.tw/fhm_upload/full_ad_
.fhm\.com\.tw/js/colorbox/jquery\.colorbox\.js
.file\.ws\.126\.net/house/.*/js/tc_
.file\.ws\.126\.net/house/jn/.*\.swf
.file\.ws\.126\.net/house/nj/.*\.swf
.files\.webcars\.com\.cn[/&:?=_].*\.swf\?link=
.firefoxchina\.cn/2014/.*_foxphone\.png
.firefoxchina\.cn/res/js/fchina_video-min\.js
.firefoxchina\.cn[/&:?=_].*_bmwbanner\.gif
.fj\.sina\.com\.cn/iframe/63/
.fj007\.com/money/
.fjlyfdc\.com\.cn/hxhad/
.flash\.mycar168\.com/data/js/
.flash8\.net/flash8_a_d_s/
.flvcd\.com/image/partner/
.flvxz\.com/js/xiaodao\.js
.fmdisk\.com/ima/
.fmdisk\.com/templates/123/images/
.focus\.cn/common/js/adm
.forum\.51nb\.com/images/
.forum\.techweb\.com\.cn/advtcnt\.php
.fragment\.firefoxchina\.cn/html/
.free-cn\.com/logo/315x120
.free-cn\.com/logo/qq_gg\.
.free-cn\.com/logo/xierguanggao\.
.freegroup\.org/images/sien-banner-
.freep\.cn/lianjie/xuanfuwang\.js
.fsehome\.com/images/ad_tan\.js
.fspcdn\.com/main/fis/js/v11/play/pop-ad_
.fulikong\.com/images/yulecheng
.fuliqu\.com/js/bejson_common\.js
.fun\.ynet\.com[/&:?=_]
.funtude\.com/include/inc/ad_data\.
.fx678\.com/include/Index_AD/
.fxxz\.com/show/
.fzbm\.com/bbs/static/js/bma\.js
.g\.163\.com/.*&affiliate=
.g\.cnzz\.cn/Static/js/.*-
.g\.gxorg\.com[/&:?=_]
.g\.hsw\.cn[/&:?=_]
.g\.jinti\.com/f/a/a
.g\.rexian\.net\.cn/js/
.g1\.0573ren\.com[/&:?=_]
.g1\.sdo\.com[/&:?=_]
.g4\.beva\.com/data-js-
.gamefy\.cn/cookiead\.php
.gamersky\.com/bgpic/
.gamersky\.com/img/
.gamersky\.com/piaofu.*/
.gamme\.com\.tw/ga/
.ganjistatic1\.com[/&:?=_].*-banner-
.ganjistatic1\.com[/&:?=_].*/adm/
.ganjituiguang\.ganji\.com[/&:?=_]
.gaofen\.com/source/plugin/gaofen_ad/
.gd\.sina\.com\.cn/iframe/22/
.gdtv\.cn/2014/0616/1402914668473\.png
.gexing\.com\.cn/statics/images/1a\.jpg
.gexing\.com\.cn/statics/images/250x200\.jpg
.gexing\.com\.cn/statics/images/jr\.jpg
.gexing\.com/api/api_get_tankuang\.php\?
.gezila\.com/gimg/yinsu
.gfan\.com/plugin\.php\?id=gfan_viewpic:gfan_adView
.gfan\.com/press/
.gg-art\.com/anod/
.gg\.kugou\.com[/&:?=_]
.gg\.xunying\.com[/&:?=_]
.gg\.yxdown\.com[/&:?=_]
.gg163\.net/2014ad/
.gg163\.net/js/gg163ad\.js
.gg1z\.com/pic/hengfu\.gif
.ggg\.zj\.com[/&:?=_]
.ggmee\.com/files/img/ad/
.ggw\.gusuwang\.com[/&:?=_]
.ggw\.watertu\.com[/&:?=_]
.ghjie\.com/images/2012/images/bg
.ghjie\.com/JS/youcegg\.js
.ghoffice\.com/bbs/attachment/Fid_.*\?
.ghoffice\.com/bbs/js/float\.js
.ghostxp3\.com/xf\.js
.global\.tianyaui\.com/global/wizard/js/wizard\.js
.gminfo\.cn/flash/
.gminfo\.cn/js/ad-
.gminfo\.cn/qds/gmszyy\.swf
.gmw\.cn/banner/
.go\.hangzhou\.com\.cn[/&:?=_]
.go2tutor\.com/lifebox\.asp
.gohubei\.com/img/tuniu\.jpg
.gohubei\.com/img/zhuna\.gif
.good\.gd/good\.gd/js/downloadPrograss\.js
.good\.gd/js/loadpopads\.aspx
.goodlife\.tw/system/banners/
.goto\.www\.iciba\.com[/&:?=_]
.gougousoso\.com/css/dy\.js
.goyeah\.com/homepage\.html
.gpcxw\.com/file/js/img/.*\.gif
.gpsdlm\.com/images/jdyigou\.jpg
.gpsdlm\.com/images/lm2\.jpg
.gpxz\.com/js2/
.gpxz\.com/skins/gupuxiazai/soft
.gqgc\.sz\.zj\.cn[/&:?=_]
.greatwuyi\.com/tplimg/1\.files/ad
.greenxf\.com/asp/
.greenxf\.com/GreenxfAD/
.greenxf\.com/img/46860\.gif
.greenxiazai\.com/greenjs/
.greenxiazai\.com/jsgreen/
.gridsumdissector\.com/track\.ashx\?gsadid=
.groupa\.onlylady\.com[/&:?=_]
.gscn\.com\.cn/home/images/advscroll\.js
.gscn\.com\.cn/pic/0/10/34/27/10342786_994137\.gif
.gter\.net[/&:?=_].*adv
.gtimg\.com/news/news/2014ad/
.gtimg\.com/sports/000_AD/
.gtimg\.com/www/asset/project/qqDownload_
.gtimg\.com/www/test/300_250\.swf
.gtimg\.com[/&:?=_].*/ad/
.gtv\.com\.cn/public/images/2014-03/20/71_12931395286234\.jpg
.guofs\.com/images/578-60\.gif
.guofs\.com/images/you\.js
.guqu\.net/Cooperate/
.gusuwang\.com/api/gsw_
.gusuwang\.com/ymsextweb/fullggw/
.gusuwang\.com/ymsextweb/javascript/gs
.guyizhou\.cn/temp/pix/tuijian/topbanner\.js
.gx\.xinhuanet\.com/images2007/banner\.htm
.gxnews\.com\.cn/cache/wwwads\.js
.gxnews\.com\.cn/clientscript/index_duilian_
.gxorg\.com/2014/0523/20140523034947291\.gif
.gxorg\.com/index\.php\?m=poster&
.gywb\.cn/gggl/content_gg/
.gz\.xinhuanet\.com/2012image/mt\.swf
.gzcol\.com/uploads/ad/
.haha\.mx/upload/data/.*_banner\.html
.haha\.mx/upload/data/list_sidebar_
.hanfanba\.com/template/hanfanba/img/tb-
.hangzhou\.com\.cn/extra/flash/hzwarticle300\.swf
.hangzhou\.com\.cn/images/flashyingpian\.swf
.hangzhou\.com\.cn/inc_hzw/
.hanzify\..*/Main/Template/Images/chinabank\.gif
.hao\.rising\.cn/catalog/bottom\.html
.hao\.rising\.cn/images/nsdgg\.jpg
.hao123\.com/data/v/stuff\.php\?.*_forhao123Adv
.hao123img\.com/res/ecom/
.hao6666\.info[/&:?=_].*\.js
.haochi123\.com/J_Box/Inc_Tuan_Main\.htm
.haodai\.com/src/i/lianmeng/ad/
.haofs\.com/haofs/ggapi\.asp
.haoghost\.com/js/hy_cpc_print\.js
.haokan5\.com/js/haokanjs/2014_
.haokan5\.com/js/haokanjs/playa
.haokan5\.com/js/haokanjs/tj\.js
.haokan5\.com/js/haokanjs/youxiajiao\.js
.haoyu\.me/wp-content/uploads/2013/08/interserver-vps1\.gif
.haoyu\.me/wp-content/uploads/2013/12/aliyun\.jpg
.haxiu\.miaotiao\.com[/&:?=_]
.hc360\.com/images/14826/289x90\.jpg
.hc360\.com/js/hcpop_
.hc360\.com/security/201311/201311151050289368\.swf
.hc360\.com/security/201409/201409021830024990\.jpg
.hdad\.hudong\.com/hdad/
.hdbird\.com/langzi/0.*\.gif
.hdpfans\.com/images/hotapp/
.hdpfans\.com/images/icons/.*x60\.
.hdpfans\.com/images/icons/.*x70\.
.hdpfans\.com/images/icons/.*x75\.
.hdslb\.com/u_user/d5860b108d877b58593a58b0fa9df6c8\.jpg
.hdsq\.cc/data/attachment/portal/
.hebei\.com\.cn/eap/
.hebei\.com\.cn/swf/
.hebei\.com\.cn/sys/online_calc\.js
.hefei\.cc/templates/default/index_ad
.hego123\.net/760-90\.js
.hego123\.net/top\.js
.heiguang\.com/f/uad/
.heiguang\.com/statics/201404/img/tiop-1\.jpg
.heitu5\.com/js/heituad/
.henan\.sina\.com\.cn/iframe/7/
.hexun\.com.*/hx_news/hx_news_finalpage\.js
.hf365\.com/0/13/79/87/13798795_912593\.jpg
.hf365\.com/0/14/31/00/14310068_933922\.png
.hf365\.com/0/14/60/93/14609355_921128\.jpg
.hhcomic\.com/hh/h.*\.js
.hhmanhua\.com/hh/h.*\.js
.hi\.people\.com\.cn/NMediaFile/.*\.gif
.hi\.people\.com\.cn/NMediaFile/2013/0929/LOCAL201309291733411880780280942\.jpg
.hi\.people\.com\.cn/NMediaFile/2014/0408/LOCAL201404081054143353909924823\.jpg
.hiad\.vmall\.com[/&:?=_]
.hiao\.com/node/node_27508\.htm
.hinews\.cn/js/09page/10pagesjbtj
.hjav\.org/ads\.js
.hjav\.org/wp-content/themes/iMovies/js/tc_
.hjav\.org/wp-content/uploads/
.hk-pub\.com/forum/images/banner/
.hk3318\.net/template/2014/images/990X60\.jpg
.hkepc\.com/forum/api/unimhk_
.hkepc\.com/prepared/images/b608\.png
.hkgolden\.com/google_ad
.hkheadline\.com/.*promo/
.hkslg\.com/gaogao/
.hkwb\.net/images/123\.gif
.hlj3\.com/55\.gif
.hn-pc\.com/css/Fun_Div\.js
.hn\.xinhuanet\.com/hnstatics/bannermini
.hn\.xinhuanet\.com/imgs/huayuecheng1\.gif
.hn\.xinhuanet\.com/imgs/klgjad\.jpg
.hn\.xinhuanet\.com/imgs/sycad\.gif
.hongshu\.com/hs/
.hongxiu\.com/images/home20140530\.gif
.hoopchina\.com\.cn/web/ad/
.hot\.580k\.com/share/Ad_
.houdao\.com/bans/
.houdao\.com/images/houdaov3/ban\.png
.houdao\.com/images/ktpd\.jpg
.houdao\.com/images/xxd\.jpg
.house\.inhe\.net/javascript/flashdiv\.js
.house\.jschina\.com\.cn/userfiles/flash/
.house\.jschina\.com\.cn/userfiles/image/20131106/061805022f21d2d8737937\.gif
.house\.sina\.com\.cn/2\.0/abp/
.house\.sina\.com\.cn/2\.0/ads/
.house\.sina\.com\.cn/images/.*/jiaju_1000x120\.jpg
.house365\.com/hfads/
.house365\.com/js/lbpopup\.js
.house365\.com/njads/
.houyi\.baofeng\.net[/&:?=_].*\.html
.how361\.com/data/js\.php\?id=
.how361\.com/images/letou/20130111\.gif
.how361\.com/images/letou/xsbanner\.gif
.hqcx\.net/index\.php\?m=poster&
.hqdoor\.com/Web/
.hrtsea\.com/936x90\.gif
.hs\.cnfol\.com/Cm/Imgs/Load\.gif
.htpc1\.com/newfolder/news/2012-12-21-M%
.httpcn\.com/images/ad_
.httpcn\.com/images/adpic2014/ad
.httpcn\.com/images/fangxiaosan\.jpg
.httpcn\.com/tg/
.httpcn\.com[/&:?=_].*950_120\.jpg
.huacolor\.com/all/
.huacolor\.com/attachment/Mon_1303/68_1353_6a7de60968dafb9\.gif
.huacolor\.com/daocaoren/
.huacolor\.com/nei/
.huainet\.com/index_tg/js/txg\.js
.hualady\.com/static/
.huanqiu\.com/script/HuanQiuAllBottom\.Js
.huanqiukexue\.com/uploads/images/hqkx_11\.jpg
.huanwen\.com/Public/images/banner/
.huarenjie\.com/files/140257728854\.jpg
.hudong\.pl\.youku\.com[/&:?=_]
.huizhou\.cn/webfile/.*/images/scroll\.js
.hunantv\.com/ui/2014/images/hao123\.jpg
.huodong\.liaoing\.com/haibao/2013/800zhinengsuo_0702/zhineng\.swf
.huoone\.com/templets/hanfeng/js/qdtwo\.js
.huoxingyu\.com/images/hxy_350_330\.gif
.hutc\.zj\.cn/skins/hutc2012/js/fp\.js
.huxiu\.com/static/js/jobAds/
.hx95\.com/images/sn88\.gif
.hx9m\.com/ggtp/
.hxjs\.tool\.hexun\.com
.hxland\.com/bbs/static/image/A.*\.gif
.hxland\.com/static/image/TOP1\.png
.hxsd\.com/templets/js/looyu_pop\.js
.hxsxw\.com/gg.*\.gif
.hxsxw\.com/js/float\.js
.i-ab\.com.*/uploads.*/img/
.i-part\.com\.tw/hookimg/20445_13907889291\.jpg
.i-part\.com\.tw/hookimg/21031_14037554331\.gif
.i-part\.com\.tw/hookimg/21034_14026411181\.gif
.i-part\.com\.tw/images2/index/HouseStar/
.i\.alipayobjects\.com/i/ecmng/png/201406/2plz7QqgST\.png
.i\.fgi\.tw/images/survey_of_woman9\.gif
.i\.firefoxchina\.cn/html/taobao_focus_250x250\.html
.i1\.tietuku\.com/02a3173e647f7c99\.gif
.i1\.tietuku\.com/786ccc5694543ada\.jpg
.i1\.tietuku\.com/c04dd1e95ec6f77e\.jpg
.i1\.tietuku\.com/d96cf261bca7214d\.jpg
.i2i2\.cn/uploads/soft/2345\.gif
.iads\.xinmin\.cn[/&:?=_]
.iapolo\.com/myjs/
.iapp\.com\.tw/iapp_ad\.php
.ibook8\.com.*/piao.*\.js
.ibook8\.com/js/b.*\.js
.ibook8\.com/xia.*\.js
.iciba\.com/web/co/ci/
.icili\.com/cpma\.js
.ie\.5500w\.com/market/404230/pop_browser\.js
.ieche\.com/global/.*/ad/
.ieche\.com/InAds/
.ifanr\.cn/wp-content/uploads/.*/banner-
.ifanr\.cn/wp-content/uploads/2014/07/rss-01\.png
.ifeng\.com/bbsfile/js/ifeng_tip\.js
.ifeng\.com/iframe/quickbet
.ifeng\.com/ssi-incs/
.ifeng\.com/statics/comment_baidu\.html
.ifeng\.com[/&:?=_].*&ADUNITID=
.ifengimg\.com/.*/taobaopudi/
.ifengimg\.com/61dc05d2dbce10c0/2014/0818/646500af4b561264917217ec1b75ce89\.gif
.ifengimg\.com/ifeng/sources/
.ifengimg\.com/mappa/
.ifengimg\.com/zhishaofei/js/
.ifengimg\.com[/&:?=_].*-gewindow-
.ifengimg\.com[/&:?=_].*/100-100-
.ifengimg\.com[/&:?=_].*/1000-90-
.ifengimg\.com[/&:?=_].*/1000X90-
.ifengimg\.com[/&:?=_].*/300-300-
.ifengimg\.com[/&:?=_].*/300-300\.
.ifengimg\.com[/&:?=_].*/aplayer\.xml
.ifengimg\.com[/&:?=_].*/hover\.js
.ifengimg\.com[/&:?=_].*/rdn_.*\.js
.ifx\.aifang\.com[/&:?=_]
.ifxtx\.com/js/ad-02\.js
.ifxtx\.com/tp/
.ifxtx\.com[/&:?=_].*589x60\.
.iggyy8\.com/js/v/
.ijia360\.com/data/poster/
.ilovecao\.com[/&:?=_].*\.gif
.im\.zww\.im/images/
.im286\.com/data/attachment/forum/201409/09/164936ipg8e3tgtght7od7\.gif
.image\.6park\.com[/&:?=_]
.image\.hh010\.com[/&:?=_]
.image\.jzmt\.net//default\.jpg
.image\.seowhy\.com/bbs/20
.image\.sportscn\.com/other/live/
.image\.wenweipo\.com/.*/ad_
.images-amazon\.com/images/G/28/book/jiangwei/201404/b100g50b200g120_30075\._V337998063_\.png
.images\.chinaz\.com[/&:?=_]
.images\.csdn\.net/20.*-300-200-
.images\.daynews\.com\.cn/zzbframe/2008daynews/ad/
.images\.dayoo\.com/dywimg/
.images\.gxsky\.com[/&:?=_]
.images\.jurong\.cn/bbs/
.images\.mydrivers\.com/2009
.images\.sohu\.com/bill/
.images\.sohu\.com/cs/
.images\.sohu\.com/ytv/.*\.jpg
.images\.sohu\.com/ytv/.*\.swf
.imanhua\.com[/&:?=_].*/money/
.imanhua\.com[/&:?=_].*/nmoneys/
.img.*\.bet007\.com/image/.*\.gif
.img.*\.titan007\.com/image/.*\.gif
.img.*\.win007\.com/image/.*\.gif
.img\.666nnnn\.com/cps.*\.gif
.img\.86wan\.com/img2/top\.jpg
.img\.baidu\.com/img/iknow/156X200-3\.jpg
.img\.cngba\.com/da/
.img\.cqsq\.com/s/exp/.*_475x60\.
.img\.cqsq\.com/s/temp/
.img\.dm530\.com/fgr/
.img\.hexun\.com.*/wszj/js\.js
.img\.ifeng\.com/tres/html/
.img\.itc\.cn/photo/odzbW9yaZpH
.img\.jcwcn\.com/b/enkj/
.img\.kuai\.xunlei\.com/img/v2/fen/
.img\.stpic\.in/a.*\.gif
.img\.sz\.js\.cn/wj/
.img\.taoguba\.com\.cn/gbimg/
.img\.wangxiao\.cn/images/big_ad\.jpg
.img\.xdsq\.net/wo/adwz\.gif
.img\.xiami\.net/static/img/ad/
.img\.ybbbs\.com/2013/
.img\.ybbbs\.com/2014/
.img\.ybbbs\.com/dx1204\.gif
.img1\.126\.net[/&:?=_]
.img1\.autofan\.com\.cn/swf/
.img1\.efu\.com\.cn/upfile/bew/.*\.swf
.img1\.ijinshan\.com/static/media/curl\.swf
.img1\.jczqw\.com/img/
.img1\.ruyig\.com/80\.png
.img2\.126\.net[/&:?=_]
.img2\.e0575\.com.*/upload/image/
.img2\.e0575\.com//upload/adv/
.img2\.www\.fmdisk\.com[/&:?=_]
.img3\.longyu\.cc/topic/201312/980-6000\.jpg
.imgad0\.pconline\.com\.cn/ivy/image/
.imgn\.jiatx\.com/jiatx/mall/outer/
.imgout\.ph\.126\.net/28186032/Hao-123\.jpg
.imgs\.cc/images/ad_
.imgs\.ebrun\.com/uploads/
.impservice.*\.youdao\.com[/&:?=_]
.inc\.tgbus\.com/frame/youxi\.html
.info\.vip\.iqiyi\.com/promotion/
.inhe\.net/javascript/ad_js/
.inhe\.net/javascript/Jsduilian\.js
.inhe\.net/Uploadfiles/ad_2014/
.inhe\.net/Uploadfiles/adpublish2012/
.inimc\.com//static/image/5PYs
.inimc\.com//static/image/eFkL
.inlishui\.com/index\.php\?m=poster&
.inte\.sogou\.com[/&:?=_]
.iotexpo\.com\.cn/Images/2014VipReg\.swf
.ipeen\.com\.tw/js/frame/ad-actions\.js
.ipeen\.com\.tw/photo/ad/
.iqiyi\.com/player/.*/a\.swf
.iqiyi\.com/player/.*/bannery\.swf
.iqiyi\.com/player/cupid/.*/pageer\.swf
.ishangman\.com/images/aismd/
.italk\.yinsha\.com/god/
.itc\.cn/a/www/index/2014/js/ggcommon
.itcast\.cn/files/image/201303/20130304164842603\.jpg
.itemarket\.com/uploadpic/2013/07/20130711133647453330\.jpg
.iteye\.com/iframe_ggbd/
.ithome\.com/block//hl-head\.htm
.ithome\.com/images/lagou/
.ithome\.com/images/partner/
.ithome\.com/js/recommend\.js
.ithome\.com/NewsUploadFiles/focus/5\.jpg
.itmxc\.com/mxc-news/960x
.itocp\.com/html/gk/.*/.*x50\.
.itocp\.com/html/gk/.*/204x
.itocp\.com/html/gk/topic/topicmain\.html
.itongcheng\.cc/amm/
.itopdog\.cn/itopdog/d.*\.js
.itpub\.net/popwin_js\.php\?
.itv\.hexun\.com
.itxtbook\.com/game/images/kuping
.ivsoo\.com/template/ivsoos\.jpg
.iwebacg\.com/http/js/1\.js
.iweihai\.cn/js/float\.js
.iyaya\.info/newmshow\.php
.javlibrary\.com/js/bnr_
.jb51\.net/2012js/baidu
.jb51\.net/2012js/google
.jb51\.net/js/Dowplayjb51
.jb51\.net/js/list300tupian
.jbtalks\.cc/static/image/custom/sme-web-hosting-splash\.jpg
.jbyf\.net/2011_Ad/
.jbyf\.net/JS/1
.jd\.com/exsites\?spread_type=
.jdcjsr\.com/images/zzgg/
.jdcjsr\.com[/&:?=_].*/jdcgg/
.jdxsw\.net/201400/
.jdxsw\.net/a_d_s_d_d/
.jgzj\.net/bbs/attachments/month_1111/
.jiancai365\.cn/lbad\.gif
.jianhucheng\.com/data/attachment/portal/
.jianli-sky\.com/templets/edu/js/jianli\.js
.jianshen114\.com/images/Advistings/
.jiaodong\.net/a/js/
.jiaonan\.net/image/news/news
.jiasuba\.com/js/jjrjtg\.js
.jiasule\.com/static/js/http_error\.js
.jingnei\.net/data/attachment/album/201303/21/005921r7w6kkw26nh765we\.jpg
.jingnei\.net/data/attachment/album/201309/16/175035getttebba0ycteti\.jpg
.jingnei\.net/data/attachment/album/201406/05/211449le8rofdeb38ir3dd\.jpg
.jinhongweiqi\.com/cache/ads\.js
.jinyici\.com/qq\.js
.jinzhuedu\.com/k/img/swt\.png
.jirou\.com/plus/mytag_js\.php
.jisuxz\.com/2747/
.jitapu\.com/inc/adv
.jiyun360\.com/content/js/aqiooad\.min\.js
.jj\.5ccc\.net/scripts/new/
.jj59\.com/sy/banner\.js
.jj59\.com/sy/ibanner\.js
.jjjaaa\.com/aaa/
.jjjgame\.com/images/ad11\.jpg
.jjplay\.com/cps/
.jkforum\.net/template/default/common/attachAD
.jkpan\.com/open\.js
.jmsyzj\.com[/&:?=_]
.jn\.auto\.sina\.com\.cn/iframe/13/
.jnnews\.tv/indexad/
.jobtong\.com/openSiteAd\?
.joyes\.com/image/06\.jpg
.jpseek\.com/pr/click2\.jpg
.jpwind\.com/images/partner/
.jpwind\.com[/&:?=_].*/scroll\.js
.jq22\.com/css/img/g300x300\.jpg
.jrj\.com\.cn/iframe/zjgjs\.html\?
.jrjimg\.cn/aigu/adcj\.jpg
.jrjimg\.cn/homev2/ad/
.js-1\.pchome\.net[/&:?=_]
.js\.4738\.com/newda/img/994_90_
.js\.a\.focus\.cn/.*_ad/
.js\.cnzz\.cn/js/.*-
.js\.duotegame\.com[/&:?=_]
.js\.mumayi\.net/76090\.gif
.js\.mumayi\.net/9495\.gif
.js\.mumayi\.net/jiujiang26054\.gif
.js\.pub\.tom\.com[/&:?=_]
.js\.shiwt\.com/110\.js
.js\.tlt\.cn/js/
.js\.tv\.itc\.cn/site/play/v.*/vip_discount_
.js\.yankanshu\.com[/&:?=_]
.js\.youxi369\.com[/&:?=_]
.jsd\.haodnss\.com[/&:?=_]
.jsshuba\.com/js/bdhengfu\.js
.jsshuba\.com/js/gg\.js
.jsshuba\.com/js/tongji\.js
.jsw\.com\.cn[/&:?=_].*/index\.htm
.jswangpan\.com/375x75
.jswangpan\.com/haha728\.gif
.jthysh\.com/uploadfile/poster/trt\.swf
.jtyskq\.com/!/20140327/js/_a\.js
.juxia\.com/public/js/foot\.js
.juxia\.com/public/js/juxia\.js
.jx\.xinhuanet\.com/.*banner/
.jxcn\.cn/images/banner/
.jxcn\.cn/js/hotpic_
.jxgdw\.com/2013images/ad/
.jxgdw\.com/images/jdgg\.jpg
.jxnews\.com\.cn/jxcn/con_ad_title\.js
.jxold\.com/index\.php\?m=poster&
.jz123\.cn/kanli/
.jz5u\.com/new/
.jzhome\.cn/Public/images/jyt\.gif
.jzhome\.cn/Public/Js/top\.js
.jznews\.com\.cn/comnews/js/ad_tanchuang\.js
.jznews\.com\.cn/js/.*_tc\.js
.jznews\.com\.cn/js/adtwo\.js
.jznews\.com\.cn/js/n_two\.js
.jznews\.com\.cn/js/topad
.k618\.cn/images/140321zyg\.jpg
.k618\.cn/images/feijiplane\.gif
.k618\.cn/tlgg/
.k6777\.com/.*0\.swf
.k7mm\.com/js/t.*\.js
.kaixin001\.com\.cn/i3/client/hflgad/adlj\.png
.kamlm\.com/kmgg
.kan300\.com/js/union/
.kangxitv\.com/click\.js
.kbcool\.com/other/yytf/
.kekenet\.com/images/2014/
.kekenet\.com/images/kekepic/tom468X60\.gif
.key8\.com/cache/www/banner_
.keywin\.org/templates/kw_v2/images/youbianad\.png
.kfcdn\.com/upload/analysis/20140423/v7ny7ap9fr9hekj9\.jpg
.kfcdn\.com/upload/analysis/20140625/21ln3ovhre9djgri\.jpg
.kfcdn\.com/upload/analysis/20140626/9mmh58z7itqv7g75\.jpg
.kfs\.io/article5/global/.*/original\.gif
.kk55\.net/beitou\.js
.kkkmh\.com/iframe/
.kkkmh\.com/javascripts/abcde/
.klgwdh\.com/pp\.php
.klss\.cn/jc/
.kmplayer\.cn/include/jscript/.*-a\.js
.kmplayer\.cn/include/jscript/.*-b\.js
.knnwdyou\.com[/&:?=_]
.kp52\.cc/data/attachment/portal/
.ktkkt\.com/js/cnbeta/
.ktzhk\.com/file/adv/
.ktzhk\.com/plugins/cache_template/adv_3b2g\.js
.ku6cdn\.com/comm/v/0\.1\.0/mm\.png
.kuaidi100\.com/images/adm/
.kuaihei\.com/js/980
.kuaihei\.com/js/view\.js
.kuaihei\.com/js/xiazaishang\.js
.kuaihou\.com/c/shuoming\.js
.kuaihou\.com/c/you1\.js
.kuaihuo\.me/2\.js
.kuaihuo\.me/3\.js
.kuaihuo\.me/4\.js
.kuaihuo\.me/js/aa\.js
.kuaile222\.com//template/cpanew/images/796054\.gif
.kukudm\.com/js/comic-
.kukudm\.com/js/play-
.kukuplay\.com/plugins/EggModule
.kutj\.com/.*/.*x80\.jpg
.kutj\.com/shijiebei/shijiebei\.gif
.kuwo\.cn/today_recommend/images/201311/1384562617570\.jpg
.kyocdn\.com/forum/201312/20/151925t52ey4l34ck0lkgv\.jpg
.kyocdn\.com/upload/1316059709x983128031\.gif
.l\.qq\.com/lview\?
.l7po\.com/images/tree/
.lab\.feng\.com/images_new/ad-
.lady100\.net/760-90\.js
.lady100\.net/top\.js
.lady1314\.com\.cn/addata/
.lagou\.com/js/cooperation/
.laibafile\.cn/p/m/185038012\.jpg
.laixi\.com/tp/20
.langya\.cn/2014html/2014ad_
.langya\.cn/2014html/ad/
.langya\.cn/images/ad_down\.js
.lanyes\.org/content/templates/default/images/no
.laogu\.com/laogubbs/my/
.laogu\.com/my/ad
.laoyuegou\.com/img/.*/banner/
.laoyuegou\.com/js/.*_couplet_
.law-lib\.com/2009_ad/
.lcxw\.cn/i/AD
.ld0766\.com/.*20.*a/
.leiqun\.snxyf\.com[/&:?=_]
.lekan\.com/.*&stopTime=
.lelevod\.com/js/money/
.lepan\.cc/img/96039\.gif
.lepan\.cc/system/templates/32666/250\.gif
.lepan\.cc[/&:?=_].*/zsz.*\.gif
.letsebuy\.com/static/image/common/dm_cn_130\.jpg
.letvcdn\.com/js/.*_focus_flash\.js
.letvimg\.com/gugwl/.*\.swf
.lh168\.net/extra/ads/
.lh168\.net[/&:?=_].*/attachment/portal/
.liangzijie\.com/Runtime/
.liao1\.com/js/floatVideoAd\.js
.liao1\.com/publicize/file/news_detail_
.liaoing\.com/egou/
.liaoing\.com/henan/js/kejet/0624\.js
.liaoing\.com/image/picture_g/luoyang/index/.*\.swf
.liaoing\.com/image/picture_g/zhengzhou/index/.*\.swf
.liaoing\.com/image/picture_g/zhengzhou/index/20
.life\.e0575\.com[/&:?=_]
.link\.fobshanghai\.com[/&:?=_]
.linkhelper\.cn/mmshow
.links\.cn/mmshow
.linuxeden\.com/plus/web_js\.php
.linuxidc\.com/linuxfile/list
.linuxidc\.com/linuxfile/y9\.js
.liulanmi\.com/labs/x/liulanmi2345\.jpg
.live8bo\.com/j/Lad6\.js
.ln\.xinhuanet\.com/inc/
.lnd\.com\.cn/site1/.*\.swf
.lnzq5\.com/js/shuanglian\.js
.lofter\.com/mailEntry\.do\?blogad=
.longhoo\.net/36732\.files/banner_shi\.gif
.longhoo\.net/36732\.files/kuang_shi\.jpg
.longyu\.cc/adg/
.longyu\.cc/bucket/flash/
.loorin\.com/templets/loorin/images/nubiaxk\.jpg
.loorin\.com/uploads/140616/yijia\.jpg
.loorin\.com/uploads/140903/mx2\.jpg
.ltaaa\.com/data/bg/worldcup\.jpg
.luckstatic\.v1\.cn/st/10000/
.lululu\.cc/wp-content/uploads/.*\.gif
.lululu\.lu/wp-content/uploads/.*\.gif
.lxting\.com[/&:?=_]
.ly\.js\.cn/adv/
.lyd\.com\.cn[/&:?=_].*950-90\.
.lywww\.com/data/js/1
.lywww\.com/data/js/2
.lywww\.com/data/js/3
.lywww\.com/header_pic\.php
.lywww\.com/index_topa\.php
.lz13\.cn/script/.*0
.lzep\.cn/data/js/1.*\.js
.lzep\.cn/images/.*/ad
.lzep\.cn/images/201.*ad/
.m1905\.cn/afp/mdsfw\.js
.m1905\.com/asp_js/k\.js
.macd\.cn/macd-topads\.html
.mail\.pchome\.com\.tw/img/classifieds/300120\.gif
.mail\.pchome\.com\.tw/img/pccenter/freepc1000\.gif
.maipiao\.96900\.com\.cn/js/indexgg
.maipiao\.96900\.com\.cn/jtjt/js/jtjtgg\.js
.maituan\.com/admin/indexflash/pic/gg
.manads\.static\.olcdn\.com[/&:?=_]
.manage\.wdfans\.cn[/&:?=_]
.manhua\.weibo\.com/weimanhuagg/_xCPo85CO\.jpg
.maolihui\.com/wp-content/themes/miao/img/adb
.market\.178\.com[/&:?=_]
.market\.21cn\.com[/&:?=_]
.market\.duowan\.com[/&:?=_]
.masadora\.net/kakusan-
.masok\.cn/red/
.mat1\.gtimg\.com/2014/vikkydu/GA/haier
.mat1\.gtimg\.com/2014/webtips/ola2014tips
.mat1\.gtimg\.com/cq/flash/
.mat1\.gtimg\.com/ent/flash/.*300
.mat1\.gtimg\.com/www/fbgg/
.mbalib\.com/wiki/common/wikibits\.js
.mcncc\.com/yeyou/gg\.js
.media\.cheshi-img\.com[/&:?=_]
.meilele\.com/js/recad\.
.meinv\.com/templates/meinv/js/.*_banner\.js
.meinv24\.com/js/960-
.meishichina\.com/v3/
.meitu\.com/js/floatxiuxiu\.js
.meizhou\.com/data/attachment/portal/
.meizhou\.com/images/topbanner
.message\.csdn\.net/msg\.popup\.js
.mfcad\.com/images/footer_tupian/5\.gif
.mfxp\.com/images/
.mgbbs\.cn/js/float\.js
.mgyun\.com/Files/FriendLink/2014/5/9/175140acc3e\.jpg
.mhhf\.net/fserFiles/711x90\.jpg
.mifengtd\.cn/ad-rishiqing-180\.png
.miljinhua\.com/GD/
.mimg\.127\.net/ggimg/all/img18/140218_yixin_780x96\.jpg
.mimg\.127\.net/m/smartad/img/
.mingxing\.com/js/tuku/_banner\.js
.missyuan\.com/sy/
.mitbbs\.com/ad_
.mitbbs\.com/servicedata/static_ad\.php
.miyun360\.com/data/attachment/portal/
.mlbuy\.com/gg\.js
.mm111\.net/data/js\.php\?id=
.mm111\.net/dotnet/artemis/u/cms/www/201406/12093713ux9h\.png
.mm111\.net/dotnet/artemis/u/cms/www/201408/14103834esje\.jpg
.mm111\.net/dotnet/artemis/u/cms/www/201408/141039144xys\.jpg
.mm387\.com/images/.*\.gif
.mnspx\.com/js/bdbd/
.mobile01\.com/300x100\.swf
.money\.qz828\.com[/&:?=_]
.moonbt\.com/template/skin1/images/g_js/
.mopimg\.cn/dc/
.motorfans\.com\.cn/iggs_system/
.ms211\.com/211tf/
.ms211\.com/js/tf\.js
.mscbsc\.com/gbook/telecomhr292x90\.gif
.msn\.people\.com\.cn/css/2010tianrun/
.msn\.ynet\.com/vtui_js01\.js
.mt30\.com/ok/
.mtksj\.com/images/2345\.gif
.mtksj\.com/images/ad1225\.jpg
.mtksj\.com/images/icoean\.gif
.mtrend\.cn/images/prome/
.mtrend\.cn/images/tmall/
.muyuge\.com/js/bb/
.muyuge\.com/js/KillABP\.js
.mwsl\.qiniudn\.com/250x250-
.mwsl\.qiniudn\.com/puma-faas300v3\.jpg
.mwsl\.qiniudn\.com/wp-content/uploads/2014/06/duckduckgo\.png
.my0511\.com/.*/ad_
.my0511\.com/aadd/
.my0832\.com/xyz/upload/
.myad\.toocle\.com[/&:?=_]
.mybjx\.net/theme/default/js/common/duilianchn\.js
.mybjx\.net/theme/default/js/common/mtibjx\.js
.mycodes\.net/js/down_txt\.js
.mycodes\.net/js/hf_txt\.js
.mydrivers\.com/images/drivergenius\.png
.mydrivers\.com/www/2014/code_lb_
.myexception\.cn/u/cms/www/bf\.gif
.myhack58\.com/abcd01/
.myhack58\.com/acdb02/
.myhack58\.com/js/banner\.js
.myhack58\.com/js/top
.mymusic\.net\.tw/upload/mobile_web_tmp/indexad01\.
.mywpku\.com/.*-banner\.
.mywtv\.cn/public/allAds\?
.mzyz\.com/image/tj/
.n2\.hk/promo/
.namipan\.cc/baidu/
.namipan\.cc/includes/js/digg\.js
.nanrenshu\.com/rmb/st_dh\.js
.nanrenwo\.net/theme/2013/js/popup.*\.js
.nanrenwo\.net/theme/2013/js/top\.js
.narutom\.com/js/jsg2\.js
.narutom\.com/v2/js/ca\.js
.ncdiy\.com/webindex/300-250AD\.swf
.ncnews\.com\.cn/65\.files/wb_
.ncnews\.com\.cn/images/ty_ewm\.js
.ncnews\.com\.cn/images/tyzp_20140313_logo\.jpg
.ncnews\.com\.cn/images/wb_duilian_web\.js
.ncnews\.com\.cn/tywwxj/
.neihan8\.com/templets/default/images/dubo
.neihan8\.com/templets/default/images/porf\.jpg
.nen\.com\.cn/eap/
.nen\.com\.cn/service/js/beitou
.neotv\.com\.cn/images/avs/tc/tc\.js
.neotv\.com\.cn/wp-content/uploads/2014/06/20140505\.jpg
.neotv\.com\.cn[/&:?=_].*/620x70\.
.new-icon\.ol-img\.com/article/xinjiemeng/img/728x90gaoxiao\.jpg
.new-icon\.ol-img\.com/jslib/ad_new\.js
.newft\.com/template/comiis_snx3deyi/ads/
.newhua\.com/newhuagg/gg_search_
.news\.0898\.net/NMediaFile/.*\.gif
.news\.0898\.net/NMediaFile/.*\.swf
.news\.cn/forum/script/float2\.js
.news\.cn/xilan/20120615/xliphonetit1\.gif
.news\.hz66\.com/IAA/201111/
.news\.sina\.com\.cn/js/792/.*head.*\.js
.news\.sina\.com\.tw/js/ti\.js
.news\.tom\.com/v2008\.js
.news\.xdkb\.net/img/attachement/png/site2/20130603/3859f9e3a59613168bea0c\.png
.newsgroup\.la/ad/yahoo/fad\.gif
.newsgroup\.la/search/ysm/pam430x80\.swf
.newsmth\.net/nForum/baiduunion/
.newsmth\.net/nForum/files/adv/
.nextmedia\.com/web_images/recruit_banner\.jpg
.ngacn\.cc/common_res/js_adscommon\.js
.nilongdao\.com/include/js/Copyright
.niutuku\.com/skin/img/830x90\.gif
.njdaily\.cn/templates/njdaily2014/widget/njdaily-slideAds
.nmg\.xinhuanet\.com/sy/images/.*\.swf
.nmgnews\.com\.cn/0/10/71/66/10716601_990205\.gif
.no1\.168abc\.net/upload/
.nokiacn\.net/baidu\.htm
.northtimes\.com/huodong/02/js/ad-
.ntu\.me/di/COFM0/2\.jpg
.nueiu\.r\.haizhangs\.com/js/nueiu\.js
.nvsheng\.com/js/gg\.js
.oa\.hinews\.cn/work/img/
.oeeee\.com/static/js/AD2v1\.1\.js
.offcn\.com/qzzn/
.okbmf\.com[/&:?=_].*950_120\.jpg
.on\.cc/js/v2/iframe_ysm_
.onegreen\.net/MyFile/
.oogps\.com/oogps/aiostech\.jpg
.opera\.by-fan\.net/content/uploadfile/201408/6bc21407810441\.jpg
.opera\.by-fan\.net/content/uploadfile/201408/dc1e1408832001\.gif
.orsoon\.com.*/zhuanti/
.oschina\.net/uploads/ad/
.oyksoft\.com/show/s\.php/
.p\.37youyou\.com/.*\.jpg
.p\.aty\.sohu\.com/p\?cat=
.p\.szonline\.net[/&:?=_]
.p\.tanx\.com/ex\?i=
.p\.zol-img\.com\.cn[/&:?=_]
.p3\.img\.cctvpic\.com/photoAlbum/page/performance/img/2013/11/20/1384944092228_124\.jpg
.p4p\.sina\.com\.cn[/&:?=_]
.padhz\.com/pic/data/0000/04/14055677861419\.gif
.padhz\.com/webimg/slide/nokillad
.paipaitxt\.com/bans/
.panda\.kdnet\.net[/&:?=_]
.pc0359\.cn/data/xzb_haha\.js
.pc0359\.cn/sczy/
.pc3w\.com/js/
.pc6\.com/js/un/
.pcbeta\.com/static/image/5PYs
.pccoo\.cn/js/dlv1\.0\.js
.pcgames\.com\.cn/download/newnq/
.pcgames\.com\.cn/jctj/
.pchome\.com\.tw/js/idlead\.js
.pcjishu\.com/other/yj300x3006\.jpg
.pconline\.com\.cn/_hux_/index\.js
.pconline\.com\.cn/download/.*/intf.*\.js
.pconline\.com\.cn/js/ad_
.pconline\.com\.cn/js/ivy\.js
.pcpp\.com\.cn.*/pcpp\.jpg
.pcpp\.com\.cn/news/a/.*_article_right\.html
.pcpp\.com\.cn/news/ad/
.pcs1\.app\.joy\.cn[/&:?=_]
.pcstore\.com\.tw/css/myacc_init\.js
.pctowap\.com/img/bs\.jpg
.pctowap\.com/img/bs2\.jpg
.pcworld\.com\.cn/Article/UploadFiles/201403/2014031016150885\.jpg
.pediy\.com/temp/ajm\.jpg
.penglai\.com\.cn/template/default/js/index/topfloat\.js
.people\.com\.cn/img/2013people/wza/domready\.js
.people\.com\.cn/img/gjt/
.ph66\.com/bbsgg/
.ph66\.com/js/float\.js
.pharmnet\.com\.cn/cnbanner/
.pharmnet\.com\.cn/image/upload/images/20140619_162612\.gif
.pharmnet\.com\.cn/js/float_div\.js
.photo\.erji\.com[/&:?=_]
.photofans\.cn/cooperator/banner/
.php100\.com/statics/sem/chuangen\.gif
.phpad\.cqnews\.net[/&:?=_]
.phpcms\.cn/statics/images/video/ad
.phpfans\.net/image/sponsors/
.piao\.com\.cn/Flash/Scripts/FloatLeftRight_
.piaodown\.com/other/.*\.js
.piaohua\.com/js/wlfloat\.js
.piaoliang\.com/js/gg\.js
.piaoliang\.com/js/gg_.*\.htm
.piaoliang\.com/ruanwen/
.piaoliang\.com/uploads/allimg/.*\.gif
.pic\.0597kk\.com[/&:?=_]
.pic\.2u\.com\.cn[/&:?=_]
.pic\.959\.cn/media/js/
.pic\.ea3w\.com[/&:?=_]
.pic\.fengniao\.com[/&:?=_]
.pic\.gongkong\.com/UploadPic/gongkong/
.pic\.taian\.com[/&:?=_]
.pic\.xgo-img\.com\.cn[/&:?=_]
.pic\.yupoo\.com/heidongke_v/DMI8TWao/11YsLR\.png
.pic\.yupoo\.com/heidongke_v/Dz3G6aBA/kSHc3\.gif
.pic\.yupoo\.com/showflash/
.pic\.zol-img\.com\.cn/20.*background
.pics\.wanlibo\.com/js/pagemodulestat\.js
.pinggu\.org/static/pinggu/float\.js
.pinglun\.sohu\.com/sogouad\.html
.pingpang\.info/banner/
.pingpang\.info/bbs/UploadFile/2013-1/2014tt\.gif
.pingpang\.info/bbs/UploadFile/2013-11/xiom\.gif
.pingpang\.info/bbs/UploadFile/2013-6/sword\.gif
.pingpang\.info/bbs/UploadFile/2014-5/201455214543955851\.gif
.pingpang\.info/bbs/uploadflash/2014baxi\.swf
.pingpang\.info/bbs/uploadflash/jinyu\.swf
.pingpang\.info/themes/v1\.0/images/yasaka\.
.pingpang\.info/uploadfile/950X90B\.gif
.pingpang\.info/uploadfile/butterfly\.gif
.pipi\.cn/player/
.pixfs\.net/js/mib\.min\.js
.pixfs\.net/js/mib_falcon\.
.plures\.net/scripts/widget/tips\.js
.plurk\.com/Ads/
.poco\.cn/mypoco/myphoto/20140107/22/5939544420140107221444048\.jpg
.poco\.cn/mypoco/myphoto/20140330/21/5589980820140330214657064\.jpg
.poco\.cn/mypoco/myphoto/20140418/18/5589980820140418182334072\.gif
.poco\.cn/mypoco/myphoto/20140423/19/5589980820140423191248067\.gif
.poppur\.com/banner/962x100\.gif
.poster\.weather\.com\.cn[/&:?=_]
.poto\.kikicici\.com/up_files/2013-11-25/1385390346MPIr\.jpg
.poxiao\.com/template/default/images/12345\.js
.pp\.7060\.com[/&:?=_]
.pps\.ipart\.cn/comp/hooks\.php
.ppsimg\.com/ipd/fe_res/srcmin/sup/pages/.*/flet\.js
.ppsj\.com\.cn/images/ppsj300\.gif
.ppsj\.com\.cn/images/usa_250_120\.gif
.pptiyu\.com/index/js/float\.js
.price\.com\.hk/dfp_price\.php\?
.price\.com\.hk/scripts/ysm\.js
.pro\.iweihai\.cn[/&:?=_]
.promotion\.msn\.com\.tw[/&:?=_]
.ps123\.net/MyFile/
.ptfish\.com/08html/
.pub\.funshion\.com[/&:?=_]
.pub\.mop\.com[/&:?=_]
.pub\.stockstar\.com/feedback/
.publicize\.liao1\.com[/&:?=_]
.publish\.ad\.youth\.cn[/&:?=_]
.pzzc\.net/data/attachment/ad2/
.q\.115\.com/static/uploads/cheese/.*\.gif\?
.qbaobei\.com/data/attachment/portal/201310/23/171807xmyi29gah8cypbh6\.gif
.qbaobei\.com/data/attachment/portal/201310/23/171915wh3ox3oiwck3dwxo\.jpg
.qbaobei\.com/IAA/
.qdjimo\.com/html/js/
.qdmm\.com/javascript/NewSNDAPop\.js
.qdmm\.com/javascript/SNDAADAltern\.js
.qfans\.net/js/open
.qhnews\.com/tupian/
.qidian\.com/javascript/abc\.htm
.qidian\.com/Javascript/DoublePop\.js
.qidian\.com/javascript/fkky\.js
.qidian\.com/Javascript/NewSNDAPop\.js
.qidian\.com/javascript/ppccload\.js
.qidian\.com/javascript/SNDAADAltern\.js
.qidian\.com/ploy/.*swf
.qidian\.com/ploy/cloudary08/
.qikzj\.u\.qiniudn\.com/wp-content/uploads/.*/280X280_
.qikzj\.u\.qiniudn\.com/wp-content/uploads/.*/ad-
.qilanxiaozhu\.co/data/attachment/portal/
.qilanxiaozhu\.com/data/attachment/portal/
.qilindao\.com/data/attachment/portal/
.qingdaonews\.com/images/36024\.files/360da\.gif
.qingkai\.com/2009/html/top\.htm
.qingkai\.com/gg_img/
.qiniudn\.com/plusvps\.png
.qiniudn\.com/sites/default/files/boltfree\.png
.qiniudn\.com/sites/default/files/FeQuan_0\.jpg
.qiniudn\.com/uploads/new/banner/540847a64f4a5\.jpg
.qinmin8\.com/api\.php
.qisuu\.com/js/bottem_new\.js
.qitete\.com/sp/
.qiuyi\.cn/qiuyi/cooper/
.qiuziti\.com/img/rightp20\.gif
.qiyipic\.com/common/20130801/6abde0a49dde432b8dc30548880f0529\.jpg
.qj001\.com/data/js/js0\.js
.qjis\.com/js/qjis_nr\.js
.qm120\.com/images/adZhayou\.jpg
.qpic\.cn/mblogpic/829ff64132ceec61b372/2000
.qpic\.cn/mblogpic/f7052e063cec814c8a44/2000
.qq\.com/bbs/bbs_topgg\.htm
.qq\.com/js/2013js/ad_float_
.qq\.com/swf/sx_ads\.swf
.qqcf\.com/js/Content_Get\.js
.qqjia\.com/dan\.js
.qqjia\.com/images/ad
.qqkj\.cn/js/qqkjnew/lanmuzhuantitongji\.js
.qqread\.com/swf/
.qqtn\.com/js/page_970\.js
.qqyy\.com/js/commAdv
.qqyy\.com/js/public_end_add\.js
.qstatic\.com/baike/js/ad_
.qtfy30\.cn/980-90\.gif
.quanji\.com/static/bd/
.quick8\.cn/softimg/.*AD\.gif
.qunaso\.cn/Data/upload/ad/
.qusu\.org/pic/uploadimg/950-90\.gif
.quumii\.com/img/top_nav/sp_topbar\.png
.qz828\.com/css/2010/script/.*ad
.qzntv\.com[/&:?=_].*\.swf
.qzss\.cn/ssad
.ranwen\.net/ssi/
.rar8\.net/htmljs/
.read\.2200book\.com/images/bloading\.gif
.ref\.so/templates/ref/images/client/tg.*\.jpg
.renren\.com/pages/seo/reg_seo_pop\.js
.rentiyishu\.org/.*\.js
.res\.cngoldres\.com/web/index/img/.*_ad_
.res\.cngoldres\.com/web/js/.*_advs\.js
.res\.files\.131\.com/webroot/v2012/images/bg_yun\.jpg
.res\.ganyou\.com/img/75/23/13958078472375\.gif
.res\.ythouse\.com/image/index/2012/
.resource\.updrv\.com/drivers/img/tu_
.rexuedongman\.com/scripts/show/3
.rexuedongman\.com/scripts/show/a
.rexuedongman\.com/scripts/sui
.rfidworld\.com\.cn/js/a\.js
.rfidworld\.com\.cn/js/b\.js
.rfidworld\.com\.cn/js/c\.html
.rh\.qq\.com[/&:?=_]
.right\.com\.cn/logo/jlu\.gif
.rising\.cn/index/20130717/images/wifiad\.png
.rising\.com\.cn/weblog/
.rizhao\.net/html/js/main\.js
.rkanr\.cn/upload/2013/12/31/165683e8-bab4-4c6a-b28b-22ca7a60c1f6\.jpg
.rkanr\.com/Content/image/Common2013/signUp\.jpg
.rkanr\.com/data/cpcache/cp.*\.js
.rosmm\.com/ad_js/
.rosmm\.com/chat/xxx/
.rsccs\.com/code/
.rsdown\.cn/static/t/
.ruan8\.com/img/foot\.js
.ruan8\.com/img/head\.js
.ruanyifeng\.com/blog/images/ad_
.ruian\.com/img/y13/
.ruian86\.com/img/y13/
.runsky\.com/bbsadv-
.runsky\.com/html/.*_index_
.ruten\.com\.tw/js/ahd_
.ruten\.com\.tw/js/gads_
.rxs\.cc/js/inc/
.rznews\.cn/images/col/201308ydfy\.gif
.rznews\.cn/liv_loadfile/.*\.swf
.rznews\.cn/liv_loadfile/folder1021/fold5/1373610421_63369500\.gif
.s-msn\.com/msnportal/hp/luckyday/
.s-msn\.com/portal/xiatui\.js
.s\.tankr\.net/n/
.s\.tkurl\.com
.s\.u17t\.com/leaflet/upload/
.s\.yimg\.com/ja/ap/hk/rm/hk_rm_tab_20140226\.js
.s1\.pplive\.cn/sta\.js
.s3-ap-northeast-1\.amazonaws\.com/unalisbucket/10/
.s3-ap-northeast-1\.amazonaws\.com/unalisbucket/4/
.s3-ap-northeast-1\.amazonaws\.com/unalisbucket/9/
.saaee\.com/view/youkuvip/.*ad\.gif
.same\.chinadaily\.com\.cn[/&:?=_]
.same\.eastmoney\.com[/&:?=_]
.same\.stockstar\.com[/&:?=_]
.sax\.sina\.com\.cn/crossdomain\.xml
.sc\.chinaiiss\.com/do\.php\?do=ad&
.sc\.tom\.com[/&:?=_]
.scol\.com\.cn/js/def_
.scol\.com\.cn/scol-3/js/08scol_text_
.script\.cmfu\.com/ADScript/
.script\.cmfu\.com/Script/GameAdAptationInfo\.js
.sd\.sina\.com\.cn/auto/iframe/13/
.sd\.xinhuanet\.com/2014xb/flash/
.sd\.xinhuanet\.com/2014xb/html/albbg\.htm
.sd\.xinhuanet\.com/2014xb/images/shanhang\.gif
.sd173\.com/images/1209\.png
.sdgundam\.cn/upload/2014-07/dca9b1a643b1f3ca\.jpg
.sdo\.com/static/image/mkads/
.seazor\.com/images/other/
.sex169\.net/images/2014/.*\.gif
.sex169\.org/images/2014/.*\.gif
.sf-express\.com/cn/sc/\.galleries/sfbest/.*_right_sc\.
.sfile\.baidu\.com/%E6%97%A0%E6%A0%87%E9%A2%98\.png
.sfile\.baidu\.com/img/load\.gif
.sg169\.com/resource/2013.*\.swf
.sg169\.com/tp/news/
.sgg\.southcn\.com[/&:?=_]
.sh\.sina\.com\.cn/iframe/408/
.sh\.sina\.com\.cn/iframe/522/
.sh114so\.com/js/nm.*\.js
.shabc\.net/shyk/swt/swt_yh\.js
.shang\.hlgnet\.com/code/
.shang\.hlgnet\.net/code/
.shangdu\.com/1002/1002030101\.js
.shangdu\.com/1002/1002030801\.js
.shangdu\.com/1002/1002030901\.js
.shangdu\.com/1002/1002031301\.js
.shangdu\.com/comiis_ad/
.shangdu\.com/lyinfo/ad/
.shangdu\.com/newfile2007/ad/tu/flash/3dboard\.swf
.shanhe\.cc/index\.php\?m=poster&
.shanhe\.cc/Scripts/ads_dl\.js
.shanhe\.cc/Scripts/main-pf\.js
.shaoxing\.com\.cn[/&:?=_].*gg\.
.share\.gzdsw\.com[/&:?=_]
.shared\.ydstatic\.com/images/hao163/600-45_2\.jpg
.shenmaxiaoshuo\.com/js/hf
.shenmaxiaoshuo\.com/js/lu\.js
.shenmaxiaoshuo\.com/js/mu\.js
.shfq\.com/data/attachment/portal/
.shixin\.court\.gov\.cn/static/images/xglHammerEdge\.jpg
.shixin\.court\.gov\.cn/static/javascript/move\.js
.shm\.com\.cn/css/m\.js
.shm\.com\.cn/js/load\.swf
.shm\.com\.cn/shm/Html/Item/conn\.js
.shopping\.udn\.com/mall/cus/cat/OutWebAd\.do\?
.shoubow\.com/temp/banner/playgg\.htm
.shoudian\.org/diantong/sunwayman.*\.gif
.shouyou\.com/2013/new/shouyou-duilian\.js
.shouyoucdn\.com/images/www/index/.*-600x110\.
.showfom\.sexy/files/2014/04/23/809abc04c5cbc2a9cdcab853999a4dc6\.jpg
.shows\.21cn\.com[/&:?=_]
.shtimg\.com/portal/201210/29/14342484gae6g2h4efo499\.swf
.shuaijiao\.com/statics/js/adv0\.js
.shuhe\.cc/ssi/
.shulihua\.net/js/gzlishi468google\.js
.shulihua\.net/js/gzlishigoogle\.js
.shulihua\.net/js/topcen\.js
.shulihua\.net/js/yegonggao\.js
.shulink\.com/js/pagetop5\.js
.shuobar\.cn/images/task/300x200wl\.swf
.simplecd\.me/static/js/adcpm\.js
.sina\.aicai\.com/pages/sina/foot/jczq\.shtml
.sina\.com\.cn/js/87/20140101/hongbao/
.sina\.com\.cn/js/loadAd\.js
.sina\.com\.cn/litong/
.sina\.com\.cn/rwei/hapi2014/64video_titu_logo_500x90\.gif
.sina\.com\.cn/tgy/pop_js/ad\.js
.sina\.com\.tw/game_data/adsbro_
.sina\.com/ads/
.sina\.com/assets/js/dart/
.sina\.com/rm/
.sinaimg\.cn/cj/dfz_ad/
.sinaimg\.cn/large/7044f931gw1ejiv61vggsg20qy0230xd\.gif
.sinaimg\.cn/large/710c121btw1ecexo6z2e2j20qe02ijrz\.jpg
.sinaimg\.cn/large/710c121btw1ecexp4p1d1j20qe02i74t\.jpg
.sinaimg\.cn/large/adde8400gw1ehkji88zq1j20tg01ot9j\.jpg
.sinaimg\.cn/large/d3a48243tw1e9ku3qboj1j207e02aq2y\.jpg
.sinaimg\.cn/mw690/7d1c8e96gw1ehjblxlj39j206y06ydgi\.jpg
.sinaimg\.cn/mw690/7e2fcc5btw1eddew6zhznj206y06ymxf\.jpg
.sinaimg\.cn/mw690/7e2fcc5btw1eeeexqfdyij20j602i0tg\.jpg
.sinaimg\.cn/mw690/a1916e89gw1dye4d6qvyaj\.jpg
.sinaimg\.cn/mw690/a1916e89gw1dye4d74zmij\.jpg
.sinaimg\.cn/mw690/a6a976a2gw1ee8phmumv5j20h802ijrp\.jpg
.sinaimg\.cn/mw690/a6a976a2gw1eh9ccuoljbg206y08ct91\.gif
.sinaimg\.cn/mw690/a6a976a2gw1ejevv4ja1xj207h02bjrg\.jpg
.sinaimg\.cn/mw690/a6a976a2gw1ejj92lzu6fj207e02amxe\.jpg
.sinaimg\.cn/mw690/a6a976a2gw1ejx4rfzsftj20h801ymxb\.jpg
.sinaimg\.cn/mw690/a6a976a2gw1ejzj7vdc09j20h801yq3d\.jpg
.sinaimg\.cn/mw690/a6a976a2jw1ekate4cecig206y06ytge\.gif
.sinaimg\.cn/mw690/a6a976a2jw1ekate9l17gj207e02a0t0\.jpg
.sinaimg\.cn/mw690/a6a976a2jw1ekgvf39sxbg206y08cdh3\.gif
.sinaimg\.cn/mw690/a6a976a2jw1ekhni4zy9gj207e02aq36\.jpg
.sinaimg\.cn/mw690/a6a976a2jw1ekkao57e7xj207e02aaa6\.jpg
.sinaimg\.cn/mw690/a6a976a2tw1e2naxcbjyoj\.jpg
.sinaimg\.cn/mw690/ea495f08gw1egqwdf1h2mj208c04rt91\.jpg
.sinaimg\.cn/mw690/ea495f08gw1ehcsmx6dlzg20eq04gt9c\.gif
.sinaimg\.cn/unipro/
.sinajs\.cn/blog7style/images/activity/app_tuiguang/
.siqiboke\.com/upload/ad-
.siqiboke\.com/upload/winpop\.js
.siyu88\.cn/xl/xiaoke960_90\.gif
.sj\.net\.cn/img/hlw428\.gif
.sj\.net\.cn/img/yjy2014\.gif
.sjzbus\.com\.cn/advimg/
.sjzbus\.com\.cn/uploadimg/20130829114555\.gif
.sjzbus\.com\.cn/uploadimg/20130929080243\.gif
.sjzdaily\.com\.cn/sjznewsad/
.skdh1\.com/tp/
.slit\.cn/skin/slitsk/js/dlad\.js
.slit\.cn/slgg/
.slit\.cn/slimages/
.smzy\.com/newjava/.*970\.js
.smzy\.com/newtaip/smzy.*\.js
.so100\.cn/images/a.*\.js
.so100\.cn/images/newshead\.htm
.soaspx\.com/images/hws\.gif
.soaspx\.com/images/iiszj\.gif
.soft\.mumayi\.net/images/download\.gif
.soft\.mumayi\.net/js/
.soft711\.com/2013/
.softhy\.net/hp/
.sogou\.com/adpub/
.sogou\.com/images/app_1200X90\.jpg
.sogou\.com/skins/images/skinlist_ad\.
.sogoucdn\.com/app/a/100520113/20140812133958
.sogoucdn\.com/app/a/100520113/20140812172821
.sohu\.com\.cn/ppp/bms/bms\.popup\.
.sohu\.com/ssi/ad\.js
.soso\.com/baike/js/ad_
.source\.qunar\.com/site/images/wns/
.southmoney\.com/page/inc/
.southmoney\.com/page/top
.soxia\.cc/img/baoyue.*\.gif
.sp\.cc/html/click/dot\.gif
.spn\.com\.cn/admin_new/imgs/b2\.jpg
.spn\.com\.cn/media/jackmm\.js
.srzc\.com/images/.*\.swf
.srzc\.com/images/1\.jpg
.srzc\.com/images/2\.jpg
.srzc\.com/js/Adsjs/
.srzc\.com/templets/srxw/img/000ad\.jpg
.srzc\.com[/&:?=_].*/zwfjs/
.st\.vq\.ku6\.cn[/&:?=_]
.starbaby\.cc/201407/15/59a2614f61c358\.jpg
.starbaby\.cc/images/index/ikjt_words\.gif
.starnnews\.com/banner/
.static\.aizhan\.com/jsa/
.static\.colafile\.com/images/vip\.png
.static\.d\.lecai\.com/js/m\.js\?
.static\.doyouhike\.net/partner/
.static\.fzdm\.com/foot
.static\.fzdm\.com/ispop\.js
.static\.fzdm\.com/top
.static\.imanke\.com/imanke/m/
.static\.imanke\.com/imanke/pigbbs\.js
.static\.tianyaui\.com/gamify/broadcast/js/broadcast\.
.static\.tianyaui\.com[/&:?=_].*/stat_20080313\.js
.static\.wenxiu\.com/js/top\.js
.static\.zongheng\.com/upload/ad/
.static\.zongheng\.com/upload/hzds/
.static\.zongheng\.com/upload/zhds/
.static\.zongheng\.com[/&:?=_].*/index_r_b\.js
.stats\.chinaz\.com/tool/
.stcn\.com/common/flash/aigu\.swf
.stheadline\.com[/&:?=_].*/right_promo\.js
.stnn\.cc/images/xy/.*80px
.stnn\.cc/images/xy/yy\.swf
.stockstar\.com/.*DUILIAN&t=
.strtv\.cn/publicimg/sitelink/
.sub\.powerapple\.com[/&:?=_]
.subaonet\.com/templates/subaonet/images/index/2013/
.sufile\.com/jsa/
.suimeng\.com/js/html/yuedu
.suopao\.org/attachment/Fid_177/177_1_a0f2af20e450977\.gif
.super\.cat898\.com[/&:?=_]
.super\.kdnet\.net[/&:?=_]
.swf\.ws\.126\.net/house/201406161500\.swf
.sx566\.com[/&:?=_].*/zsz.*\.gif
.sxrom\.com/images/zz\.jpg
.sy\.ln\.cn/08gg/
.sygd\.tv/index\.php
.synacast\.com[/&:?=_]
.sz1001\.net/ab1/index.*\.js
.sz1001\.net[/&:?=_].*/soft_.*\.js
.sz5\.cn/template/comiis_kmsjx3hlx/ads/ad
.szhk\.com/565\.jpg
.szhk\.com/ads/
.t\.58xs\.com/hot/
.t56\.net/ad.*/
.taihainet\.com/biz/
.taihainet\.com/skin/v2014/index/images/aa_10\.jpg
.taihe\.net/js/ad
.taiwan\.cn/images/20140530_hxlt\.jpg
.taiwan\.cn/images/20140606_nxtshtzfww\.jpg
.taiwan\.cn/images/tw_ad_
.tanghui\.asia/xo/ttjs/top.*\.js
.taodake\.com/taodake_img/Images/union/
.taoguba\.com\.cn/js/tgbduilian
.taomato\.com/js/TP\.js
.tc\.cn/ad123/
.tc\.cn/g/dl\.ashx\?
.tc\.cn/g/upload/
.tc\.cn/news/images/h\.jpg
.tc\.cn/news/images/right\.jpg
.techorange\.com/wp-content/uploads/.*320x300
.techorange\.com/wp-content/uploads/.*600x100
.techweb\.com\.cn/static/images/lagou/lagougg\.jpg
.techweb\.com\.cn/static/images/liepin/
.tenitt\.info/03\.jpg
.tgbus\.com/sf/taobao/
.thethirdmedia\.com/a1/.*960x
.tianjinwe\.com/images/qssx/
.tianjinwe\.com/together/szbz/
.tianmu\.com/abbsd/
.tianmu\.com/js/qq\.js
.tianqi\.com/static/js/gg\.js
.tianshui\.com\.cn/newbg\.jpg
.tianshui\.com\.cn/newimages/xhglj\.swf
.tianshui\.com\.cn/Scripts/AC_
.tianshui\.com\.cn/xys\.swf
.tianshui\.com\.cn/yb\.html
.tiansin\.com/wp-adsense/
.tianya\.cn/images/ad950x90\.jpg
.tibet\.news\.cn/zhuye/images/wangqun
.tieba\.baidu\.com/f/urlcheck\?
.tieba\.lecai\.com/page/zhuanti/baidu/
.tietuku\.com/0bb9bfe57636dc55\.jpg
.tietuku\.com/8e81aa8e5298383e\.jpg
.tiexue\.net/domain-policy/
.tigtag\.com/images/pic1/
.timedg\.com/hfhtml/baiduad\.html\?
.tingchina\.com/js/.*220-
.tingchina\.com/js/760
.tingchina\.com/js/990
.tingchina\.com/js/allad\.js
.tingchina\.com/js/dp468
.tmcdn\.net/img/h000/h67/img201405211716540f9230\.jpg
.tntdown\.com/News/js/C_
.tom\.com/templets/tomwq/ad/
.tom365\.com/js/.*0
.tom365\.com/newjs/
.tom61\.com/style2012/gamead\.html
.tompda\.com/images/2014/800.*\.gif
.tompda\.com/static/soft/fav/fav_shop\.js
.tompda\.com/tupian/2013-03-15/300\.jpg
.tongxiang\.net/template/default/js/index/
.tongzhuo100\.com/img/jianzhi\.gif
.toowa\.com/Js/Inc_Foot\.js
.toptour\.cn/Portals/0/images/meilizhongguo\.swf
.totheglory\.im/pic/fangtuo\.jpg
.totheglory\.im/pic/ttg-
.totheglory\.im/pic/ttg_
.tt7z\.com/js/
.ttcy\.com/style/image/gg_
.ttcy\.com/style/indexImg/mengniu\.jpg
.ttdbh\.com/Scripts/defaultad\.js
.ttkdex\.com/ttkdweb/page/image/query
.ttrar\.com/js/
.tuan\.cs090\.com/gettuan\.php\?
.tucao\.cc/index\.php\?m=poster&
.tv380\.com/ovp/ovp_home/.*/adi/
.tvf4\.com/1/mugua\.js
.tvnmg\.com/banner/
.tw\.beanfun\.com/bfweb/NEW/commonlogin
.tw\.buy\.yahoo\.com/\?z=
.txahz\.com/static/image/tp/
.txooo\.com[/&:?=_].*/ydl\.jpg
.txooo\.com[/&:?=_].*/zdl\.jpg
.txt99\.cc/skin/script/.*\.js
.txtbbs\.com/data/txtbbs/
.txzqw\.com/js/float\.js
.ty121\.cn/IAA/
.tzfdc\.com/fdcSell/
.tzfdc\.com/Images/09/flv/flv_index\.js
.u\.riju\.com/click\.php
.u8xs\.com/js/box_
.u8xs\.com/js/tj\.js
.u8xs\.com/js/yuedu_
.uc8\.cc/_style/2013/js/all\.js
.ucbug\.com/js/left\.js
.ucbug\.com/templets/default/js/sharp\.js
.udn\.com/adpinline/
.udn\.com/excluded/
.udn\.com/SSI/neckFrameFlash.*\.htm
.udn\.com[/&:?=_].*/ad/
.union\.china\.com\.cn[/&:?=_]
.unionjs\.dianxin\.com[/&:?=_]
.untitled\.dwstatic\.com[/&:?=_]
.up\.hiao\.com[/&:?=_]
.upaiyun\.com/css88/.*/250-250\.jpg
.upaiyun\.com/css88/.*/680-100\.jpg
.upaiyun\.com/image/ad_ina/
.upaiyun\.com/statics/images/ad_
.upan\.cc/images/pay/
.upan\.so/images/bcbjAD\.jpg
.upan\.so/templates/default/images/sir\.gif
.upantool\.com/playing/
.upload\.northnews\.cn/2013/0826/1377507162798\.jpg
.upload\.northnews\.cn/2013/1028/1382943429869\.jpg
.uploadhouse\.com/fileuploads/16891/.*\.gif
.uploadhouse\.com/fileuploads/16920/.*\.jpg
.usa\.bytravel\.cn/images/cus/
.uutv5\.com/xz\.gif
.uutv5\.com/zy/
.uuu9\.com/news/css/news_content_in\.js
.uuu9\.com/stat/shouye/
.uzzf\.com/js/down_
.uzzf\.com/js/top_970\.js
.v-56\.com[/&:?=_]
.v\.huanqiu\.com/tres/xml/vda\.xml
.v1\.freep\.cn/3tb_140318090733pgee512293\.png
.v2ex\.com/assets/sidebar/
.v7v3\.com/images/lxhost\.png
.vanpeople\.com/adrotate2\.php
.vanpeople\.com/images_site/adb/
.vas\.funshion\.com[/&:?=_]
.vdisk\.cn/img/dcr2\.gif
.vdisk\.cn/img/yzm-zuowening\.gif
.veryhuo\.com/plus/js/
.video\.sdo\.com/index\.php\?m=poster&c=index&a=show_poster&id=
.videospeedy\.com/Res/images/wuy0u\.jpg
.vikilife\.com/huaban\.jpg
.vip\.luanren\.com/data/.*\.swf
.vipcn\.com/hezuo/
.vista\.ptbus\.com/s\.js
.vista\.tgbus\.com/data\.ashx[/&:?=_].*_SINGLE_SETJSONADSLOT
.vista\.tgbus\.com/s\.js
.vista\.tgbusdata\.cn/s\.js
.vmanhua\.com/new_v3/player/image/a_d_img/
.voc\.com\.cn/adsClick/
.voc\.com\.cn/Frame/qqms_cs\.html
.vupload\.duowan\.com[/&:?=_]
.vvic\.com/images/pi/.*\.jpg
.vvtor\.com/wordpress/wp-content/themes/NewsPro2/images/youbo\.gif
.vvvdj\.com/sms/
.w3cplus\.com/sites/default/files/banner
.w3cplus\.com/sites/default/files/lagou700-80\.jpg
.w3cplus\.com/sites/default/files/zhufen-js\.jpg
.wa\.kuwo\.cn/lyrics/img/kwgg/
.wacowla\.com/wp-content/plugins/codecanyon-.*-pullout-widgets-for-wordpress/
.wacowla\.com/wp-content/uploads/.*140x400
.wacowla\.com/wp-content/uploads/.*320x250
.wan\.sogou\.com/pop/
.wandoou\.com/heibing/js/640X60\.js
.wandoou\.com/heibing/js/wdgg\.js
.wangjing\.cn.*/upload/com/
.wangjing\.cn/images/js/YlFloat\.js
.wangjing\.cn/upload/ftp/ad/
.wangpanwu\.com/images/.*guanggao
.wangyueblog\.u\.qiniudn\.com/IMG_0978\.PNG
.wanwan\.sina\.com\.cn/third_party/
.wanyx\.com/js/bt\.js
.wanyx\.com/js/gg\.js
.wcxiaoshuo\.com/js/nrh\.js
.wd147\.com/templets/mm/js/cs\.js
.wdown\.cn/falala/
.we54\.com/54index_ad/
.we54\.com/poster/
.webacg\.com/data/js/
.webcars\.com\.cn/CarsPhoto/PictureHousePic/News/4/4/7/461947\.jpg
.webjx\.com/zanzhushang/
.webkaka\.com/script/duilian_
.weeiy\.com/wp-content/uploads/2013/12/2345ie\.jpg
.wehefei\.com/uploadfile/flashad/
.wei2008\.com/js/6\.html
.wei2008\.com/js/7\.html
.wei2008\.com/js/960X90
.wei2008\.com/js/down
.wei2008\.com/js/img
.wei2008\.com/js/index_
.wei2008\.com/js/list_gg\.js
.wei2008\.com/js/t_win
.weibo\.com/images/ad_
.weiqitv\.com/Uploads/185_440_
.weiqitv\.com/Uploads/20140721/53cca3becc50b\.jpg
.weixin\.qqday\.com/js/rb\.js
.weixin\.qqday\.com/js/tj\.js
.wendu\.cn/templates/wzdsb/js/yanue\.pop\.js
.wenyoutai\.com/template/comiis_x3wyt/ads/iad03\.jpg
.wfcmw\.cn/uploadfile/Article/.*\.swf
.whinfo\.net\.cn/ad20
.whnews\.cn/wh_public/dl/
.whnews\.cn/wh_public/xuxu/homegg/
.whqyw\.com/file/upload/201408/01/09-41-45-92-1\.jpg
.windows7en\.com/adsihai/banner\.js
.windows7en\.com/adsihai/ghost\.js
.wishdown\.com[/&:?=_].*/myad
.wlnews\.zjol\.com\.cn/bbs/
.wlnews\.zjol\.com\.cn/wlrb/bbs/
.wowody\.net/public/wowo/.*play_
.wowody\.net/public/wowo/2345\.html
.woxiu\.com/xapi/get_pre_config\.php
.woxiu\.com/xapi/offsite_swf_more\.php\?
.wp\.ylaop\.com[/&:?=_]
.wpdaxue\.com/2014/06/3h\.jpg
.wpdaxue\.com/2014/06/cef\.png
.wpdaxue\.com/2014/06/wx\.jpg
.wpdaxue\.com/2014/07/90zj\.png
.wpjam\.qiniudn\.com/wpjam/banner/.*g$
.wpmeeimg\.b0\.upaiyun\.com/2014/04/hczj\.jpg
.wpmeeimg\.b0\.upaiyun\.com/2014/08/ali0801\.jpg
.wszhibo\.com/Uploadfiles/.*\.gif
.wszhibo\.com/xml/tvAdtext\.ashx
.wuhan\.net\.cn/guanggaojs/
.wumii\.cn/site_images/c/
.wuxi\.cn/index\.php\?m=poster&
.wuyou\.com/0000/
.wuyougo\.info/03\.jpg
.wx\.56\.com/youxitg/
.wx\.sina\.com\.cn/iframe/pdps/
.wz\.zj\.cn/2014/0703/ty\.gif
.x-berry\.com/wordpress/wp-content/uploads/.*vpn
.x-berry\.com/wordpress/wp-content/uploads/2014/04/ad_nydus\.png
.x-berry\.com/wordpress/wp-content/uploads/2014/04/hidemyass\.gif
.x-berry\.com/wordpress/wp-content/uploads/2014/04/yinsuqidong\.gif
.xc\.macd\.cn[/&:?=_]
.xczhibo\.com/xml/
.xdcad\.net/source/plugin/disad/disad\.js
.xdf\.cn/v4/images/index/ads/
.xdf\.cn/v4/js/adm-
.xdf\.cn/v4/js/leyus/
.xdjz\.net/js/float\.js
.xdowns\.com/dd/
.xdowns\.com/g-g/
.xdowns\.com/ggco\.js
.xdowns\.com/info\.js
.xdowns\.com/js/lefttuijian\.js
.xemh\.com/other/.*_ads
.xgrb\.cn/bbs/js/float\.js
.xgrb\.cn/newad/
.xhub\.cn/cache/d125\.260\.gif
.xiaav\.cc/js/float\.js
.xiancn\.com[/&:?=_].*/adv_content/
.xiangai365\.com/ad_js/
.xiaolushu\.com/js/
.xiaoma\.com/xiaoma/www/images/nav/gre_max\.jpg
.xiazaiba\.com/uploadfiles/2013/1230/2014031213430294297\.gif
.xiazaiba\.com/uploadfiles/ads/
.xici\.net/d190282959\.3/3639080_2014_08_05_08_01_25_83c3b\.jpg
.xigua110\.com/a/
.xilu\.com/iframe/pagepic/
.xilu\.com/js/bd\.js
.xincheping\.com/Script/Ad/
.xinhuanet\.com/.*/ad20
.xinhuanet\.com/2013ad/
.xinhuanet\.com/2013images/jfzj\.swf
.xinhuanet\.com/2013images/ltxl\.gif
.xinhuanet\.com/2014/iframe/AD-
.xinhuanet\.com/2014/imgad/
.xinhuanet\.com/adxl/
.xinhuanet\.com/classad/
.xinhuanet\.com/images/ggdl\.jpg
.xinhuanet\.com/images2011/yt_csj\.gif
.xinhuanet\.com/images2013/yscy469X61dpi\.jpg
.xinhuanet\.com/imgs/hnmb0416\.jpg
.xinhuanet\.com/jjimages/jc/js/fla\.js
.xinhuanet\.com/jsstatics/2013/index/bayuan\.jpg
.xinhuanet\.com/newscenter/images/xhmb_top\.swf
.xinhuanet\.com/plugs/szzc630x80\.jpg
.xinhuanet\.com/static/img/2012/118114\.jpg
.xinhuanet\.com/sy/images/yidong4g\.jpg
.xinhuanet\.com/titlepic/111243292_title1n\.jpg
.xinhuanet\.com/v/script/coupletAd\.js
.xinhuanet\.com/v2/ads/
.xinhuanet\.com[/&:?=_].*/ad_
.xinji\.org/js/float\.js
.xinjs\.cn/2010/yf
.xinminweekly\.com\.cn/images/.*-banner
.xinminweekly\.com\.cn/images/index-985x93-
.xinyi\.com/Public/config/Couplet/Index100\.js
.xinyi\.com/Public/config/Couplet/Index39\.js
.xinyi\.com/Public/config/Couplet/Index40\.js
.xinyi\.com/Public/config/Couplet/Index41\.js
.xinyi\.com/Template/Ant/Js/tonglang\.js
.xitek\.com/idzone/
.xitong8\.com/theme/default/images/725x90\.gif
.xitong8\.com/theme/default/images/index_13\.jpg
.xitong8\.com/theme/default/images/udaxia
.xitongzhijia\.net/theme/default/images/725x90\.gif
.xitongzhijia\.net/theme/default/images/udaxia2\.gif
.xizhongzi\.net/bootstrap/dist/img/
.xizi\.com/a/20.*\?
.xizi\.com/js/rotator\.js
.xkhouse\.com/display/displaygg/
.xkhouse\.com/xkhouse/ggvert/
.xkxs\.org/js/bd
.xkxs\.org/js/tl
.xkxs\.org/js/tongji\.js
.xlpu\.cc/adv/
.xnimg\.cn/imgpro/home/a/niucuilai_
.xnnews\.com\.cn/images/smsline_double\.js
.xnnews\.com\.cn/images/yr_wsm\.js
.xnnews\.com\.cn/templets/image/.*gg
.xnnews\.com\.cn/templets/image/600zzj\.gif
.xp85\.com/statics/js/all\.js
.xp911\.com/img/xitong\.gif
.xpgod\.com/UploadPic/xpgod/
.xrba\.net/9kba
.xs\.houyi\.baofeng\.net[/&:?=_]
.xs8\.cn/xs8_stat\.js
.xsduo\.com/js/
.xsjie\.com/ads/
.xunleihao\.com/a-d-j-s/
.xunleihd\.com/image/maose
.xunzai\.com/static/wwwimg/
.xunzai\.com/www/all_common\.js
.xxdm\.com/js/union/
.xxs8\.com/data/attachment/forum/201308/02/154213bpecdb6qly7fgv71\.jpg
.xxsy\.net/js/xxsypop
.y2\.ifengimg\.com/1d124ac5e89463af/2013/0125/rdn_51023a5071d32\.jpg
.y2\.ifengimg\.com/6e0e559e19f25e8b/2013/1231/lj-dfnl-b\.swf
.y4dg\.com/source/plugin/wzkk_xshow/images/title\.js
.yam\.com/ad_yam/
.yanjiao\.com/zt/indexad/
.yanu\.qiniudn\.com/.*x60\.
.yaolan\.com/wenku_debris/time_debris/images/mary
.yaolanimage\.cn/cms/image/960-90
.yb983\.com/skin/yb983V2013/ad/
.ybbbs\.com/2013gg/
.ybvv\.com.*/aimg/
.ychr\.com/dlad\.js
.ychr\.com/swf/new0515netcom\.swf
.ydstatic\.com/fanxian/minisite/promotion/
.yehaolu\.com/js/jjss
.yeyou\.com/2013/new/yeyou-float-window\.js
.yimg\.com/.*/ysm/
.yimg\.com/ja/ap/.*/hk_rm_umu_
.yimg\.com/ja/ap/.*_wallpaper
.yimuhe\.com/n_ad/
.yinfuren\.com/ads/
.yinfuren\.com/config\.js
.yizhai\.net/myjs/f.*\.js
.yktj\.yzz\.cn[/&:?=_]
.ylnet\.com\.cn/201.*/rh/
.ylnet\.com\.cn/dl.*\.js
.ylnet\.com\.cn/gj\.js
.ylyl\.net/template/comiis_bato/ads/
.ylzx8\.cn/style/js/sad\.js
.you85\.cn/tao88/
.youth\.cn/templates/youth/edu/images/edu_atd\.jpg
.youth\.cn/templates/youth/edu/images/edu_xly\.gif
.youthwant\.com\.tw/dodo\.php\?adjs=
.youthwant\.com\.tw/images/mot_ad\.jpg
.youtu\.zjg\.js\.cn/data/js/
.youxi\.baidu\.com/tips/bdtips_min\.js
.youxiaxiazai\.com/db_top/index_top\.htm
.youxiaxiazai\.com/dm/
.ysxs8\.com/ysgg/
.ytbbs\.com/images/index/
.yto\.net\.cn:8022/Image/left_ad\.jpg
.yu64\.com/aajjss/
.yunaw\.com/content/templates/yunaw/images/2345banner
.yunfile\.com[/&:?=_].*/offline_banner/
.yxdown\.com/ghtml/
.yxlady\.com/cdd/
.yy521\.com/qq/qq\.js
.yytcdn\.com/others/avt/
.yytcdn\.com/user/bugles/.*_.*x.*\.jpg
.yytlw\.com/navigatoral\.js
.yzwb\.com/images/ad_
.yzwb\.com/js/AD
.yzwb\.com/js/ppaa\.js
.yzz\.cn/home/theme/popwin/
.zalra\.cn/wp-content/uploads/2014/05/adsj\.png
.zalra\.cn/wp-content/uploads/2014/05/xs009\.jpg
.zalra\.qiniudn\.com/zhou2\.jpg
.zalrad\.qiniudn\.com[/&:?=_]
.zaobao\.com/ssi/bizp/
.zasv\.com/somic\.gif
.zb7\.com/static/archy/ad/
.zbgl\.net/userfiles/image/20140724/24135631b2522827ef7101\.jpg
.zc173\.com/173fee/
.zc173\.com/pp/
.zdface\.com/Controls/ChannelHot/ChannelHotTypeID19ClassID0\.aspx
.zdface\.com/Controls/ChannelHot/ChannelHotTypeID8ClassID317\.aspx
.zfs\.cn/data/attachment/portal/
.zhangleisir\.qiniudn\.com/wp-content/uploads/.*/350_80\.
.zhangleisir\.qiniudn\.com/wp-content/uploads/.*250250
.zhao\.265g\.com/cache/kfbftop\.html
.zhaojiao\.net/templets/default/js/AD_flay\.js
.zhenjiang365\.cn/.*/ad_
.zhenjiang365\.cn/bbsatt/day_120827/1208271004af7c25b6e3d4fa1d\.gif
.zhenjiang365\.cn/bbsimg/lphyslideshower\.swf
.zhibo8\.cc/js/float\.js
.zhiboba\.cc/js/pic\.js
.zhibok8\.com/images/zhaozu
.zhibok8\.com/js/ding\.js
.zhibok8\.com/js/scroll\.js
.zhibowu\.com/js/ad
.zhoushan\.cn/new\.js
.zhuangpin\.com[/&:?=_].*/ad/
.zhuankeba\.net/rw/tyrw/top\.jpg
.zhuishu\.com/js/bd
.zhuishu\.com/js/fy
.zhulang\.com/ad_js/
.zhulong\.com/poster/get\?.*_960
.zhulong\.com/poster/get\?positions_name=ZY_JZ_300_02
.zhulong\.com/poster/get\?positions_name=ZY_SP_300
.zhyjw\.com/IAA/
.zhyjw\.com/xiala/
.zibosky\.com.*/adgl/
.zibosky\.com/images/gg11/
.zisai\.com/2013\.ad/
.zisai\.com/2014\.ad/
.zj\.com/bm_images/102975_1\.jpg
.zjbdt\.com/onexgadimgs/
.zjjzx\.cn.*/push/
.zjphoto\.yinsha\.com/special/
.zk168\.com\.cn/js/300gg\.js
.zk168\.com\.cn/js/b\.js
.zk168\.com\.cn/js/fwpd\.js
.zk168\.com\.cn/js/sy
.zo66\.com[/&:?=_]
.zol\.com\.cn/ajax/book2013/add_jindou_tips\.php
.zol\.com\.cn/intelcorp/
.zolsky\.com[/&:?=_].*ad/.*\.js
.zongheng\.com/zhuanti/2014/active/js/active\.js
.zsjjob\.com/user/member/google\.htm
.zsnews\.cn/Components/2013ZSNEWS/
.zsnews\.cn/fix_imgs/.*_300x80\.
.zsnews\.cn/JSFUN/AdvFun/
.zt\.iciba\.com/guess/images/900\.jpg
.zt2088\.com[/&:?=_]
.zuoche\.com/promo/.*\.jspx
.zvweapp\.com[/&:?=_]
.zxip\.com/2013_ad/
.zxxk\.com/js/articleinfo/JS_
.zymk\.cn/Public/editor/attached/20140819080822_33400\.jpg
.zyzczs\.com/js/tj\.txt
.zznews\.cn/home/js/duilian1\.js
.zzqhy\.com[/&:?=_].*/page/
.zzsky\.cn/images/zzskycom_
/att_count\.js
.a\.tbcdn\.cn/s/tb-tracer-min\.js
.acookie\..*\.gif\?
.acount\.pconline\.com\.cn[/&:?=_]
.adgeo\.163\.com[/&:?=_]
.analytics-union\.sandai\.net[/&:?=_]
.analytics-union\.xunlei\.com[/&:?=_]
.analytics\.tv189\.cn[/&:?=_]
.api\.pixnet\.tv/count[/&:?=_]
.brand\.sogou\.com[/&:?=_]
.bt\.ktxp\.com/iframe/statistics\.js
.ca\.cbsi\.com\.cn/rpv\?
.cdnlog\.zhenai\.com[/&:?=_]
.chinatimes\.com/analytics/
.click\.bokecc\.com[/&:?=_]
.click\.tianyaui\.com[/&:?=_]
.cloudfront\.net/atrk\.js
.count\.enet\.com\.cn[/&:?=_]
.counter\.pixplug\.in/count\.php
.countpage\.sznews\.com[/&:?=_]
.data\.xici\.net[/&:?=_]
.dq\.baidu\.com/nocipher\?
.dw\.xcar\.com\.cn[/&:?=_]
.error\.pixplug\.in[/&:?=_]
.frame\.enet\.com\.cn/a\.php
.gdt\.qq\.com[/&:?=_]
.hz\.youku\.com/red/
.icon\.zol-img\.com\.cn/mainpage/js/click\.js
.imedia\.bokecc\.com[/&:?=_]
.img\.kuai\.xunlei\.com/js/statistics\.js
.imp\.zol\.com\.cn[/&:?=_]
.isdspeed\.qq\.com[/&:?=_]
.itc\.cn[/&:?=_].*/tracker\.js
.js\.17173\.com/ping\.js
.kcart\.alipay\.com/web/bi\.do\?
.kkpgv2\.xunlei\.com[/&:?=_]
.l\.qq\.com/p\?
.l\.ykimg\.com[/&:?=_]
.log\.daqi\.com[/&:?=_]
.log\.mtime\.cn[/&:?=_]
.log\.vdisk\.cn[/&:?=_]
.log\.zongheng\.com[/&:?=_]
.login\.sdo\.com/sdo/PRes/js/sdo_beacon\.js
.msg\.ettoday\.net[/&:?=_]
.msg\.iqiyi\.com[/&:?=_]
.msn\.ynet\.com/c/stat/uv\.js
.msn\.ynet\.com/c/tj_comm\.js
.news\.baidu\.com/nocache/mp/b\.jpg
.news\.sina\.com\.cn/pvcounter/
.newspage\.xilu\.com/model/visitlog\.js
.play\.bokecc\.com/servlet/PlayVideo\?
.qq\.com/livemsg\?
.ranking\.ynet\.com[/&:?=_]
.record\.kuai\.xunlei\.com[/&:?=_]
.referer\.pixplug\.in[/&:?=_]
.rs\.sinajs\.cn[/&:?=_]
.s\.360\.cn[/&:?=_]
.s\.so\.360\.cn[/&:?=_]
.shrek\.6\.cn[/&:?=_]
.sogou\.com/js/pb_.*\.js
.sstat\.jd\.com/scslog\?
.stat\.2u\.com\.cn/ol_2u\.js
.stat\.baike\.com[/&:?=_]
.stat\.pchome\.net[/&:?=_]
.stat\.ws\.126\.net[/&:?=_]
.stat\.zol\.com\.cn[/&:?=_]
.static\.youku\.com/.*/index/js/iresearch\.js
.static\.youku\.com/.*/js/cps\.js
.static\.zongheng\.com[/&:?=_].*/ad_click\.js
.static\.zongheng\.com[/&:?=_].*/adClickStat\.js
.static\.zongheng\.com[/&:?=_].*/logger\.min\.js
.stats\.autohome\.com\.cn[/&:?=_]
.tajs\.qq\.com[/&:?=_]
.tcss\.qq\.com[/&:?=_]
.tf\.360\.cn[/&:?=_]
.tongji\.500wan\.com[/&:?=_]
.uuu9\.com/photolog\.html
.xls\.go\.sohu\.com[/&:?=_]
.youdao\.com/ctlog\?
.youdao\.com/tl\?
.zol\.com\.cn/cgimp/zc\.js
{ +filter{easylistchina} }
*
{ -block }
.union\.bokecc\.com/crossdomain\.xml
.union\.bokecc\.com/js/player/
.union\.bokecc\.com/servlet/GetUserInfo\?
.union\.bokecc\.com/servlet/playinfo\?
.l\.yimg\.com/f/a/tw/.*/790840_.*\.swf
.l\.yimg\.com/f/a/tw/elephant/.*240x94.*\.swf
,modules/adMedia\.
\.beautifulphoto\.net/ads/music
\.cntv\.cn/adplayer/
\.jstv\.com/c/gg/
\.s1979\.com/ad/ad.*\.mp4
/ad2\.js,
/qplayer\.swf\?.*&showAd=
/ttkdweb/page/js/ad\.js
^http:.*/gg/.*\.css
.100jia\.cn/template/veikei_dz_life_20130101_green/images/ad/ad_s_230_90\.jpg
.113\.com\.tw/www/image/index-ad\.png
.131js\.131\.com/home/resouces/js/index_20120420\.js
.17173\.com/x/flash800500\.js
.222pv\.com/js/A_names\.js
.33\.autohome\.com\.cn/njs/10055\.js
.33\.autohome\.com\.cn/njs/newget\.js
.3399\.com/DataTransfer/Advertisement/
.51hanhua\.com/2013/brtxt\.js
.52cons\.cn/data/attachment/.*_300_250_
.52zy\.com/gg/
.66u\.com/data/attachment/common/cf/
.75\.125\.41\.29:8080/.*/
.77119\.com/js/fenxiang\.js
.8591\.com\.tw[/&:?=_].*/buyAd\.css
.9588\.com/images/ad/
.a\.banggo\.com/Ad/getAdPosList\.shtml
.ad\.cw\.com\.tw[/&:?=_]
.ad\.damai\.cn[/&:?=_]
.ad\.jz123\.cn[/&:?=_]
.ad\.ourgame\.com[/&:?=_]
.ad\.qyer\.com[/&:?=_]
.ad\.thsi\.cn/siteHome/44\.txt
.ad1\.nownews\.com/.*\.php\?ownerid=1355
.ad1\.nownews\.com/ads\.php\?ownerid=1294
.ad1\.nownews\.com/ads\.php\?ownerid=1321
.ad1\.nownews\.com/ads\.php\?ownerid=1322
.ad1\.nownews\.com/ads\.php\?ownerid=1323
.ad1\.nownews\.com/ads\.php\?ownerid=1324
.ad1\.nownews\.com/ads\.php\?ownerid=1325
.ad1\.nownews\.com/ads\.php\?ownerid=1331
.ad1\.nownews\.com/ads\.php\?ownerid=1332
.ad1\.nownews\.com/ads\.php\?ownerid=1333
.ad1\.nownews\.com/ads\.php\?ownerid=1334
.ad1\.nownews\.com/ads\.php\?ownerid=1335
.adcdn\.pingan\.com[/&:?=_]
.admin5\.com/hezuo/action/inner\.head\.logo\.js
.adobe\.com[/&:?=_].*/afr\?auid=
.ads\.i8\.com\.cn/hd/dzs/
.ads\.ribiaozi\.info[/&:?=_].*\.jpg
.advertise\.shijue\.cvidea\.cn[/&:?=_]
.ali213\.net/.*/pop\.js
.aoodoo\.feng\.com/view\.php\?what=zone:94&
.appbyme\.com/adclient/
.appbyme\.com[/&:?=_].*/Advertisement\.css
.aspjzy\.com/jsweb/js/hotsearch\.js
.astyle\.alicdn\.com/\?.*/advertisement\.
.bbs\.52waha\.com/data/attachment/common/ad/common_74_icon\.png
.bbs\.yantuchina\.com/gg/tmp/hong\.gif
.bbs\.ylyl\.net/AD/1227\.jpg
.bdstatic\.com/\?\?
.beanfun\.com/ADClient/
.biz\.gexing\.com/bottom_
.blimage\.com/picserver/ggpic/
.bloggerads\.net/apps/CSS/ba\.css\?
.bzfxw\.com/adfile/ad14\.htm
.bzfxw\.com/adfile/ad29\.htm
.bzfxw\.com/adfile/syycss\.js
.bzfxw\.com/adfile/xzhf3\.js
.c4d\.cn/ads/ads_
.cb\.baidu\.com/ecom\?di=106878&
.cb\.baidu\.com/ecom\?di=231790&
.cb\.baidu\.com/ecom\?di=373107&
.cb\.baidu\.com/ecom\?di=654997&
.cb\.baidu\.com/ecom\?di=891878&
.cb\.baidu\.com/ecom\?di=892769&
.cb\.baidu\.com/ecom\?di=893557&
.cb\.baidu\.com/ecom\?di=933918&
.cb\.baidu\.com/ecom\?di=98779&
.cctcw\.cn/advert/
.cctv\.com/js/cntv_Advertise\.js
.chinahr\.com/images/phpads/
.citysbs\.com[/&:?=_].*/swfupload/
.click\.union\.jd\.com[/&:?=_]
.cmbchina\.com/ads/
.cnr\.cn/gg/
.cntv\.cn[/&:?=_].*_ad\.js
.colafile\.com/js/ad_test\.js
.costco\.com\.tw/jsps/website/.*AD
.cq\.qq\.com/js/cody/.*scroll_ad\.js
.czsrc\.com/Adpic/
.damai\.cn[/&:?=_].*/TopAd/
.dianxinos\.com/advs/
.disney\.com\.tw/tv/global/swf/banner728x90\.swf
.do189\.com/zb_users/theme/duoyi/style/images/text_bg\.gif
.downbank\.cn/s1/yl\.js
.dw\.xcar\.com\.cn/analytics\.php
.ebiotrade\.com/jslibrary/js44\.js
.eden\.org\.tw.*/script/ad_banner/
.eden\.org\.tw/themes/liger/images/banner_
.feng\.com/aoodoo/.*logo\.png
.feng\.com/aoodoo/view\.php\?what=zone:93&
.forum\.51nb\.com/images/.*/
.fwxgx\.com[/&:?=_].*/floatad\.
.g\.163\.com/jr\?site=netease&affiliate=freemail
.game\.sina\.com\.tw/game_data/advertise/
.gamersky\.com[/&:?=_].*/dhgame_
.gpsdlm\.com/images/ad\.
.guancha\.cn/ad/m_
.haseemobile\.net/data/files/mall/advs/
.hh010\.com/static/js/adsbygoogle_ad_adview_pic_cpc_cpm_cpa_guanggao_gg\.js
.hkjc\.com/banners/
.i3\.sinaimg\.cn/video/deco/2013/0325/js/
.icbc\.com\.cn/icbc/include/AD_
.icbc\.com\.cn/ICBC_ADJS/
.img\.ybbbs\.com/2014/.*app
.indeep\.com\.tw/images/ad\.swf\?
.indeep\.com\.tw/Images/Upload/AdPic/
.indeep\.com\.tw[/&:?=_].*/Showad\.
.jj\.5ccc\.net/scripts/new/pagetop\.js
.jjjgame\.com/plus/ad_
.joy\.cn/service\.php\?.*&showad=
.juxiangyou\.com/advert/
.kocpc\.myweb\.hinet\.net/BANNER\.jpg
.laniqu\.com/static/ad/
.launcher\.lenovo\.com/launcher/data/attachment/common/cf/
.life\.tenpay\.com/res/ad/cellphone/js/down_for_app\.js
.linuxidc\.com/linuxfile/linux\.js
.m1905\.cn/utils/adloader\.js
.meizu\.com/fileserver/ad/img/
.minisite\.letv\.com/tuiguang/
.mnighthk\.net/template/.*/ad
.msn\.wrating\.com/a1\.js
.mymusic\.net\.tw/js/ad/index_1\.js
.naruto\.hk/ad/uy\.js
.new7574\.u\.qiniudn\.com[/&:?=_].*[/&:?=_]ad
.news\.u17i\.com/advert/
.omusic\.com\.tw/backend/uploadpic/adindex/
.ooomm\.com/ad/icon/
.ooomm\.com/ad/Whoyao_logo114\.png
.ouyaoxiazai\.com/shouyead\.js
.p\.tanx\.com/ex\?i=mm_12852562_1778064_
.p\.tanx\.com/ex\?i=mm_33231655_8000000_
.pcdvd\.com\.tw/advertisement\.js
.photo\.erji\.com/hifig\.jpg
.photo\.erji\.com/opera\.jpg
.photo\.erji\.com/srk\.png
.pic\.zol-img\.com\.cn/2009/pix_index\.swf
.playno1\.com[/&:?=_].*/common/cf/
.pos\.baidu\.com/ecom\?di=u1370837&.*Fdz%
.pos\.baidu\.com/ecom\?di=u1493974&
.ps123\.net/MyFile/toptxt\.js
.pub\.alimama\.com/common/adzone/
.qidian\.com/ploy/20.*\.swf
.qingcheng\.com[/&:?=_].*/ad
.qingdaoport\.net/adv/random\.jsp
.qq\.com/bossweb/jifen/
.qq\.com[/&:?=_].*\?ADTAG=
.qqread\.com/swf/qqread_rollpic\.swf
.rapoo\.cn/images/ad/
.re-vat\.com/advs/
.ref\.so/templates/ref/short_show/adview_
.regapi\.37\.com/api/p_register\.php\?login_account=
.sc\.jb51\.net/adimg/.*\.jpg
.selfimg\.com\.cn/\?\?
.sf-express\.com/\.galleries/advertisement/
.share\.dmhy\..*/generate-captcha\?
.shu008\.com/heibing/js/ad/style1\.js
.sina\.com\.cn/litong/zhitou/pic/close-
.sina\.com\.hk[/&:?=_].*_ads\.cgi
.sinaimg\.cn/ad/adimage/50x50_
.sinaimg\.cn/large/696b3be5jw1eiuo9zjz34g206e01yjra\.gif
.sinaimg\.cn[/&:?=_].*/deco/.*/sinaObj\.js
.snh48\.com/images/ad/
.stjscn\.s-msn\.com/portal/hp/2011/udctrack\.
.tansuo\.cntv\.cn[/&:?=_].*/tansuo_Advertise\.js
.taobao\.com/go/app/tmall/login-api\.php\?
.tenpay\.com/v2\.0/main/creditcard/portal_rpm_apply\.shtml
.tingbook\.com/images/ad/
.tmall\.com/go/.*/banner\.php
.tompda\.com/images/pix\.swf
.totheglory\.im/pic/ttg_logo\.png
.txt99\.cc/skin/script/login\.js
.ujinbi\.com/AD/
.ujinbi\.com/UpLoadFile/guanggao/
.union\.bokecc\.com/player\?
.union\.bokecc\.com/servlet/getvideofile\?
.unisharp\.com/images/ad\.jpg
.v\.rbc\.cn/ad/
.v1\.cn/player/cloud/cloud_player\.swf\?
.wowsai\.com/data/files/ad/
.woxiu\.com/xapi/offsite_swf_more\.php\?.*&type=
.xda\.cn/data/attachment/common/cf/
.xinhuanet\.com/2014/imgad/FS_2014weixin\.jpg
.xinhuanet\.com/static/rmedia/pv\.swf
.xunleihao\.com/a-d-j-s/a-d-7\.js
.ychr\.com/picad/
.yimg\.jp/combo\?.*/ad/
.youlea\.com/uppic/adpic/
.zhibowu\.com/ad2\.htm
{ -block +handle-as-image }
.hinet\.net/.*bien.*/
.poster\.weather\.com\.cn/p_files/base/
.ads\.yimg\.com/ja/a/
/adbanner/.*
^http:
.hd\.duba\.net/vip\.ijinshan\.com/repository/ad-images/
.houdask\.com/data/advertising/
.jinhongweiqi\.com/ad/update/
.sdc\.pingan\.com[/&:?=_]
.static\.hdslb\.com/ad-images/
