{ +block{easylistgermany} }
&werbemittel=
-werb_hori\.
-werb_vert\.
-werbebanner\.
\.at/ads/
\.at/werbung/
\.com/de/ad/
\.com/werbung_
\.de/ads/
\.de/ads\?
\.de/ads_
\.de/werb/
\.de/werbung/
\.net/werbung/
\.to/werbung/
/_werbung/.*
/ad-rahmen-
/ad/anzeige_
/banner125werbung\.
/banner_quartermedia\.
/banner_woomws\.
/bannerwerbung-
/bilder/ads/.*
/bilder/werbung_
/buchreklame\.
/cms/werbung/.*
/dateien/ads/.*
/defaultwerbung/.*
/ec_adalt\.
/ec_adalt/.*
/ec_adalt_
/econa-layer/.*
/eraffe_ad\.
/esel\.js
/fileupload/werbung/.*
/firstloadwerbung\.
/getwerbung\.
/gigaflat\.js
/grafik/ads/.*
/hier_werben\.
/image_werbung/.*
/images/_werb_
/images/werb/.*
/images/werb_
/images/werbung\.
/images/werbung/.*
/img/werbung/.*
/imgwerbung/.*
/includes/werbung/.*
/layer_werbg\.
/media/werbung/.*
/medien/werbung/.*
/mod/werbung/.*
/o2-layer\.
/partneradzwerk/.*
/pic/werbung/.*
/pic/werbung_
/sidebar_werbung/.*
/styles/.*/werbung/.*
/upload/werbung/.*
/usemax/.*
/werb\.gif
/werb\.php
/werbeanzeige/.*
/werbeanzeigen/.*
/werbebanner-
/werbebanner\.
/werbebanner2\.
/werbebanner_
/werbebannerneu/.*
/werbecenter/.*
/werbegrafiken/.*
/werbeimages/.*
/werbemanager2/.*
/werbemittel/.*
/werbemittel_
/werbenetz/.*
/werbepartner\.
/werbepartner/.*
/werbeplakat\.
/werbepopup/.*
/werbescript/.*
/werbeslider\.
/werbeteaser/.*
/werbetrenner_
/werbezonen/.*
/werbung\.gif
/Werbung/.*_banner_
/werbung/banner/.*
/werbung/banner_
/werbung160\.
/werbung5jw/.*
/werbung90\.
/werbung_.*\?
/werbung_banner\.
/werbung_banner1\.
/werbung_frame\.
/werbungheader\.
/werbunglongbanner1\.
/WerbungPlatzhalter/.*
/werbungsbilder/.*
/werbungsky\.
/werbungsr3\.
/wrbg\.js\?
_Banner_Werbung_
_bannerwerbung/
_oben_ad\.
_unten_ad\.
_werbe_layer\.
_werbebanner\.
_werbebanner/
_werbebanner_
_werbebreak\.
_werbepartner\.
_werbung\.php
_werbung\.pl
_Werbung260\.
_woz_banner_vote\.
.doubleclick\.net/adx/.*/extern_gmxnet/
.doubleclick\.net/adx/rtl2\.de/.*;sz=
.doubleclick\.net/pfadx/.*\.myspass\.de_de/
.1deluxe\.eu/banner/
.213\.133\.100\.18[/&:?=_].*&clicktag=
.abbuono\.de/images/banners/
.ad\.71i\.de[/&:?=_]
.ad\.bwise\.ch[/&:?=_]
.ad\.jaumo\.com[/&:?=_]
.adm24\.de[/&:?=_].*/resbanner/
.alfahosting\.org/forum/f_bild/ban-kopf-
.amateurpin\.com/puarea/
.anleger-fernsehen\.de/movadplugin\.swf
.apps\.bergzeit\.de/seo/bdyn\?pid=
.arktis24\.de/tradedoubler/
.assets\.oomz\.de[/&:?=_]
.avidnova\.com/grafik/banner
.backlinkseller\.de/gfx/banner/
.banner\.immowelt\.de[/&:?=_]
.baygel\.de/banner/
.bbwworld\.com/livebanner/
.bergfreunde-partner\.de/banner/
.bergzeit\.de/out/pictures/partner/image/
.bn\.gewinn24\.de[/&:?=_]
.bodyguardapotheke\.com[/&:?=_].*/banner/
.boxen1\.com[/&:?=_].*/jessica1\.jpg
.boxen1\.com[/&:?=_].*/luxus-villa-zu-verkaufen\.gif
.bumskontakte\.ch/banner/
.business-best-practice\.de/anzeigen/
.business-best-practice\.de/include/anzeigen_
.catsms\.de/images/banner/
.cdn\.kaisergames\.de/www\..*/images/wallpaper_
.cect-shop\.com/CMBannerCECT-SHOP\.gif
.clanplanet\.de/cp-leaderboard\.jpg
.crawler\.pearl\.de/pearl-crawler/banner\?
.databaseapplications\.org/banner_manager/
.ddl-moviez\.org/promo/
.ddl-search\.biz/bilder/banner/
.deinplan\.de/pharus-shop\.gif
.distributionz\.net/bstadt_banner1\.gif
.dubstep-beats\.de/images/banner/
.easy-reisen\.ch/easyreisenadds\.aspx\?
.ebby\.de[/&:?=_].*/sportwettentipp220-
.ebby\.es[/&:?=_].*/logoringside220\.gif
.eblogx\.com/amazon/
.ecostream\.tv[/&:?=_].*/sofadeals_sky\.
.enforcer-shop\.de/banner/
.fachverlagshop\.de[/&:?=_].*/pujs\.php
.faktenpedia\.de/layer-
.fandealer\.de[/&:?=_].*/promo/
.farm\.plista\.com/widgetdata\.php\?.*%22pictureads%22%7D
.fettverbrennen\.net/bilder/banner/
.firstload\.de/affiliate/
.flatrate-4all\.de[/&:?=_].*/adultfrendfind\.jpg
.flirttoday\.de/banner/
.forgif\.me/ads[/&:?=_]
.fs-location\.de/img/partner/
.g-stream\.in/js/sms\.js
.gan\.wavecdn\.net[/&:?=_]
.gay-thailand\.de[/&:?=_].*/gay-thailand468x60\.gif
.geschenkidee\.ch[/&:?=_].*/ad/
.gewinnspielnetzwerk\.de/layer\.php
.gold-super-markt\.de/affiliate/
.gutscheinstore\.com/fullsizebanner\.gif
.handyz\.de/spank\.php
.happyweekend-community\.com/banner/
.happywins\.com/images/banner/
.hd-load\.org/linkus/
.hd-vidz\.net/layers\.php
.heimatdeal\.de/banner/
.heisebanner\.geizhals\.at[/&:?=_]
.hmsat\.de/banner/
.icq-styler\.de/promo\.html
.idealo\.de/extern/IdealoWidget\.php\?
.idealo\.net/widget/
.ideecon\.com[/&:?=_].*/iphone4-ohne-vertrag-ratenkauf\.gif
.imgimg\.de/popit/
.iphoone\.de/images/banner/
.iphpbb3\.com/banner4_iframe\.html
.joyclub\.de/partner/aff/
.kart-club-trier\.de/images/banners/
.kfz-gutachter-service\.de/kfz\.jpg
.kgmx\.de/layer/
.kka\.agitos\.de[/&:?=_]
.kka\.idg\.de[/&:?=_]
.konsi-shop\.de/images/banner/
.konsolenshop24\.com/360hacks/
.lavire\.de/layer\.php
.linkbase\.in/banner\.png
.loadsieben\.org/banner/
.mafia-banner\.myftp\.org[/&:?=_]
.mafia-losebank\.de/bilder/banner
.mafia\.to/popup\.php
.media\.alphaload\.com[/&:?=_]
.moneyspecial\.de[/&:?=_].*/banner/
.monsterdealz\.de/script\.js
.motorrad-link\.de/shop/catalog_extern\.php
.movie-blog\.org[/&:?=_].*/layer2\.js
.mp3kingz\.org/img/banner_
.musica\.at/banner/
.n-romserver\.de/banner/
.natursubstanzen\.com/banner\.gif
.navisys\.de/download/banner-blitzer\.gif
.nexxcdn\.com/banner/
.npage\.de/banner/
.onlyfun\.to[/&:?=_].*/onlyfun-rectangle\.
.osnatel\.de/swf/osnatel_kampagne_
.ox\.comventure\.de[/&:?=_]
.partner\.dasoertliche-marketing\.de[/&:?=_]
.partner\.maxxim\.de[/&:?=_]
.partner\.simplytel\.de[/&:?=_]
.partner\.teufel\.de[/&:?=_]
.partners\.eatsmarter\.de[/&:?=_]
.partyfans\.de/145x300\.gif
.pass\.ch/wp-content/uploads/.*/PASS-Banner-
.pfoetchen-talk\.de/banner/
.phonepublisher\.com/banner\.do\?
.picception\.com/banner/
.pocket\.at/banner/herold300x250\.swf
.ponsline\.net/assets2/Banner_
.porndude\.com[/&:?=_].*/layer\.php\?
.pornsearch\.to/images/banner/
.powerdownload\.info/pd/
.premium-zone\.us/banner\.png
.promotion\.mmxlive\.com[/&:?=_]
.promotionmaterial\.betacash\.com[/&:?=_]
.pytalhost\.de/images/wpmhome\.gif
.rabattsparer\.de/banner234x60\.gif
.randyrun\.de/affil/
.rc-network\.eu/banner/
.rechemco\.com/media/mw_affiliate/
.red-stripe-beer\.de/arnold\.jpgbanner/
.relink\.us/js/landingpage\.js
.roemerforum\.com/banner/
.satshop24\.de/banner\.gif
.schmunzelseite\.de/layer/
.scooter-attack\.com/banner/
.server\.nitrado\.net/img\.nitrado/nitrado_minecraft1_
.shopfacer\.de/images/banner/
.shoutbox\.de/ad/
.shuuz\.de/banner/
.sims-3\.net/xbox\.jpg
.sky-abonnieren\.de/banner/
.sn-multimedia\.de/download/bannersn\.gif
.snapr\.to/images/banner-
.sorgenlos\.de[/&:?=_].*/banner/
.spielotheka\.de/layer\.js
.sprachenlernen24-download\.de/banner/
.suchebiete\.com/bilder/allgemein_kleinanzeigen\.png
.sunshine-space\.it/_raika_lana/
.sunshine-space\.it/banner/
.superwin\.de[/&:?=_].*/anzeige\.jpg
.tele\.net/shoppingbanner\.php\?
.tnm\.de/wa/ad\?
.trackfox\.com[/&:?=_]
.trackfox2\.com[/&:?=_]
.tuneup\.de[/&:?=_].*/affiliate/
.tuneyourscoot\.com/images/banner
.turbo-promo\.de/banners/
.turnschuh-lose\.de/img/banner/
.ui-portal\.de/uim/.*/promo/
.ui-portal\.de[/&:?=_].*/topper\.js
.unicef\.de/ueber-uns/bannercenter/\?
.vertical-n\.de/scripts/.*/mediumrect\.js
.vertical-n\.de/scripts/.*/sky\.js
.vertical-n\.de/scripts/.*/supb\.js
.verticalnetwork\.de/scripts/.*/mediumrect\.js
.verticalnetwork\.de/scripts/.*/sky\.js
.verticalnetwork\.de/scripts/.*/supb\.js
.vienna\.at/banner/
.waiwidgets-.*\.amazonaws\.com[/&:?=_]
.wallpaper-arena\.to/images/banner/
.watercool\.de/images/wc_banner_
.webguidez\.de/test/images/
.webme\.com/show\.php\?
.wichsfleck\.com/layer\.html
.widgets\.goldankauf123\.de[/&:?=_]
.widgets\.mywai\.de[/&:?=_]
.wm-space\.youero\.com[/&:?=_]
.woom\.ws/banner/
.world-pictures\.de/banner_
.world-pictures\.de/daks_banner\.jpg
.world-pictures\.de/logo_purelements\.jpg
.world-pictures\.de/logo_summit\.jpg
.world-pictures\.de/outdoorshop\.jpg
.world-pictures\.de[/&:?=_].*_150x150\.gif
.wundert\.at/banner/
.wurzelimperium\.de/banner/
.xobor\.miranus\.com[/&:?=_]
.xxx-4-free\.net/banner/
.xxxporn\.to/banner/
.zock4help\.de/banner/
/werbe-banner/.*
^http://lustich\.de/bilder/.*_.*-
.0nk\.de/banner/
.1000hp\.net/banner/
.193\.107\.16\.142/f\.php
.1jux\.net/js/1l\.js
.1jux\.net/js/4p\.js
.1jux\.net/js/4p2\.js
.1load\.bz/kwa\.php
.20min\.ch/werbung/
.2concert\.de/banner/
.2download\.de/js/jquery\.simplemodal\..*\.min\.js
.320k\.in/jscript/layer\.js
.360hacks\.de[/&:?=_].*/partner/
.3d-area\.in/out\.js
.3dl\.bz/Layer\.js
.4-seasons\.tv[/&:?=_].*/FsProducts\.swf
.4players\.de/4pl/wallpaper/
.4players\.de/javascript/4players/billiger\.de\.js
.4players\.de/sourcen/portal/4players/utraforce/
.5-jahres-wertung\.de/apd/online/5-jahres-wertung-dateien/image.*\.gif
.5-jahres-wertung\.de/apd/online/5-jahres-wertung-dateien/image.*\.jpg
.5-jahres-wertung\.de/cl/online/cl-dateien/image.*\.jpg
.5-jahres-wertung\.de/el/online/el-dateien/image.*\.jpg
.5-jahres-wertung\.de/forum/images/other/.*\.jpg
.5-jahres-wertung\.de/grafiken/logos/banner1und1shop2\.jpg
.6dl\.to/images/girl_x7\.png
.800gs\.de/images/tpa/duonix/
.90elf\.de[/&:?=_].*/buderus_banner_
.a\.nyx\.at[/&:?=_]
.aachener-zeitung\.de/zva/container/kalaydo/
.abakus-internet-marketing\.de/img/forum-800_120_
.abc-sms\.de/frame1\.php
.abg-net\.de/uploads/tx_macinabanners/
.abload\.de/deals/teaser\.php
.access-im-unternehmen\.de/fileadmin/php/layer\.js
.achtzehn99\.de/assets/banner/.*x526
.achtzehn99\.de/themes/hoffenheim/images/banner_
.ad-hoc-news\.de/js/jquery\.lightboxad\.js
.ad-hoc-news\.de/theme/classic/swf/billboard-
.ad-hoc-news\.de/theme/classic/swf/headbanner-
.ad\.dslr-forum\.de[/&:?=_]
.ad\.games\.ch[/&:?=_]
.ad\.main-netz\.de[/&:?=_]
.ad\.putenbrust\.net[/&:?=_]
.adbl\.spieletipps\.de[/&:?=_]
.addicted-sports\.com/fileadmin/banner/
.adn\.meinsol\.de[/&:?=_]
.adsm\.gameforge\.de[/&:?=_]
.aerger\.tv/images/03-1\.gif
.aerger\.tv/images/a\.gif
.aerger\.tv/images/b\.gif
.aerger\.tv/images/c\.gif
.aerger\.tv/images/d\.gif
.aerger\.tv/images/hl-banner\.gif
.aerger\.tv/images/pl_i_wer\.gif
.aerger\.tv/images/sch_de\.gif
.aerger\.tv/images/sozhius\.jpg
.aerger\.tv/images/wer\.gif
.affiliate-marketing\.de/media/banner/
.affiliate-marketing\.de/media/medienpartnerschaften/
.africa-live\.de/!banner/
.ajaxstatic\.ebook-hell\.to[/&:?=_]
.ak-kurier\.de/akkurier/www/images/headerhoehn\.gif
.ak-kurier\.de/akkurier/www/images/headerhoehn\.jpg
.ak-kurier\.de/akkurier/www/images/iphonerepa\.gif
.ak-kurier\.de/akkurier/www/pic/dbeyer_250_200\.swf
.ak-kurier\.de/akkurier/www/pic/indupamitte\.png
.ak-kurier\.de/akkurier/www/pic/tbechera13\.png
.ak-kurier\.de/akkurier/www/pic/toyotaadorfmitte\.gif
.akkuschlapp\.de/images/asuv_leaderboard\.jpg
.alatest\.de/banner/
.alatest\.de/banners\.php\?
.alkoblog\.de/wp-content/uploads/.*/banner_weisshaus_
.allesueberfilme\.de/img/nextbase_banner\.gif
.alpine-auskunft\.de/images/banners/
.altesrad\.net/phpBB3/images/banner/
.amadeal\.de/pics/240\.gif
.amateur-blog\.org[/&:?=_].*/rotator\.php
.amerika-forum\.de[/&:?=_].*/ebay_logo\.gif
.amerikanisch-kochen\.de/bilder/GlamFood_
.androidpit\.info/js/video/videoTakeOver\.js
.anime-loads\.org/images/c3on9\.jpg
.anisearch\.de/affi\.php\?
.anonstream\.com/pokerboni\.html
.anonstream\.com[/&:?=_].*/popup\.js
.anonstream\.com[/&:?=_].*/popup1\.js
.antag\.at/js/ov\.js\.php\?
.antag\.de/js/ov\.js\.php\?
.antenne-frankfurt\.de/tl_files/img/partner/
.anthrojob\.de/images/banners/
.anzeigen\.bei-uns\.de[/&:?=_]
.anzeiger-news\.com/portals/willowtree/
.apfelnews\.eu/banner/
.apfelnews\.eu/banner_ipoint_
.apfelnews\.eu/copytrans\.png
.apfelnews\.eu/ct-banner\.png
.apfelnews\.eu/ipad-special\.jpg
.apfelnews\.eu/iphone_300de\.jpg
.apfelnews\.eu/iphone_oben\.gif
.apfelnews\.eu/iphone_sidebar\.gif
.apfelnews\.eu/mein-deal\.png
.apotheke-adhoc\.de/banner/
.arbeitstage\.at/pub_
.arbeitstage\.de/pub_
.areamobile\.de/service/gads/
.argovia\.ch/promotion/
.artikelpedia\.com/js/.*-.*\.js$
.asv-hamm-westfalen\.de/images/stories/marketing/.*-Anzeigesimpli\.jpg
.asv-hamm-westfalen\.de/images/stories/marketing/.*-hauptsponsoren\.jpg
.ate\.spritmonitor\.de[/&:?=_]
.atelco\.de/ai/swf/banner200_
.ati-forum\.de/files/atinews/ais/
.atomload\.at/231554\.js
.atomload\.at/bolle\.js
.atomload\.at/google\.js
.atomload\.at/js/\.
.atomload\.at/js/alanal\.php
.atomload\.at/js/atom\.js
.atomload\.at/js/holz\.js
.atomload\.at/js/llll\.js
.atomload\.at/js/volume\.js
.atomload\.at/net\.js
.atomload\.at/ULpop\.
.atomload\.at/yahoo\.js
.atv\.at/adonly\?
.au-ja\.de/banner/
.audiovision\.de/assets/templates/av-template/cocoon/dateien/.*\.swf
.augsburger-allgemeine\.de/img/incoming/.*/xxl-DonDent\.jpg
.augsburger-allgemeine\.de/incoming/.*\.ece/binary/.*\.swf
.augsburger-allgemeine\.de[/&:?=_].*/Skyscraper-
.austrianaviation\.net/uploads/tx_macina/
.austriansoccerboard\.at/banner/
.austriansoccerboard\.at/public/banner/
.austriansoccerboard\.at/public/sponsoren/
.auto-bild\.de/js/rd/google\.js
.autobild\.de/js/rd/google\.js
.autofreies-lautertal\.de/images/banner/
.autoline-eu\.at/atlads/
.autoline-eu\.ch/atlads/
.autoline\.de/atlads/
.auxilium-online\.net/images/banner_
.awardfabrik\.de/images/banners/
.az\.com\.na/img/banner/
.b-stadt\.com/images/banner\.gif
.back2hack\.cc[/&:?=_].*/partner/
.badisches-tagblatt\.de/html/netcontentmedia/bilder/red-banner-
.badisches-tagblatt\.de/html/netcontentmedia/webimages/aldi-bt\.swf
.banner\.click-tt\.de[/&:?=_]
.barcoo\.com/images/barcoo/campaigns/banner_
.basicthinking\.de/ad/
.basische-produkte\.de/wp-content/themes/nature_wdl/images/banner_
.basiszinssatz\.info/banner/
.bastel-elfe\.de/banner/
.bastel-elfe\.de/images/banners/
.bastel-elfe\.de[/&:?=_].*/prell-online\.gif
.battlefield-3\.org/interstitial\.php
.baulexikon\.de/cgi-bin/banner\.cgi
.bayer04\.de/b04-deu/data/banner/
.bayer04\.de[/&:?=_].*/_md_banner1\.aspx
.bayer04\.de[/&:?=_].*/_md_banner2\.aspx
.bayern-hof\.de/res/bilder/banner/
.bayern-hof\.de/res/bilder/partner/
.bbc-coburg\.com/bbc-data/images/cw\.jpg
.bbc-coburg\.com/bbc-data/images/hundf\.jpg
.bbc-coburg\.com/bbc-data/images/np\.jpg
.bbc-coburg\.com/bbc-data/images/scl\.jpg
.bbszene-shop\.de/countdownbanner\.php
.bbszene\.de/ane/bbszene/iframe\.php
.bbszene\.de/images/banner/
.beamten-informationen\.de/media/banner/
.beihilferecht\.de/media/banner/
.beisammen\.de[/&:?=_].*/banner/
.benm\.at[/&:?=_].*/iphoneohnevertrag_banner_
.benzinpreis\.de/140_x_160\.gif
.benzinpreis\.de/gfx/rc_banner\.jpg
.benzinpreis\.de/zahn\.gif
.bestboyz\.de/wp-content/uploads/.*-300x600_
.bestboyz\.de/wp-content/uploads/.*/ggsim_banner_blog_
.bhc06\.de/images/brosedkb\.jpg
.bhc06\.de/images/sponsorenleiste\.jpg
.bielefelderblatt\.de/images/banners/
.bielertagblatt\.ch/wallpaper_
.bild\.de/fotos/cb-autohaus24-
.bildschirmarbeiter\.com/images/poster/
.bildwl\.mobile\.de[/&:?=_]
.bio-markt\.info/biomarkt/easyCMS/FileManager/Banner/
.bizipic\.de/images/gbcodes200\.jpg
.bizipic\.de/images/gross\.png
.blackbeats\.fm/defshopbanner\.swf
.blickpunkt-brandenburg\.de/typo3conf/ext/sbbanner/
.blockbusters\.cc/partner/
.blockfloete\.eu/media/images/banners/
.blog-xx\.net/pop-code\.js
.blogprojekt\.de/Bilder/bp/backlinkseller\.gif
.blogprojekt\.de/Bilder/Profi/bloggerjobs\.gif
.blogtotal\.de[/&:?=_].*/foxload_125x125\.jpg
.bltrainer\.de/banner/
.boerse-express\.com/images/kapsch_claim\.png
.boerse\.bz/clientscript/msgbox/jquery\.msgbox\.js
.boerse\.bz/images/bitly\.png
.boerse\.bz/images/comeonguys\.png
.boerse\.bz/images/empfehlung\.png
.boerse\.bz/images/flat-deutsch-1\.png
.boerse\.bz/images/forumlist\.png
.boerse\.bz/images/hidebanner\.png
.boerse\.bz/images/maindisplay\.png
.boerse\.bz/images/maindisplay3-nb\.png
.boerse\.bz/images/maindisplay3-noborder\.png
.boerse\.bz/images/maindisplay3\.png
.boerse\.bz/images/md3\.png
.boerse\.bz/images/newimg\.png
.boerse\.bz/images/share\.png
.boerse\.bz/images/shareoffer\.png
.boris-becker\.tv[/&:?=_].*/presenting/
.borussia\.de/fileadmin/templates/main/swf/banner_
.botfrei\.de/kmp/
.boxee-forum\.de/images/banners/
.boxen1\.com[/&:?=_].*/arena-boxpromotion-logo1\.jpg
.boxen1\.com[/&:?=_].*/felix_sturm_banner\.gif
.boxen1\.com[/&:?=_].*/felix_sturm_boxing\.jpg
.boxen1\.com[/&:?=_].*/ibf\.gif
.boxen1\.com[/&:?=_].*/ibo\.gif
.boxen1\.com[/&:?=_].*/jessica_banner\.gif
.boxen1\.com[/&:?=_].*/klitschko_banner\.gif
.boxen1\.com[/&:?=_].*/paffen_sport_logo\.jpg
.boxen1\.com[/&:?=_].*/sauerland_logo\.png
.boxen1\.com[/&:?=_].*/steinforth\.png
.boxen1\.com[/&:?=_].*/super_six\.jpg
.boxen1\.com[/&:?=_].*/wba\.jpg
.boxen1\.com[/&:?=_].*/wbc\.jpg
.boxen1\.com[/&:?=_].*/wbo\.jpg
.boxen1\.com[/&:?=_].*/wfc_logo220\.png
.boxen1\.com[/&:?=_].*/www\.ebby_\.de1_\.gif
.braunschweigheute\.de/platzierungen/
.brautinfo\.at/uploads/tx_macinabanners/
.bravo\.de/online/sponsoring-
.bravo\.de/sponsoring-
.brothersoft\.de/gg/back_ad\.js
.brothersoft\.de/gg/center_gg\.js
.brothersoft\.de/gg/g\.js
.brothersoft\.de/gg/kontera_com\.js
.brothersoft\.de/gg/soft_down\.js
.browsergames\.de/images/wallpaper/
.brustverein\.de/images/banner/
.buchhandel\.de/img/header/.*/adv_
.buchhandel\.de[/&:?=_].*/banners/
.buffed\.de[/&:?=_].*/body_bg_
.buffed\.de[/&:?=_].*/metaboli/
.bundesliga\.de[/&:?=_].*/banner/
.business-best-practice\.de/bilder/anzeigen/
.bvb\.de/var/ezdemo_site/storage/images/bvb\.de/banner/mobil09/
.bvb\.de/var/ezdemo_site/storage/images/bvb\.de/banner/schwarzgelbe-karte/
.bvb\.de/var/ezdemo_site/storage/images/bvb\.de/banner/sky/
.bvb\.de/var/ezdemo_site/storage/images/bvb\.de/banner/strom09-banner/
.campen\.de/images/misc/ebay_logo\.gif
.casecenter\.net[/&:?=_].*/werbung/
.casinowelt\.com/banner/
.cellesche-zeitung\.de[/&:?=_].*/banner/
.center\.tv/cms/fileadmin/site/flash/anzeigen/
.center\.tv[/&:?=_].*_pimpmyleasing\.jpg
.centertv\.de/upload/anzeigen/
.chillmo\.com/wp-content/uploads/.*/mariokart81\.jpg
.chillmo\.com/wp-content/uploads/.*/thelastofusremastered\.jpg
.chillmo\.com/wp-content/uploads/2014/05/watchdogs\.jpg
.chillmo\.com/wp-content/uploads/2014/05/wolfenstein\.jpg
.chilloutzone\.net/consume/
.chilloutzone\.net/invokers/sfuchs/
.chilloutzone\.net[/&:?=_].*/weedseed-banner\.jpg
.china\.ahk\.de/uploads/tx_bannermanagement/
.chip\.de/hphdas2/
.cine24\.tv/la\.php
.cine24\.tv/themes/default/banner/
.cine24\.tv/themes/default/images/hdstream\.jpg
.cine24\.tv/themes/default/images/joyetech_
.cine24\.tv[/&:?=_].*/rotator\.php
.cine4home\.de/images/banner_
.cine4home\.de/images/logos/banner_
.cine4home\.de/images/logos/mainlogos/swans%20banner%20ar150\.gif
.cine4home\.de/images/logos/wir-machen-3d-zum-erlebnisk\.jpg
.cine4home\.de/images/maeueskino_150x280_120705\.gif
.cine4home\.de/images/oppo-germany-150x280-static\.gif
.cine4home\.de/pics/aibanner_
.cine4home\.de/pics/banner_
.cine4home\.de/pics/heimkino_160x240\.gif
.cinebee\.org/_out\.js
.cinebee\.org/la\.js
.cinebee\.org[/&:?=_].*\.js$
.cinebee\.org[/&:?=_].*/rotator\.php
.cinecity\.at[/&:?=_].*/banner.*\.gif
.cinemotion-kino\.de/fileadmin/backgrounds/.*/background\.jpg
.cineprog\.de/images/banner/
.cinestar\.de/flash/sdkm_intro_video_mini\.swf
.cinestar\.de[/&:?=_].*/banner_
.clever-tanken\.de/images/.*_banner_
.clever-tanken\.de/images/banner_160x85px\.gif
.clever-tanken\.de/images/poicon\.gif
.clever-tanken\.de/tamoil/10-006_banner2neu\.swf
.click-learn\.de[/&:?=_].*/Junge_Fahrer_155x250\.swf
.click-learn\.de[/&:?=_].*_155x155\.swf
.click-learn\.de[/&:?=_].*_JungeFahrer_155x430\.swf
.climbing\.de/fileadmin/banner/
.clubtime\.fm/banner/
.cobuich\.de/avislogo\.jpg
.computer-bild\.de[/&:?=_].*/idealo/banner_
.computerbetrug\.de/uploads/pics/a2\.jpg
.computerhilfen\.de[/&:?=_].*/gt-banner-
.connect\.quoka\.de[/&:?=_]
.consol\.at/fileadmin/templates/images/bg_
.consol\.at/uploads/tx_consolmedia/.*_branding\.jpg
.coretime\.fm/banner/
.crawli\.net/com/
.crawli\.net/pr\.js
.crosswater-job-guide\.com/images/banner_
.crosswater-job-guide\.com/pics/.*_skyscraper_
.crosswater-job-guide\.com/pics/banner_
.crosswater-job-guide\.com/pics/logo_yourfirm_250\.gif
.crosswater-job-guide\.com[/&:?=_].*250x300\.swf
.crosswater-job-guide\.com[/&:?=_].*_skyscraper\.
.crypt\.to/layer/
.crypt\.to/tracker\.php\?action=showbanner&
.cryptload\.biz/lala\.php
.cryptload\.biz[/&:?=_].*/greybox/
.csr-news\.net/main/images/Banner_
.csr-news\.net/main/images/compamedia_600\.gif
.csr-news\.net/main/images/grundfos\.gif
.cybercity\.de/domains4sale/
.cylex\.de/images/cylex\.de/credit-report-banner-
.daf\.fm/templates/images/flatex_
.daf\.fm/templates/images/vitrade_
.dance-charts\.de/images/banners/
.dancecore\.fm/partner/
.das-bewegt-die-welt\.de/images/banners/
.dasbewegtdiewelt\.de/images/banners/
.dasfachblatt\.de/banner/
.dastelefonbuch\.de/mic_banner\.jsp
.dat\.de/fzgwerte/einladungslayer_dat_sommer_12_20sec\.swf
.data-travelers\.de[/&:?=_].*/blogwebspace1\.gif
.dataup\.to/data/iad/
.datei\.to/ban/
.daujones\.com/gifs/ban/
.dav-summit-club\.de/uploads/tx_extcategory/.*_200x600\.
.ddl-base\.ws/partners/
.ddl-board\.com[/&:?=_].*/usenet_banner\.png
.ddl-music\.org/images/och_logos/
.ddl-porn\.in/out\.js
.ddl-porn\.us/ad\.js
.ddl-porn\.us/ads\.js
.ddl-porn\.us/frontpics/
.ddl-porn\.us/layer/
.ddl-porn\.us/pop\.php
.ddl-porn\.us/trade\.js
.ddl-scene\.com/usenext\.php
.ddl-search\.biz/banner/
.ddl-warez\.in/\..*\.js\.\.php
.ddl-warez\.in/\..*\.js\.php
.ddl-warez\.in/\.affiliate_
.ddl-warez\.in/images/hoster/
.ddl-warez\.in/images/hoster_logos/
.ddl-warez\.in/images/hosterlogos/
.ddl-warez\.in/images/och_logos/
.ddl-warez\.in[/&:?=_].*_js\.js
.ddl-warez\.in[/&:?=_].*_popup\.js
.ddl-warez\.in[/&:?=_].*_ulpop\.
.deal-magazin\.com/dat/pix/estatepro\.gif
.deal-magazin\.com/dat/pix/expobike\.jpg
.deal-magazin\.com/dat/pix/immoscout\.gif
.deal-magazin\.com/dat/pix/kon\.gif
.deal-magazin\.com/dat/pix/voelkel\.gif
.deejayforum\.de[/&:?=_].*/ebay_logo\.gif
.delamar\.de/wp-content/themes/delamar_v4/iframes/
.deluxetelevision\.com/img/banner/
.deluxetelevision\.com[/&:?=_].*/dsp_bannerrotator\.php
.deluxetools\.net/dlx_out\.js
.deraktionaer\.de/upload/Marktberichte-Aktionaer_15401\.gif
.deraktionaer\.de/xist4c/web/aktionaer/02/img/flatexBuySellBar/icons_all\.png
.derkleinegarten\.de/images/banners/
.derlacher\.de/static/lib/dialog/jquery\.reveal\.js
.deukom\.co\.za/banner/
.deutsche-versicherungsboerse\.de/imgdisp/.*Banner%
.deutscher-hip-hop\.com/bilder/werbepartnerlogos/
.deutschland\.fm/i/ducksunited120x60deutsch\.gif
.dexgo\.com/sponsoren/banner/
.dforum\.net/banner/
.dforum\.net/ebay/
.dforum\.net[/&:?=_].*/df_blitzbuch\.gif
.didaktik-der-mathematik\.de/tibanner\.swf
.die-beihilfe\.de/media/banner/
.die-eulen\.de/img/index/boxes/lotto_rlp\.jpg
.die-eulen\.de/img/intro/freiberger\.png
.die-eulen\.de/img/intro/sparkasse\.png
.die-eulen\.de/img/intro/suedzucker\.png
.die-eulen\.de/img/intro/twl\.png
.dieantenne\.it/images/logo_sparkasse\.gif
.dieantenne\.it/images/wer_
.diebrennstoffzelle\.de/images/banner/
.dieharke\.de/Partner/
.dieneue1077\.de[/&:?=_].*/wellness-deal_
.dieschmids\.at/images/banners/
.dieweinstrasse\.bz/uploads/tx_lemonadvancedflash/
.digital-eliteboard\.com/banner/
.digital-eliteboard\.com/images/banner-
.digital-kingdom\.dk/banner/
.din-5008-richtlinien\.de/bilder/anzeigen/banner/
.direct-city\.org/out\.js
.directupload\.net/graphics/anzeige_
.dloads\.org/usenext\.php
.dmax\.de[/&:?=_].*/anzeige\.gif
.dokujunkies\.org/media/md/
.dokujunkies\.org/media/prj/
.dokumente-online\.com/amazon_adv\.php
.dokus\.to/c/t\.js
.dokus4\.me/cgde\.js
.dokus4\.me/handyz_rss_\.php
.dokus4\.me/interstitial\.js
.dokus4\.me/kpopcg2012n2\.js
.dokus4\.me/w-v2\.php
.dokustream\.org[/&:?=_].*/banner/
.dooyoo\.de[/&:?=_].*/pp_anzeige\.gif
.dooyoo\.de[/&:?=_].*_skyscraper.*\.php
.doppelagent\.de/banner2\.php
.doppelpunkt\.de[/&:?=_].*/fullsizebanner\.html
.doppelpunkt\.de[/&:?=_].*/fullsizebanner2\.html
.doppelpunkt\.de[/&:?=_].*/halfsizebanner\.html
.doppelpunkt\.de[/&:?=_].*/halfsizebanner2\.html
.dotnet-forum\.de/photos/banner/images/
.dotnet-snippets\.de/dns/bilder/banner/
.dotnetpro\.de/grafix/banners/
.dotnetpro\.de[/&:?=_].*/anzeigeh\.gif
.dotnetpro\.de[/&:?=_].*/anzeigev\.gif
.dragondesigns\.de/include/images/sponsor/
.dreambox\.info/banner/
.dreambox\.info/d4d468\.gif
.dreambox\.info/euro_desaster_banner_2011\.gif
.dreambox\.info/satboerse24banner\.gif
.drehscheibe-foren\.de/dso_header/banner\.jpg
.drehscheibe-online\.de/ds_cms/banner/
.drehscheibe-online\.de[/&:?=_].*/anzeige\.gif
.drwindows\.de/images/ie9_sicherheit\.gif
.drwindows\.de[/&:?=_].*/crostec_banner\.jpg
.dsl-forum\.de/images/aktion/
.dslr-forum\.de/banner\.
.dsv\.de/images/banners/
.dtj-online\.de/content/banners/
.duckcrypt\.info/serv/
.dumdi\.net[/&:?=_].*/layer\.php
.durchfallhausmittel\.net/wp-content/uploads/.*/banner\.gif
.dxtv\.de/2spnsrs/
.e-va\.com[/&:?=_].*/skyscraper/
.e110\.de/images/abus_
.e110\.de/images/leaderboard/
.e110\.de/images/skyscraper/
.e110\.de/kaspersky/
.easy-scripts\.de/wp-content/themes/arras/images/250x250_
.easywarez\.biz/layer/
.ebase\.to/layer/
.ebby\.de[/&:?=_].*/boxen1_com_klein-220\.gif
.ebby\.de[/&:?=_].*/boxsport1\.gif
.ebby\.es[/&:?=_].*/wfc_logo220\.png
.ebook-hell\.me/popdown\.js
.ebook-hell\.to/google/
.ebook-hell\.to/js/bk2\.js
.ebook-hell\.to/js/ebook\.js
.ebook-hell\.to/js/ebooktip\.js
.ebook-hell\.to/js/mediamarkt\.js
.ebook-hell\.to/js/ranger\.js
.ebook-hell\.to/js/tooltip\.js
.ebook-hell\.to/js/tooltips\.js
.ebook-hell\.to/js/ulnet\.
.ebook-hell\.to/js/ULpop\.
.ebook-hell\.to/js/zk\.js
.ebook-hell\.to/js/zk1\.js
.ebook-hell\.to/popdown\.js
.ebook-hell\.to/toppop\.js
.ecdl-moodle\.de[/&:?=_].*/script_banner_
.econo\.de/uploads/tx_macinabanners/
.ednetz\.de/aktionen/banner\.html
.edvinfos\.de/banner/
.egofm\.de[/&:?=_].*banner
.egomera\.de[/&:?=_].*/bads/
.egun\.de/market/images/banner/
.eierkraulen\.net/dsfgsdf\.js
.eierkraulen\.net/img/blu\.gif
.eierkraulen\.net/js/gdsfgsdf\.js
.eierkraulen\.net/js/igdsfgsdf\.js
.eierkraulen\.net/js/ztigdsfgsdf\.js
.eierkraulen\.net/nmban\.gif
.einkaufaktuell\.de/data/page/NIVEASoftHauptbuehne954x240\.jpg
.einrichtungsbeispiele\.de/images_site/footer\.jpg
.eintracht-hildesheim\.de/Banner_Neu/Zufallsbanner\.html
.eintracht\.com/fileadmin/templates/html/images/seat-logo\.png
.eintracht\.de/media/banner/big_banner\.jpg
.eisbaeren\.de[/&:?=_].*/arentour_o2worldberlin\.jpg
.eisenbahn-kurier\.de/images/banners/
.eishockey\.info/banner/
.eiskaltmacher\.de[/&:?=_].*\.swf
.ekz\.de/resources/images/banner/
.eliteanimes\.com/images/elsheader\.jpg
.eliteanimes\.com/images/elsleft\.jpg
.eliteanimes\.com/images/elswordheader\.jpg
.eliteanimes\.com/images/elswordleft\.jpg
.eliteanimes\.com/images/flyffright\.jpg
.eltee\.de/img/broker/
.eltern-zentrum\.de[/&:?=_].*/werbeblocker_abschalten\.jpg
.elternforen\.com/images/aad\.png
.elternforen\.com/limango\.gif
.ems-tv\.de/banner/
.englische-briefe\.de/images/maennergeschenke\.jpg
.enjoykitz\.tv/banner1\.png
.eot-clan\.net/images/banners/
.epicspeedload\.in/top/neu_b\.php
.epicspeedload\.in[/&:?=_].*/wgpopup\.js
.epochtimes\.de/js/businessad\.js
.erdbeerlounge\.de/addons/common/pics/coop/
.eselfilme\.com/werbung/
.eslgfx\.net/media/masters/esl_sitebranding_homefront\.jpg
.esportcup\.kicker\.de/iframe/index\.html
.etailment\.de/wp-content/uploads/.*/Barcamp1\.gif
.etailment\.de/wp-content/uploads/.*/etailment\.gif
.etailment\.de/wp-content/uploads/.*_250x700\.
.etcg\.de/images/sponsoren/
.etcg\.de/sponsor/
.etel-tuning\.de/img/300250-
.etel-tuning\.de/img/banner_vzappeal\.jpg
.europeonline-magazine\.eu/anzeigen/
.europeonline-magazine\.eu/anzeigen2/
.eviltrash\.to/banner3\.jpg
.evz\.ch/assets/banner/
.experten-interviews\.de/wp-content/uploads/.*/banner_timetoprint_
.explora\.ch/uploadfiles/banner/
.explora\.ch/uploadfiles/bannersky/
.express\.de/image/view/.*,data,lotto_sommer\.gif
.ext\.platinnetz\.de[/&:?=_]
.fahrzeuglackiererforum\.de/layer\.js
.fail\.to/deadok\.php
.fail\.to/deal\.php
.fail\.to/failto\.php
.fail\.to/images/dokus_banner\.jpg
.fail4fun\.de/layerloop/
.fake-it\.biz/lla2/
.fake-it\.biz[/&:?=_].*/layer\.php
.falk\.de/fr/aservice\.php\?
.falk\.de/fr/bn\.php\?
.familytv\.de/design/11899\.gif
.familytv\.de/images/sonnenklar\.jpg
.familytv\.de/images/visitx-banner\.jpg
.famousfm\.de/images/partner/
.farmarbeit\.de/uploads/images/taxback-rec\.jpg
.farmarbeit\.de/uploads/images/wt_kanda10_
.faz\.net/f6/ad/
.fbsmiley\.de/tipp/moodrush\.gif
.fc-koeln\.de/fileadmin/img/banner/
.fcbayern\.telekom\.de/media/native/misc/banner/
.fcbayern\.telekom\.de[/&:?=_].*/385x66\.swf
.fcbayern\.telekom\.de[/&:?=_].*_385x66\.swf
.fck\.de/fileadmin/default/templates/gfx/banner/
.fcschweinfurt1905\.de/wp-content/uploads/.*_Skyscraper_
.fcz\.ch/_img/banner/
.fcz\.ch/_img/banner_
.feierabend\.de/gta/
.fernsehen\.to/js/notificationbar\.js
.fernsehserien\.de/gfx/anzeige\.gif
.fettspielen\.de/de/banner/
.ffn\.de[/&:?=_].*/banner/banner_
.fhcdn\.net[/&:?=_].*/ebay_logo\.gif
.file-upload\.net[/&:?=_].*/popup\.js
.files\.putpat\.tv/putpat_player/.*/top_banner/
.filestore\.to/banner/
.filme2k\.net[/&:?=_].*/system\.js
.filmz\.de/h/la\.htm
.filmz\.de/h/r\.htm
.filmz\.de/h/s\.htm
.filmz\.de/h/u\.htm
.finanzen\.net/images/a_anzeige/
.finanzen\.net/images/b_euro_eurams/banner_wiki_eas\.png
.finanzen\.net/images/b_partner/
.finanzen\.net/swf/a_anzeige/
.finde-reitbeteiligung\.de/banner/
.finya\.de/ad/
.fischkopf\.de/image-content/wallpapers/
.flashmob\.de/modules/mod_beinvolved/images/wordpress\.png
.flirttoday\.de/popup_
.flugzeugbilder\.de/adria\.gif
.flugzeugbilder\.de/schriftklein\.jpg
.fm-arena\.de/images/fm10/.*x128\.gif
.forendienst\.de/ad/
.forum-speditionen\.de/k-grafik/
.fr-online\.de[/&:?=_].*/teaserbox_300x160\.jpg
.fr-online\.de[/&:?=_].*_banner_fr_
.free-klingeltoene-handy\.de/images/bannertopbg\.jpg
.freecity\.de/www/anzeige\.gif
.freeload\.bz/out\.js
.freeload\.to[/&:?=_].*/lovedate\.gif
.freeload\.to[/&:?=_].*/lovedate160\.gif
.freizeitparks\.de/fileadmin/user_upload/banner/
.fremdwort\.de/images/banner_
.frischauf-gp\.de/fileadmin/images/banner-extern/
.fscklog\.typepad\.com/heise_mac\.gif
.fscklog\.typepad\.com/ms_imovie\.jpg
.fscklog\.typepad\.com/sz_kampagne\.gif
.fsv-frankfurt\.de/cms/fileadmin/templates/fsv/img/banner/sparhandy_banner\.jpg
.fuechse-berlin\.de[/&:?=_].*/anzeige\.gif
.full-ddl\.org[/&:?=_].*/out\.js
.fun80s\.fm/www/images/deinbanner\.gif
.fundanalyzer\.de[/&:?=_].*/laufband\.js
.fundanalyzer\.de[/&:?=_].*_banner\.swf
.fundresearch\.de[/&:?=_].*/laufband\.js
.fundresearch\.de[/&:?=_].*_banner\.swf
.funkbasis\.de/images/ban-
.funlinx\.to/images/linktipps_aktuell\.jpg
.funnybilder\.net[/&:?=_].*/dug_layer\.js
.funnypizza\.de/swf/pizzadebanner\.swf
.funnypizza\.upjersnet\.de/upad/
.fussballn\.de/images/banners/
.fussbodenbau-forum\.com/_images/banner/
.g-stream\.in/img/covers/752927162\.jpg
.g-stream\.in/lla2/
.g-stream\.in/mirror/
.g-stream\.in/zoomtube/buttons/.*\.jpg$
.g-stream\.in[/&:?=_].*/pfull2\.js
.g4u\.me/images/partners/
.g4u\.me/js/dug_layer\.js
.game-freaks\.net/popup\.php
.gamecaptain\.de/css/gc_branding_
.gamefox\.de/design/bannershaiya_
.gamefront\.de/am-zombiu\.jpg
.gamefront\.de/banners/
.gamefront\.de/f2play-
.gamefront\.de/gamecompany-170912\.jpg
.gamefront\.de/gamedealer170113\.gif
.gamefront\.de/gameplan2\.gif
.gamefront\.de/gametrader150x250\.jpg
.gamefront\.de/kingpl.*\.gif
.gamefront\.de/my-game-deals150x300\.jpg
.gamefront\.de/online-spiele4me150x300\.jpg
.gamefront\.de[/&:?=_].*-160x200px_
.gamefront\.de[/&:?=_].*\.swf$
.gamekeyfinder\.de/img/rot/
.gamekeyfinder\.de/img/rotation/
.gamemovieportal\.ch/_banners/
.gameone\.de/images/icons/paysafe\.jpg
.gameone\.de/images/nokia/
.gameothek\.com[/&:?=_].*/wp-addpub/
.gamepro\.de[/&:?=_].*/ova\.swf
.gamers\.at/fileadmin/user_upload/website/brandings/
.gamers\.at/images/branding/
.gamers\.at/uploads/tx_consolmedia/.*_branding\.jpg
.gamers\.at/uploads/tx_consolmedia/.*_branding_
.gamers\.at/uploads/tx_consolmedia/.*_sitebranding_
.gamers\.at/uploads/tx_consolmedia/bg_.*\.jpg
.gamers\.at/uploads/tx_consolmedia/branding_
.gamersglobal\.de/b\.js
.gamersglobal\.de/GAMERS-ps4-exp_v2_statisch\.jpg
.gamersplus\.de/fileadmin/user_upload/website/brandings/
.gamersplus\.de/images/branding/
.gamersplus\.de/uploads/tx_consolmedia/bg_.*\.jpg
.games\.ch[/&:?=_].*/banner/
.gamestar\.de/_misc/countdown/
.gamestar\.de/img/gamestar/_misc/gcEventBtnPrmBg\.png
.gamestar\.de/img/gamestar/_misc/prm_logoheader_gs_
.gamestar\.de/img/gamestar/_misc/promotion/.*/amazon_button.*\.png
.gamestar\.de/promotion/promowidget/
.gamestar\.de[/&:?=_].*/ova\.swf
.gameswelt\.net/public/upload/fullexpbranding/
.gaming-insight\.de/images/amd-.*\.swf
.gaming-insight\.de/images/banners/
.gaming-insight\.de/images/sensei\.jpg
.gaming-insight\.de/images/steelseries-legendary\.jpg
.gamingxp\.com[/&:?=_].*/metacritic_reviews_games\.png
.gamingxp\.com[/&:?=_].*/wallpaper-
.gamingxp\.com[/&:?=_].*/wallpaper/
.gamona-images\.de/471277/cf9b98701d9a4221b994fe5e7bd32c87\.jpg
.gamona-images\.de/471284/3f71999f1544d168cbce0128572e0b5a\.jpg
.gamona\.de/assets/.*/fallback_
.gamona\.de/assets/.*_expandable\.jpg
.gamona\.de/assets/.*_interstitial_
.gamona\.de/assets/.*_sitebranding-
.gamona\.de/assets/.*_sitebranding_
.gamona\.de/zeugs/.*_300\.swf
.gamona\.de/zeugs/.*_728\.swf
.gamona\.de[/&:?=_].*/1d51490a42eb6b18422ad278e296b2db\.js
.gamona\.de[/&:?=_].*/9aa397ac7f3010335eb8d6138ad988fe\.js
.gamona\.de[/&:?=_].*/widesky\.swf
.gayfm\.de/banner/
.gayfm\.de/images/banner/
.gb-4you\.com/js/lad/
.gehaltsvergleich\.com/di\.html
.gehaltsvergleich\.com/di2\.html
.geizhals\.at[/&:?=_].*/ad/
.geizkragen\.de[/&:?=_].*/anzeige.*\.gif
.gelbeseiten\.de/yp/ppcHorzAction\.yp\?
.gelbeseiten\.de/yp/rechte_spalte\.yp\?
.gelbeseiten\.de[/&:?=_].*/marginale_advt\.yp
.gelbeseiten\.de[/&:?=_].*/regioframe\.yp
.gentleman-blog\.de[/&:?=_].*/banner\.jpg
.gentleman-blog\.de[/&:?=_].*/skyscraper\.swf
.gentleman-blog\.de[/&:?=_].*/superbanner\.swf
.gepostet\.com/templates/desktop/images/banner/
.gepostet\.com[/&:?=_].*/layer\.js
.germanscooterforum\.de/bannermanagement/
.geschenke\.de/banner/
.gesetzlichekrankenkassen\.de/banner_ext/
.gesichtskirmes\.net/deal\.php
.gesichtskirmes\.net/fire-popdown-gk\.js
.getgaming\.de/sites/all/themes/getgamingtheme/img/.*_bg\.jpg
.getgaming\.de/sites/all/themes/getgamingtheme/img/bg_.*\.jpg
.gewinnspiel-gewinner\.de/images/zu-verschenken\.gif
.glarus24\.ch/typo3conf/ext/juhuiinserate/scripts/inserate_ajax\.php
.gmx\.net/banner\?
.goastro\.de/popup_chat/
.goettgen\.de/g-a-s/www/images/
.gofeminin\.de/home4/skin/.*_.*/home\.css$
.golem\.de[/&:?=_].*_afc1\.js
.golem\.de[/&:?=_].*_afc2\.js
.golem\.de[/&:?=_].*_afc3\.js
.googlewatchblog\.de/apt\.png
.gooster\.at/js/ov\.js\.php\?
.gooster\.ch/js/ov\.js\.php\?
.gooster\.de/js/ov\.js\.php\?
.gotv\.at[/&:?=_].*_clicktag\.swf
.gratis-hoerspiele\.de/wp-content/uploads/.*/heias_
.grauzone\.us[/&:?=_].*/dropin\.js
.green\.ingame\.de[/&:?=_]
.grillratte\.de/wp-content/uploads/2011/12/1-und-1\.gif
.gronkh\.de/media/brandings/
.grosseleute\.de/banner
.grosseleute\.de/otto_.*\.gif
.gtavision\.com[/&:?=_].*/reklame_
.guenstiger\.de/a-d-s/
.guenstiger\.de/banner/
.guenstiger\.de/bilder/anzeige_
.guiders\.de/cms/landing/bonn-bike-shop-ii\.jpg
.gulli\.com/layout/partner/
.gulli\.com/media/partner/
.gulli\.com[/&:?=_].*/camao_ebay_
.gutefrage\.net/js/marketing\.js
.gutefrage\.net[/&:?=_].*/partner-tipp-
.gutefrage\.net[/&:?=_].*/premium_partner/
.gwars\.de/index\.php\?page=advertisingpage
.halle\.de/anzeigen/
.halleforum\.de/images/anzeige_
.hallo-verlag\.de/img/sky_.*\.swf
.hallo-verlag\.de/img/super_.*\.swf
.hamburg-pride\.de/fileadmin/banner/
.hamm\.biz/bannerBOX\.php
.hamm\.biz/bannerLB\.php
.hammonline\.de/bannerbox\.php
.hammonline\.de/bannerlb\.php
.hammstars\.de/bannerBOX\.php
.hammstars\.de/bannerLB\.php
.handball-neuhausen\.de/images/logos/sponsoren/slider/
.handelsblatt\.com/images/icon/anzeige_h\.gif
.handwerksblatt\.de/banner_scripte/
.handykino\.info/banner/
.hannover-allsports\.de/ast/home_files/luederslogo_cmyk\.png
.hannover-allsports\.de/ast/home_files/rs_logo\.png
.hannover-dragonboatraces\.de[/&:?=_].*/drachenbootshop\.jpg
.hannover-dragonboatraces\.de[/&:?=_].*/gessjacob\.jpg
.hannover-dragonboatraces\.de[/&:?=_].*/gilde\.gif
.hannover-dragonboatraces\.de[/&:?=_].*/logo_avi\.jpg
.hannover-dragonboatraces\.de[/&:?=_].*/logo_starlighte\.jpg
.hannover-dragonboatraces\.de[/&:?=_].*/sponsors/
.hannover-dragonboatraces\.de[/&:?=_].*/tui\.jpg
.hannover-zeitung\.net/images/banners/
.hannover96\.de/CDA/uploads/tx_templavoila/sponsor_
.hans-wurst\.de/images/empfehlung/
.hans-wurst\.net/wp-content/uploads/ama/
.happywins\.com/headbanner\.php
.hardbase\.fm/banner/
.hardcoremetal\.biz/vote\.php
.hardware-academy\.org/images/banners/
.hardware-experten\.de/images/banner/
.hardware-factory\.com/banner/
.hardware-factory\.com/images/banners/
.hardwaremax\.net/images/banners/
.hartgeld\.com/images/wb/
.hartgeld\.com[/&:?=_].*/hgb_
.haustechnikdialog\.de/banner/
.hc-aschersleben\.de/SponsorenBanner\.swf
.hc-empor\.de/images/content/sponsors/
.hc-erlangen\.de/fileadmin/user_upload/bundesliga/sponsoren/
.hcempor\.de/images/content/sponsors/
.hd-vidz\.net/layer\.php
.hd-vidz\.net/out\.js
.heddesheimblog\.de[/&:?=_].*/anzeige-
.heddesheimblog\.de[/&:?=_].*/bds-anzeige-
.heidoc\.net/amazon/
.heimspiel-online\.de/uploads/tx_macinabanners/
.heinertown\.de/anzeigen/
.heise\.de/icons/ho/seen_by_banner\.gif
.heldendesalltags\.net/rss/handyz_rss_\.php
.hertener-allgemeine\.de[/&:?=_].*/anzeigen/
.hg-saarlouis\.de/uploads/pics/swsls_vdsl_
.hifitest\.de/wb/.*_MediumRectangle
.hifitest\.de/wb/.*_Offerbox
.hifitest\.de/wb/.*_Skyscraper
.hifitest\.de/wb/.*_XXLBanner1_
.highspeed\.duckcrypt\.info[/&:?=_]
.hiking-blog\.de/wp-content/uploads/.*/Campz\.de-300x177\.jpg
.hildesheimer-allgemeine\.de/uploads/tx_macinabanners/
.hirnfick\.to/hf\.php
.hirnfick\.to/random\.php
.hitradio-rtl\.de/uploads/pics/.*_banner_
.hitradio-rtl\.de/uploads/pics/banner_
.hl-live\.de/aktuell/grafiken/banner/
.hochzeitsplaner\.de[/&:?=_].*_200x600\.
.hochzeitstage\.de[/&:?=_].*/200x600_
.hochzeitstage\.de[/&:?=_].*/728x90hochzeitsdrucksachen\.gif
.hoerbuch\.in/newlay/
.hoerbuch\.in/pop\.php
.hoerbuch\.in/rssmd\.php
.hoerbuch\.in/trackit\.html
.hoerbuch\.in/zn\.html
.hoerbuchfm\.de[/&:?=_].*/banner/
.hollywood-streams\.com/partner\.js
.holstein-kiel\.de/tl_files/banner/rectangle_
.holstein-kiel\.de/tl_files/banner/skyscraper_
.holstein-kiel\.de/tl_files/banner/wide_rectangle_
.homepage-anleitung\.de/wp-content/uploads/.*/sky2\.png
.homerj\.de/images/.*_1580x250\.
.homerj\.de/images/.*_300x550_
.homerj\.de/images/.*_wallpaper\.jpg
.homerj\.de/images/asuswp_rog-gserie_042013\.jpg
.homerj\.de/images/design/box_elbster_
.homerj\.de/images/design/box_eset_
.hopto\.org[/&:?=_].*/banner\.html
.hornoxe\.com/ddpd\.js
.hornoxe\.com/plp_
.hornoxe\.com/pup_plaer\.js
.horseweb\.de[/&:?=_].*/blink/
.hot-porn-ddl\.com/downloads\.html
.hot-porn-ddl\.com/gtrade\.js
.hot-warez\.org/trade\.php
.hot-warez\.org/vote\.js
.hotel-tip-thailand\.de/images/villa_rental_deals\.jpg
.hotel-tip-thailand\.de/images2/andaman_photography\.jpg
.hotel-tip-thailand\.de/images2/best_deal_hotels\.jpg
.hotel-tip-thailand\.de/layer_add\.js
.housetime\.fm/banner/
.hsc2000\.de/files/knoch-web-banner-hsc\.jpg
.hsc2000\.de/files/livestream_2014_oben\.png
.hsc2000\.de/files/livestream_2014_unten\.png
.hsg-pohlheim\.de/hsg/images/banner/sponsoren/
.hsg-wetzlar\.de/uploads/.*_banner_650x100\.
.hsg-wetzlar\.de/uploads/tx_templavoila/.*-Banner\.gif
.hsg-wetzlar\.de/uploads/tx_templavoila/.*_Anzeige_
.hsg-wetzlar\.de/uploads/tx_templavoila/Banner_Stadthalle\.jpg
.hsgnordhorn-lingen\.de/sites/all/themes/hsg/images/spons_top/
.hsvhandball\.com/fileadmin/user_upload/Banner/
.html-world\.de/anzeige\.gif
.html-world\.de/anzeige3\.gif
.htwk-leipzig\.de[/&:?=_].*/premium-partner/
.iamgamer\.de/uploads/tx_iagnewsandarticles/branding/
.iamgamer\.de/uploads/tx_iagnewsandarticles/brandings/
.ich-hab-gar-keine-homepage\.de/show/kh\.php
.ichspiele\.cc/assets/images/backgrounds/
.idealo\.de/banner/
.idowa\.de/banner/
.idowa\.de/dynamic/content/banner\.do\?
.idowa\.de[/&:?=_].*/banner_objekte/
.im1\.tv[/&:?=_].*/commercial/
.imagebanana\.com[/&:?=_].*/layer\.js
.images-amazon\.com/images/.*/marquee/
.images-amazon\.com/images/.*/marqueestatic/
.imgimg\.de/a-d\.php
.imgimg\.de/a-l\.php
.infantologie\.de/layer\.php
.infokrieg\.tv[/&:?=_].*/gold-de-125x125\.gif
.infokriegernews\.de[/&:?=_].*/180x200_
.infokriegernews\.de[/&:?=_].*/all_stern\.jpg
.infokriegernews\.de[/&:?=_].*/krivor180x225\.gif
.informatikboard\.ch/banner/
.inside-channels\.ch[/&:?=_].*&ad\.id=
.inside-it\.ch/.*&ad\.id=
.inside\.bz\.it/images/banners/
.insidegames\.ch/werbung/
.insidegames\.ch[/&:?=_].*_Insidegame_bkg\.jpg
.intimesrevier\.com/banner/
.iphoneblog\.de/wp-content/uploads/2012/04/datacell-iphoneblog\.png
.ircfaq\.de/banner/
.ishare\.to/images/banners/
.islam\.de/images/other/banner/
.israelnetz\.com/uploads/tx_templavoila/
.it-sa\.de/uploads/tx_macinabanners/
.itseccity\.de/banner/
.ix\.de/icons/ho/seen_by_banner\.gif
.jacktheripper\.de/images/banner/
.jam\.fm[/&:?=_].*/centgebote\.swf
.jam\.fm[/&:?=_].*/werbung/
.jappy\.de/i/ad/
.jappy\.tv/i/ad/
.jenatv\.de/adds_
.jjahnke\.net/pt_popupbox\.js
.journalist\.de/uploads/tx_macinabanners/
.joursouvres\.ch/pub_
.jungewelt\.de/bannerdeliver\.php\?
.justpay\.de/images/banners/
.juve\.de/wp-content/plugins/banner/
.k-foren\.de[/&:?=_].*/prestitial\.js
.ka-news\.de/storage/.*/techkanews/anzeigen/
.kabelbwforum\.de/images/kabelbw/
.kabeldeutschland\.de[/&:?=_].*/556x464chat-m\.gif
.kadett-forum\.de/gp\.swf
.karriere-im-ausland\.de/bilder/ef_banner_
.kartfahrer-forum\.de/board/images/banner/
.kaufn\.com/banner_test/
.ketoforum\.de/Banner/
.keywelt-board\.com/banner\.gif
.keywelt-board\.com/banner2\.gif
.kicker\.de[/&:?=_].*/anzeigevertikal\.jpg
.kielz\.de/uploads/partner/rotbanner-
.kilu\.de[/&:?=_].*/remote_changes\.
.kingsize-crew\.cc/banners/
.kino\.de/js/mvf2\.js
.kino\.de/landingpages/
.kinokiste\.com/assets/img/leaderboard_s\.gif
.kinokiste\.com[/&:?=_].*/sofadeals_sky\.
.kinoprogramm\.bild\.de[/&:?=_]
.klamm\.de[/&:?=_].*/wms_show_frame\.php
.kleinreport\.ch/uploads/banner/
.koelner-wochenspiegel\.de/images/banner/
.koelschwasser\.eu/images/banners/
.kondomgroesse\.com[/&:?=_].*/layer1\.js
.krankenkassentarife\.de/images/anzeige_
.kress\.de/typo3conf/ext/tmplkress/res/.*-banner\.js\?
.kress\.de/typo3conf/ext/tmplkress/res/.*_200x2400\.swf
.kress\.de/typo3conf/ext/tmplkress/res/.*_777x90\.swf
.kriminalpolizei\.de/images/lzw_banner\.gif
.krone\.at[/&:?=_].*/ad_stylesheet/
.kronehit\.at/assets/banner/
.kurier\.at[/&:?=_].*/dynamicads_
.laborjournal\.de/banner/
.lachfails\.net[/&:?=_].*/layer\.js
.lachfails\.net[/&:?=_].*/layer/
.lachschon\.de[/&:?=_].*/cutewood-promo\.jpg
.land-der-traeume\.de/bilder/banner/
.land-der-traeume\.de/partner/
.langenscheidt\.de[/&:?=_].*/banner/
.langes-forum\.de/images/banner/
.langes-forum\.de/js/bannerwechsel_header\.js
.laola1\.at/fileadmin/sp10/img/presentings/
.latina-press\.com/media/brasilianisch-lernen-180\.jpg
.layer\.lima-city\.de[/&:?=_]
.leecher\.to/123\.php
.leecher\.to/ad/
.leecher\.to/hrhrhrhr\.js
.leecher\.to/leecher\.js
.leecher\.to/leecher\.php
.leecher\.to/peter/
.lesben\.org/images/banners/
.lesen\.to/camp/
.lesen\.to/deal\.php
.lesen\.to/inslay\.php
.lesen\.to/lay\.php
.lesen\.to/layer/
.lesen\.to/pop\.php
.lesen\.to/trackit\.html
.lesen\.to/trackitenter\.html
.lesen\.to[/&:?=_].*/rotator\.php
.like-fun\.eu/images/bg4y\.jpg
.like-fun\.eu/include/layer\.js
.linguee\.de/banner/
.linkbase\.in/l\.js
.linkcrypt\.com[/&:?=_].*/mirror\.gif
.linkfarm\.in/linkfarm_out\.js
.lintorfer\.eu/wp-content/images/bauconcept\.jpg
.lintorfer\.eu/wp-content/images/bensberg2\.gif
.lintorfer\.eu/wp-content/images/bional\.jpg
.lintorfer\.eu/wp-content/images/boening\.gif
.lintorfer\.eu/wp-content/images/butenberg\.jpg
.lintorfer\.eu/wp-content/images/druckerei_preuss2\.gif
.lintorfer\.eu/wp-content/images/essbar\.jpg
.lintorfer\.eu/wp-content/images/fleermann10\.jpg
.lintorfer\.eu/wp-content/images/kroellgmbh\.gif
.lintorfer\.eu/wp-content/images/marbetinoa\.JPG
.lintorfer\.eu/wp-content/images/perpeet\.GIF
.lintorfer\.eu/wp-content/images/simons_klein\.JPG
.lintorfer\.eu/wp-content/images/Steingen2012\.jpg
.lintorfer\.eu/wp-content/images/Tus-Lintorf\.gif
.lintorfer\.eu/wp-content/images/victor\.jpg
.lintorfer\.eu/wp-content/uploads/.*/130620peterbeyer\.jpg
.lintorfer\.eu/wp-content/uploads/.*/131220peterbeyer\.jpg
.lintorfer\.eu/wp-content/uploads/.*/131221kr%C3%B6lln\.jpg
.lintorfer\.eu/wp-content/uploads/.*/20130322blumenkamp\.jpg
.lintorfer\.eu/wp-content/uploads/.*/assro-bahr\.jpg
.lintorfer\.eu/wp-content/uploads/.*/assro\.jpg
.lintorfer\.eu/wp-content/uploads/.*/awo-jan\.jpg
.lintorfer\.eu/wp-content/uploads/.*/bastelesel\.jpg
.lintorfer\.eu/wp-content/uploads/.*/Bauconcept_131113\.jpg
.lintorfer\.eu/wp-content/uploads/.*/bional\.jpg
.lintorfer\.eu/wp-content/uploads/.*/butenbergneu\.jpg
.lintorfer\.eu/wp-content/uploads/.*/fleermann_111213\.jpg
.lintorfer\.eu/wp-content/uploads/.*/Froschk%C3%B6nige\.png
.lintorfer\.eu/wp-content/uploads/.*/kr%C3%B6llneu21\.jpg
.lintorfer\.eu/wp-content/uploads/.*/lintorfer1\.png
.lintorfer\.eu/wp-content/uploads/.*/pflegeunion\.jpg
.lintorfer\.eu/wp-content/uploads/.*/steingen2013\.jpg
.linux-forum\.de/images/misc/ebay_logo\.gif
.live-stream\.tv/images/savetv\.gif
.loaderz\.org[/&:?=_].*/layer\.php
.lohn-info\.de/banner_meritum\.gif
.lokalanzeiger\.de/images/banner/
.lokalisten\.de/scripts/ox_spc\.js
.looki\.de/ba/
.looki\.de/gfx/cache/ba_.*\.png
.looki\.de[/&:?=_].*/take_over_
.lose-keller\.de/sk_views\.php
.lounge\.fm[/&:?=_].*_Anzeige_
.lowbird\.com/media/ichwuerde\.gif
.luebeck-tourismus\.de/images/stories/.*_154x70
.luebeck-tourismus\.de/images/stories/banners/
.lvz-online\.de/includes/flash_sachsendeal/
.maclife\.de/sites/all/modules/fm_imageslider/slider\.html
.macnews\.de[/&:?=_].*/musicstar-teaser\.gif
.maerkischeallgemeine\.de/widget_meinprospekt\.html
.mafia\.to/base\.php\?
.mafia\.to/dl_header\.cfm
.magistrix\.de/dblock/
.magistrix\.de/deblock/
.magistrix\.de/deeblock/
.mailgen\.biz/img/banner_
.mailgen\.biz/lla2/
.mainz05\.de/mainz05/banners\.html
.manabase\.de/images/topimg\.gif
.maniac\.de/sites/all/themes/maniac/images/campaigns/
.map24\.com/banner/
.marcus-klein\.de/EWR-Logo-web-1\.gif
.mb-treff\.de/menue/banner/
.mba-studium\.de/whb3\.gif
.mcload\.cc[/&:?=_].*/hs\.gif
.mcload\.to/images/lovedate\.gif
.mcload\.to/images/lovedate160\.gif
.md5checker\.com/ipodbanner\.gif
.mdh-pa\.net/trade_out\.js
.media\.onlinewelten\.com[/&:?=_]
.media33\.kanal8\.de/media/.*/banner/
.mediaforum\.ch/banner/
.mediaforum\.ch/banner_
.medienzensur\.de/bilder/links/unicef\.gif
.mega-stream\.to/do\.php
.mega-stream\.to/js/ppop.*\.js
.mega-stream\.to[/&:?=_].*/system\.js
.meintomtom\.de[/&:?=_].*/back_adblock\.gif
.meisterkuehler\.de/bilder/artikel/banner/
.mensa-kl\.de/banner/
.meproxsoft\.de[/&:?=_].*/banner-
.meran2000\.net/de/images/banner/
.mercateo\.com/delivery\.engine/
.messweb\.de/clickrate/
.miba\.de/bilder/banner/
.michas-spielmitmir\.de[/&:?=_].*/anzeige\.gif
.michas-spielmitmir\.de[/&:?=_].*/banner_
.mistershoplister\.de/mips\.php
.mittelbadische-presse\.tv/reiffvast/vast\.php
.mmnews\.de[/&:?=_].*/banner-mmnews_336x279px\.gif
.mmnews\.de[/&:?=_].*/bocker_gold\.gif
.mobiflip\.de[/&:?=_].*/160er\.html
.mobiflip\.de[/&:?=_].*/728er\.html
.mobilfunk-talk\.de/banner_rechts\.php
.moddingtech\.de[/&:?=_].*/banners/
.modified-shop\.org/images/banner/
.moneyspecial\.de/ms/media/sponsor/
.moonsault\.de/templates/
.morgenpost\.de/adv/
.morgenweb\.de[/&:?=_].*/banner/
.morgfx\.de/banner/
.motorsport-total\.com/i/dunlop_flash\.gif
.motorsport-xl\.de[/&:?=_].*/werbung/
.mototreff\.ch/Banner/
.mov-world\.net[/&:?=_].*/fidel\.js
.movie-blog\.org[/&:?=_].*/stargames\.js
.movie-blog\.org[/&:?=_].*/starlay\.js
.movie-stream\.to/do\.php
.movie-stream\.to[/&:?=_].*/pop.*\.js
.movie-stream\.to[/&:?=_].*/system\.js
.moviebb\.to/img/banner/
.moviebox\.to/do\.php
.moviebox\.to[/&:?=_].*/.*pop.*\.js
.moviebox\.to[/&:?=_].*/system\.js
.moz\.de/fileadmin/media/flash/online_banner_
.mr-wetter\.de/images/banners/
.msxfaq\.de/images/banner_
.msxfaq\.de/images/skyscraper\.gif
.msxfaq\.de/images/skyscraper_
.msxfaq\.net/images/banner_
.msxfaq\.net/images/skyscraper\.gif
.mt-online\.de/_em_daten/[/&:?=_].*_rectangle\.jpg
.mtb-news\.de[/&:?=_].*/anzeige\.gif
.muenchen\.de[/&:?=_].*/banner/
.muenzen\.net/banner/
.multilingual\.de[/&:?=_].*/banner/
.musiksampler\.de/images/banner/
.muskelschmiede\.de/forum/partner/
.muskelschmiede\.de/images/banners/
.mvv-muenchen\.de/web4archiv/objects/pictures/homepage/banner/
.myanimes\.net/layer\.js
.myconsol\.net/uploads/brandings/bg_
.myconsol\.net/uploads/brandings/headerbg_
.mycsharp\.de/wbb2/images/community_index/events/.*_140x100\.gif
.mydict\.com/images/w/
.myfile\.bz/out\.js
.myfunlink\.to/handyz_rss_\.php
.myfunlink\.to/psdealsrss\.php
.myfunlink\.to/viral/
.mygully\.com/daload\.php
.mygully\.com/popbit\.js
.mygully\.com/popup\.js
.mypolonia\.de/promo/
.n-romserver\.de/w-info\.gif
.n-tv\.de/img/.*_290_advogarant-
.nachrichten\.at/oonup/images/kunden/
.nachrichten\.it[/&:?=_].*/banner_
.nachrichtenamort\.de/cms/wp-content/images/ANZ_
.nachtkritik\.de/images/banners/
.namibia-forum\.ch/images/banners/
.nanu\.de/modules/wochenschau/banner/
.naturpark-augsburg\.de/img_layout/zech_partner\.jpg
.navi-forum\.net/navishop\.gif
.nerdcore\.de/banner/
.nerdcore\.de/wp/wp-content/themes/.*/_img/hosteurope\.gif
.netheweb\.de/images/a-
.netheweb\.de/images/trigami\.png
.network\.bildderfrau\.de[/&:?=_]
.network\.gofeminin\.de[/&:?=_]
.network2\.aufeminin\.com[/&:?=_]
.netzpolitik\.org/wp-upload/2012-07-10-tarent-2\.png
.netzwelt\.de/images/partner/
.netzwelt\.de/js/ads/
.netzwelt\.de[/&:?=_].*/driver_detection\.js
.netzwelt\.de[/&:?=_].*/netzweltde-deals.*\.jpg
.netzwerktotal\.de[/&:?=_].*/werbung/
.neue-braunschweiger\.de/images/banners/
.neues-deutschland\.de/bannerdeliver\.php
.neumarkt-tv\.de/Media/5/Banner%20NEU/jubilaeum_button_100x100\.jpg
.newgadgets\.de/gaming\.swf
.newgadgets\.de/td\.gif
.news\.at/prod/win2day/
.news\.de/resources/banner/
.news\.de[/&:?=_].*/ads/
.nfos\.de[/&:?=_].*/h4u_banner_
.nh24\.de/images/banners/
.nibelungenkurier\.de/upload/banner/
.nichtlustig\.de[/&:?=_].*/adv/
.nichtlustig\.de[/&:?=_].*/sponsor/
.niederschlagsradar\.de/550x150\.
.niederschlagsradar\.de/bannerdetails\.aspx\?
.nnz-online\.de/_banner/
.nnz-online\.de[/&:?=_].*/anzeige\.gif
.nnz-tv\.de/_Banner/
.noobtech\.at/wp-content/uploads/.*-125x125-
.noobtech\.at/wp-content/uploads/.*/125x
.noobtech\.at/wp-content/uploads/.*_125x125_
.nordschleswiger\.dk/uploads/Aabenraa-Kommune-
.nordschleswiger\.dk/uploads/EDC_Banneranzeige_950x130-virker\.swf
.nordschleswiger\.dk/uploads/Kreditbanken1\(2\)\.jpg
.nordschleswiger\.dk/uploads/Troest&Mensel_Annonce_Flash\.swf
.nordthueringen-bote\.de/gfx/banner110-160\.jpg
.nordthueringen-bote\.de/gfx/banner_
.notebookcheck\.com/fileadmin/templates/wbg/
.notebooksbilliger\.de/images/banner/
.novalja-zrce\.de/wp-content/uploads/.*/novalja12\.jpg
.nox\.to/static/images/sky/
.nr-kurier\.de/images/benderheadern\.gif
.nr-kurier\.de/images/ferdihombach\.gif
.nr-kurier\.de/pic/dbeyer_250_200\.swf
.nrhz\.de/flyer/media/banner/
.oe-static\.de/js/rmif\.js
.oeffentlichen-dienst\.de/images/banners/
.oekoportal\.de/sites/default/files/brennstoffzellen_heiztechnik\.jpg
.oekoportal\.de/sites/default/files/lifeforestry-oekoportal\.gif
.ofc\.de/v4/images/banners/
.ofdb\.de[/&:?=_].*/takeover_
.ohost\.de/layer\.php\?
.oilimperium\.de/img_standards/wallpaper01_
.olantis\.com/images/lzobanner\.gif
.oleo\.tv/images/3gs\.jpg
.omfg\.to/bu/
.omfg\.to/deal\.php
.omfg\.to/images/xmaspromo\.jpg
.omfg\.to/md/
.omfg\.to/meindea\.php
.onlinebanking-forum\.de/phpbb2/banner/
.onlinekosten\.de/images/tactixx-banner\.gif
.onlinereports\.ch/uploads/tx_macinabanners/
.onlinetvrecorder\.com[/&:?=_].*/ingoslayer\.js
.onlinewahn\.de/sky\.js
.onlinewelten\.com/img/sponsor/
.onlinewelten\.com/uploads/brandings/
.orf\.at/mojo/.*/banner\.html
.orientierungslauf\.de/images/anzeigen/
.orschlurch\.net/cgde\.js
.orschlurch\.net/cgde2\.js
.orschlurch\.net/player2\.js
.orschlurch\.net[/&:?=_].*/amzn/
.orschlurch\.net[/&:?=_].*/poster/
.oshelpdesk\.org/zwodreifuenf\.png
.osthessen-news\.de/booklet/top_banner\.js
.osthessen-news\.de/Osthessenbanner_
.osthessen-sport\.de/uploads/tx_macinabanners/
.osthessen-tv\.de/banner_fr\.php
.osthessen-zeitung\.de/uploads/tx_macinabanners/
.out\.webmaster-zentrale\.de/images/xyz/
.outdoor-foren\.de/images/enforcer/511_Outdoorforen_B\.jpg
.outdoor-foren\.de/images/vtlershop\.de/
.outdoorseite\.de/wp-content/uploads/.*/trailsport-banner\.jpg
.outnow\.ch/Media/Site/Waerbig/Backgrounds/
.overclockingstation\.de/banner/
.ox\.gassi-tv\.de[/&:?=_]
.ox\.immobilo\.de[/&:?=_]
.ox\.videobuster\.de[/&:?=_]
.paderborner-blatt\.de/images/banners/
.paninicomics\.de/pqcms/template/2008pc/img/.*/ecke-
.paradies-oberpfalz\.de/banners/
.partyamt\.de/images/b/
.passwort-generator\.com/assets/img/dropbox\.gif
.paules-pc-forum\.de/buch/
.paules-pc-forum\.de/images/buch/
.paules-pc-forum\.de/images/teufel/
.pc-experience\.de/iframe/iframe\.html
.pc-experience\.de/iFrame/iframe_pce\.html
.pc-max\.de[/&:?=_].*/banners/
.pcgameshardware\.de[/&:?=_].*/miniteaser/
.pcpraxis\.de/images/banners/
.pdfzone\.de[/&:?=_].*_banner_800x120\.
.pferd\.de[/&:?=_].*/ebay_logo\.gif
.photon\.de/bnnr/
.phpforum\.de/jbar/js/jbar\.min\.js
.phytodoc\.de[/&:?=_].*/phytodoc-banner\.js
.pi-news\.net[/&:?=_].*/paz-banner\.gif
.picdumps\.com/thumbs/monsters-army\.jpg
.picdumps\.com/thumbs/nemexia\.jpg
.picdumps\.com/thumbs/rotkaeppchen\.jpg
.pirate-loads\.to/fl\.php
.pirate-loads\.to/neu\.php
.pixelio\.de/resources/icons/anzeige\.gif
.pixelio\.de[/&:?=_].*/anzeige2\.gif
.pixelio\.de[/&:?=_].*/clipdealer\.gif
.pixelio\.de[/&:?=_].*/he_logo\.gif
.pizzamann\.at/images/banner_
.planet3dnow\.de/iframes/160homepage\.php3
.planet3dnow\.de/iframes/468ros\.php3
.planet3dnow\.de/iframes/ebay.*\.php
.planetradio\.de/flash/banner_
.planetradio\.de/images/banner-
.playporn\.to/lla2/
.playporn\.to/pfull\.js
.playporn\.to[/&:?=_].*\.directrev\.
.ploynt\.de/uploads/user_banner/
.pokerfirma\.com/wp-content/uploads/.*/gif_animata2_soloanim\.gif
.porn-traffic\.net/mdh_
.porn-x\.org/abkeulen\.js
.porn-xx\.net/pop-code\.js
.porn2you\.org/traffictrade\.js
.porn2you\.org[/&:?=_].*/rotator\.php
.pornflash\.net/out\.js
.pornit\.org/l\.js
.pornit\.org[/&:?=_].*/trade\.js
.pornkino\.to/pk_out\.js
.pornkino\.to[/&:?=_].*/rotator\.php
.porno-pornos\.org/slimtrade2\.js
.porno-streams\.com/porno1\.js
.porno-streams\.com/porno3\.js
.pornos-kostenlos\.tv/js/pornme\.js
.portalkunstgeschichte\.de/_images/banner-
.portalkunstgeschichte\.de/getmedia\.php/_media/banner/
.powerforen\.de[/&:?=_].*/lookatme\.js
.ppc-welt\.info[/&:?=_].*/banner/
.pr0gramm\.com/media/wm/
.pragerzeitung\.cz/images/banners/
.preisbock\.de/skin/.*/mbskyscraper\.gif
.preissuchmaschine\.de/banner/
.pressebox\.de/add/
.pressebox\.de/images/banner/
.pressemeldungen\.at/hinweis\.jpg
.pressemeldungen\.at/info\.png
.presseportal\.de/images/eyecatcher/
.primavera24\.de/images/banners/
.primavera24\.de/wp-content/themes/primavera/images/spezialBanner/
.primavera24\.de/wp-content/uploads/.*_Banner_600x124\.gif
.primavera24\.de/wp-content/uploads/banner_
.primavera24\.de/wp-content/uploads/primavera_giro_premium_600x\.png
.privacybox\.net/images/vpn\.gif
.private-blog\.org[/&:?=_].*/rotator\.php
.pro-linux\.de/images/forum/w0\.png
.pro-linux\.de[/&:?=_].*/action/
.pro\.de/pro_ballon/
.pro\.de[/&:?=_].*/layer\.js
.pro7livestream\.com/wp-content/plugins/wordpress-popup/popoverincludes/
.pro7livestream\.com[/&:?=_].*/divx\.gif
.progtech\.de/images/sponsoren/
.promiflash\.de/static-images/campaigns/
.promiflash\.de[/&:?=_].*/takeover\.
.prosieben\.de[/&:?=_].*/avt\.js
.prosieben\.de[/&:?=_].*/flashintro/
.proxydienst\.de[/&:?=_].*/max_rechts\.gif
.proxydienst\.de[/&:?=_].*/max_unten\.gif
.ps3-talk\.de/images/wp/bgbanner\.jpg
.ps3blog\.de/interstitial\.js
.ps3inside\.de/forum/images/green/.*-468\.gif
.ps3inside\.de/forum/images/green/figuren-zrr\.gif
.ps3inside\.de/forum/images/green/ps3inside_zockerrampe\.gif
.psychic\.de/bilder/angst-panikattacken\.png
.psychic\.de/bilder/eifersucht\.png
.psychic\.de/bilder/erroeten-ratgeber\.gif
.psychic\.de/bilder/erroeten\.png
.psychic\.de/bilder/expertenrat-banner-gross\.jpg
.psychic\.de/bilder/muskelentspannung\.png
.pszone\.eu/templates/playzone/img/bg_all\.jpg
.pszone\.eu/uploads/banners/
.putpat\.tv[/&:?=_].*/sponsoring/
.pz-news\.de[/&:?=_].*/module_wb/
.querverweis\.net/show/index\.php\?sac_cat=
.quoka\.de/fif\.html
.r3view\.de/images/banners/
.radio-siam\.de/banner/
.radio\.li/uploads/tx_macinabanners/
.radio2000\.it/images/banners/
.radio32\.ch[/&:?=_].*/banner/
.radio7\.de[/&:?=_].*/tx_scwbannermanager/
.radioedelweiss\.it/bilder_sponsoren/
.radiopilatus\.ch/images/banner/
.radiopsr\.de[/&:?=_].*/affiliates/
.radioquintessenz\.de/bilder/right_banner\.gif
.radiostephansdom\.at/images/amazon\.jpg
.radiostephansdom\.at/images/marketing/
.radioteddy\.de/typo3temp/pics/11570d51c6\.jpg
.radioteddy\.de/typo3temp/pics/60e804a0cd\.jpg
.radioteddy\.de/uploads/pics/.*_flashbanner_
.radioteddy\.de/uploads/pics/banner-
.radiox\.ch/portal_banneradmin/
.raetsel-hilfe\.de/design/120x120-
.raidrush\.ws/pr\.js
.ratgeber-hausmittel\.info/iframes/
.ratinger-news\.de/images/banners/
.ratinger-zeitung\.de/banner/
.rc-heli-fan\.org/images/banner/
.rdrvision\.com/images/partner/banner-
.rechnungswesenforum\.de[/&:?=_].*/ebay_logo\.gif
.rechtslupe\.de/banner/
.redensarten-index\.de/banner/
.reiseangebote\.sueddeutsche\.de/products/iframe/
.reportnet24\.de/banner/
.rhein-zeitung\.de/cms_media/module_wb/
.rheinforum\.com/banner/
.rmi\.it[/&:?=_].*/banner_
.rnb-nutte\.in/popdown\.js
.rnz\.de/grafiken/rnz_banner/odenwaelder\.gif
.rnz\.de/grafiken/rnz_banner/theater_banner\.jpg
.rnz\.de/netcontentmedia/bilder/red-banner-
.rockz\.com/images/ctd-leader\.jpg
.rollertuningpage\.de/banner/
.rollertuningpage\.de/franky/RTP_banner_
.rollertuningpage\.de[/&:?=_].*/250x250-
.rollertuningpage\.de[/&:?=_].*/800x100-
.rollertuningpage\.de[/&:?=_].*/rf_webbanner_
.rollertuningpage\.de[/&:?=_].*/skz_minibanner_
.rollingplanet\.net/wp-content/uploads/.*/BANNER-
.rollingplanet\.net/wp-content/uploads/.*/Banner_
.rostock\.de/bilder/_werbekunden/
.rot-weiss-erfurt\.de/marketing/img_content/images/banner_wechsel/
.rot-weiss-essen\.de/uploads/tx_macinabanners/
.rp-online\.de/app/module/buttons/marktgefluester/
.rp-online\.de[/&:?=_].*%20Channelsponsoring%
.rro\.ch/cms/topbanner/
.rsa-sachsen\.de/images/RSA/icons/affiliates/
.rsa-sachsen\.de/rsa/vermarktung/
.rsh\.de[/&:?=_].*/playlist_amazon\.gif
.rtl\.de/img/flash_slider_o2\.swf
.rtl\.de/rtlde/media/schliessen\.swf
.ruhrbarone\.de[/&:?=_].*/msbannerl_
.rummeldumm\.de[/&:?=_].*/werbefrei\.gif
.russland\.ru/images/banneroben750x100\.jpg
.russland\.ru/images/bannerrechts200x600\.jpg
.russland\.ru/images/buechervielfrassban300\.jpg
.russland\.ru/images/literaturreisen300\.jpg
.russland\.ru/images/roedl_gross580\.jpg
.russland\.ru/images/visaservice\.gif
.russland\.tv/images/raduga-banner450\.jpg
.rv-news\.de/siggi_neu09\.jpg
.saarbruecker-zeitung\.de/storage/med/finerio/
.safeyourlink\.com/partner/
.salve-tv\.net/datenbank/image/motive_startseite/flug7\.jpg
.salve-tv\.net[/&:?=_].*/salve-anzeigen\.jpg
.sat-erotik\.de/banner/
.sat-ulc\.eu/images/misc/ebay_logo\.gif
.satindex\.de/banner/
.saugking\.net[/&:?=_].*/layer\.js
.saugzone\.info/images/.*\.gif$
.saugzone\.info/test\.js
.saugzone\.info/vote/
.saz-aktuell\.com/img/com\.png
.sb\.sbsb\.cc/images/first/
.sb\.sbsb\.cc/random\.html
.sb\.sbsb\.cc/random2\.html
.sb\.sbsb\.cc[/&:?=_].*/rid\.php\?pic=rando
.sbb\.ch/images/bw-hta-visa-bg\.jpg
.sca-stveit\.at/images/content/partner/
.scene-links\.us/AVTZ567\.js
.sceneload\.to/random\.php
.scfreiburg\.com/sites/default/files/sponsoren_
.schambereich\.net/js/mdhsbexit\.js
.schambereich\.net/js/mdhsbexit_adplib\.js
.schnaeppchenfuchs\.com/eol2\.png
.schnelle-online\.info/banner/
.schnelle-online\.info/pictures/banner/
.schnittberichte\.com/pics/.*_banner\.jpg
.schnittberichte\.com/pics/.*_Siteskin_
.schnittberichte\.com/pics/banner_bond\.jpg
.schnittberichte\.com/pics/bond_post\.jpg
.schnittberichte\.com/pics/mk2\.jpg
.schnittberichte\.com/pics/Riddick_sb\.jpg
.schnittberichte\.com/pics/Schnittberichte_BoRA\.jpg
.schnittberichte\.com/pics/Schnittberichte_Scorpion\.jpg
.schnittberichte\.com/pics/Sons-of-Anarchy_v2\.jpg
.schnittberichte\.com[/&:?=_].*_459x1200_
.schnittberichte\.com[/&:?=_].*_takeover_
.schoener-onanieren\.de/grifftechniken/maenner/autogas\.jpg
.schule-studium\.de/Studienkreis/Studienkreis160-600-
.schule-studium\.de/Studienkreis/StudienkreisSkyscraper\.jpg
.schule-studium\.de[/&:?=_].*-160-600-
.schwaebische\.de[/&:?=_].*/sykscraper\.jpg
.schwaebische\.de[/&:?=_].*_articleorg_314x112_schwaebische_hbp\.jpg
.schwedenstube\.de/wimages/
.scm-gladiators\.de/o\.red\.c/adv-
.scm-handball\.de/o\.red\.c/adv-
.scm-handball\.de/o\.red\.c/files/Webbanner_
.sealed\.in[/&:?=_].*/downloadmirror\.
.seatforum\.de/forum/images/banner_
.seatforum\.de[/&:?=_].*/anzeige\.gif
.see-online\.info/banner_pictures/
.sein\.de/uploads/banner_
.sein\.de/uploads/gilmore\.jpg
.sein\.de/uploads/master-of-life-2\.gif
.sein\.de/uploads/ronnigilla\.jpg
.sein\.de/uploads/sein_dezember\.gif
.sellerforum\.de/banner/
.sensor-test\.de/assets/Banner/
.seo-consulting\.de/bilder/ban_
.seo-united\.de/images/sponsoren_
.serien\.bz[/&:?=_].*/popdown\.php
.serienjunkies\.org/checkstatus\.php
.serienjunkies\.org/media/ajax/dd/
.serienjunkies\.org/media/ajax/deals/
.serienjunkies\.org/media/js/fpjsa0\.js
.serienjunkies\.org/media/mdz/
.serienjunkies\.org[/&:?=_].*/usenet\.php
.serienoldies\.de[/&:?=_].*/jamba_ringtone\.gif
.service4handys\.de/banner/
.sevac\.com/images/bmain-
.sevenmac\.de/banner/
.sexgeschichten\.com/banner/
.sexkino\.to/777cams\.html
.sexkino\.to/777camsvert\.html
.sexuria\.com/layer\.js
.sexuria\.com/muvi_to468\.jpg
.sexuria\.com/poup\.js
.sexuria\.com[/&:?=_].*/layer_
.sg-flensburg-handewitt\.de/uploads/tx_macinabanners/
.sg-kt\.de/images/banners/
.sg-leutershausen\.de/storage/Sponsoring/Banner/
.sgcoburg\.de/finale/bilder/promo/
.shop-027\.de/images/logos/mallux_logo_
.shopanbieter\.de/images/partner/
.silbernews\.com[/&:?=_].*/banner/
.simplytest\.me/sites/default/files/sponsors/
.simpsons\.to[/&:?=_].*/banner\.html
.simpsons\.to[/&:?=_].*/boxy\.js
.simpsons\.to[/&:?=_].*/popupcode\.js
.sk-austriakaernten\.at/images/990x33_sk_austria_kaernten2\.swf
.sk-austriakaernten\.at/images/bande_animation\.swf
.slashhosting\.de/wp-content/uploads/ad_
.sms-box\.de/sms-popup\.js
.sms4free\.cc/js/more\.php
.soft-ware\.net/banner/
.songtexte\.bz[/&:?=_].*/spreadshirt\.png
.spartoo\.de/footer_tag_iframe_
.spass-junkies\.de[/&:?=_].*/dealdoktorr\.php
.spealz\.de[/&:?=_].*/dragonsoul-neonga\.jpg
.speedlounge\.in[/&:?=_].*/highspeedmirror\.jpg
.speedlounge\.in[/&:?=_].*=highspeedmirror$
.spiegel\.de/gutenb/img/hoeflich-schokolade\.gif
.spiegel\.de/gutenb/img/HuH-Banner\.gif
.spiegelfechter\.com/img/apotheke\.gif
.spiegelfechter\.com/img/logone\.jpg
.spiegelfechter\.com/img/parship_pic\.jpg
.spiegelfechter\.com/img/poetry\.png
.spiegelfechter\.com/img/schottenland_175x80\.png
.spiegelfechter\.com/wordpress/amazon\.html
.spielautomatenforum\.de/allslots\.gif
.spielautomatenforum\.de/stake7_merkur\.jpg
.spielbox\.de/gifs/sky/
.spielesite\.com[/&:?=_].*/sponsoren_search\.php
.spielesnacks\.de/wp-content/uploads/.*-wallpaperx\.jpg
.spinnes-board\.de/banner/mail\.gif
.sport1\.de/img/TRB_SPORT1_810x90px_
.sport1\.de[/&:?=_].*/presenting_
.sport1\.de[/&:?=_].*/presentings/
.sport1\.de[/&:?=_].*/werbung/
.sportalplus\.com[/&:?=_].*/anzeige\.gif
.sportbild\.bild\.de/sport/partner/viagogo/
.sportnews\.bz/uploads/pics/.*_pubblicita_
.sportnews\.bz/uploads/pics/banner869x90\.gif\.gif
.sportnews\.bz[/&:?=_].*_970x120\.gif
.spox\.com[/&:?=_].*/xkoop/
.sprachnudel\.de/js/too1s\.js
.spreadnews\.de/banner/
.spreeblick\.com[/&:?=_].*/intro_banner\.png
.spreeblick\.com[/&:?=_].*/thomann_banner_2\.jpg
.spvggunterhaching\.de/themes/haching/images/BSWALP-Onlinebanner\.gif
.stadt-bremerhaven\.de/grafiken/footer\.gif
.stadt-bremerhaven\.de/grafiken/getgoods2013\.jpg
.stadt-bremerhaven\.de/grafiken/gg_banner_320x100_ani\.gif
.stadt-bremerhaven\.de/grafiken/redcoon\.jpg
.stadt-bremerhaven\.de/wp-content/uploads/2014/02/brandbox-sony-vaio-multi-flip\.png
.stadt-werther\.de/uploads/tx_macinabanners/
.static-fra\.de/nitronow/css/ad\.css
.static-fra\.de/rtlnow/css/ad\.css
.static\.atomload\.at[/&:?=_]
.static\.filmpalast\.to[/&:?=_]
.static\.top-hitz\.com[/&:?=_]
.stb-web\.de/new/grafiken/banner/
.stealth\.to/usenext
.stealth\.to[/&:?=_].*/layer\.js
.steelwarez\.com/cookie\.html
.steelwarez\.com/layer\.
.steelwarez\.com/layer/
.steelwarez\.com/pop\.js
.steelwarez\.com/pop\.php
.stepstone\.de/home_bottombanner\.
.stepstone\.de[/&:?=_].*/skyscraper/
.stern\.de/bilder/stern_5/allgemein/extras_vermarktet/
.stol\.it/var/ezflow_site/storage/images/beilagen-archiv/
.stol\.it/var/ezflow_site/storage/images/werbung_intern/look4you/
.store51\.de/banner\.js
.store51\.de/banner1\.js
.stream-oase\.tv/images/banners/
.stream-oase\.tv/images/fernsehen\.to\.png
.stream4\.org[/&:?=_].*/servletpop\.php
.stream800\.com/images/firstload-anmelden\.gif
.stream800\.com/layer\.js
.streams\.to/popup\.php
.studio100\.de/static/images/banner/
.studium-ratgeber\.de/uploads/images/.*-lb\.jpg
.studium-ratgeber\.de/uploads/images/.*-sky\.jpg
.stuttgarter-nachrichten\.de/meinprospekt/
.stuttgarter-nachrichten\.de[/&:?=_].*/stn_ajax_galleryad\?
.stuttgarter-zeitung\.de/meinprospekt/
.suedkurier\.de[/&:?=_].*/textlinktest\.php
.suedkurier\.de[/&:?=_].*_omsv\.js
.suedtirol-it\.com/images/banner/
.suedtiroltv\.it/images/social/banner
.sunshine\.ch/files/banner
.superfly\.fm/images/banners/
.superfunblog\.com[/&:?=_].*/layer\.js
.supertipp-online\.de/uploads/tx_macinabanners/
.surfmusik\.de/anz1\.gif
.surfmusik\.de/audialsone-1\.gif
.sv-schalding-heining\.de/cm/uploads/tx_macinabanners/
.svm-fan\.net/images/anzeige\.gif
.svm-fan\.net/images/banner/skyh2010\.jpg
.svs\.co\.at/img/spons\.jpg
.svs\.co\.at/img/titel_sponsores\.gif
.svs\.co\.at/ktz\.jpg
.svs\.co\.at/nwbanner2\.jpg
.svs\.co\.at/nwbannernavi\.jpg
.svs1916\.de/_media/images/content/Partner_2012/source/
.svwehen-wiesbaden\.de/medium/fitness_Sample\.png
.svwehen-wiesbaden\.de/medium/Hermann_Sample\.png
.swimnews\.de[/&:?=_].*_250x880\.jpg
.swimnews\.de[/&:?=_].*_960x120\.jpg
.symptomat\.de/ama/
.synchronkartei\.de/amazonproxy\.php
.t-online\.de/lisa/em/html/ecommercebar/
.t-online\.de[/&:?=_].*/fooma-bundesliga-manager-grafik-t-online-de-\.gif
.tag-des-hundes\.de/tl_files/images/banner/.*_skyscraper\.swf
.tagblatt\.de/cms_media/module_wb/
.tageblatt\.com\.ar/banners/
.tagseoblog\.de/images/schildkroete-net\.png
.tagseoblog\.de/images/vpp-werben280x250\.jpg
.taketv\.net/bilder/backdell\.jpg
.taschenlampen-forum\.de/images/fenix/fenix-taschenlampen-2014\.swf
.taschenlampen-forum\.de/images/jetbeam/
.taschenlampen-forum\.de/images/ktl-store/CR6HC50_728X9001\.gif
.taschenlampen-forum\.de/images/myled\.com/MyLED-Taschenlampe\.jpg
.taschenlampen-forum\.de/images/myled\.com/Taschenlampen-Forum\.jpg
.taschenlampen-forum\.de/images/neonlaserchina\.com/TLF\.jpg
.taschenlampen-forum\.de/images/thrunite/TN35-45\.jpg
.taschenlampen-forum\.de/images/thrunite/TN35-90\.jpg
.taschenlampen-forum\.de/images/tmart\.com/t-mart-01-2013\.jpg
.taschenlampen-forum\.de/images/vtlershop\.de/
.tattoo-spirit\.de/subsystems/adv_manager/
.taucher\.net/tnadsy/
.team-alternate\.de/docs/banner/
.technobase\.eu[/&:?=_].*/banner/
.technobase\.fm/banner/
.teen-blog\.us/popup\.js
.tekkbase\.net/board/images/banner/
.tele5\.de/images/uploads/banner/
.teleradiovinschgau\.it/images/banners/
.telmi\.it/images/btb_pittogramma\.png
.teltarif\.de/ad/
.testreich\.com/layer.*\.html
.ticket-leistung\.de[/&:?=_].*/banner/
.titanic-magazin\.de/fileadmin/content/anzeigen/
.tobitech\.de/images/.*\.swf
.tollesthueringen\.de/img_proximus/anzeigen/
.top-fm\.de/images/partner/
.top-hitz\.com/js/backtome\.js
.top100station\.de/ad_
.torrent\.to/f\.php
.torrent\.to/new/first\.php
.torrent\.to/res/deal5/
.torrent\.to/res/webc/
.torrent\.to[/&:?=_].*/layer\.js
.torrent\.to[/&:?=_].*/ttoads\.js
.toxic\.fm[/&:?=_].*/sponsoren/
.trancebase\.fm/banner/
.transfermarkt\.de/bilder/inter_sport_
.transfermarkt\.de/bilder/intersport-
.trapp-it-consulting\.com/images/freelancer-it-
.travianstats\.de/amenu\.php
.travianstats\.de/aoben\.php
.travianstats\.de/aunten\.php
.treffy\.de/images/preisbringer\.jpg
.trendhure\.com/gadgets/
.trendhure\.com[/&:?=_].*/gadgets\.php
.trendmile\.de/gedichte\.htm
.trenkwalder-admira\.com/flash/sponsor\.swf
.trenkwalder-admira\.com/img/banner/
.triff-chemnitz\.de/genbanner\.php
.trophies-ps3\.de/forenheader/amazon-
.tsv-friedberg\.de/images/Scroller/
.tsv1860\.de[/&:?=_].*/Arabella_Banner-Startseite\.jpg
.tsv1860\.de[/&:?=_].*/muenchen_de_471x90\.jpg
.tsvbodnegg\.de/wp-content/uploads/.*/altherr\.png
.tt\.com/csp/cms/sites/tt/resources/sidebar/module145/images/
.tus-n-luebbecke\.de/wp-content/uploads/.*-Webbanner-
.tutsi\.de/tutsi-blog-bilder/amazon-sonderangebote-prozente\.gif
.tutsi\.de/tutsi-blog-bilder/o2-nxt-tarif-vergleich\.jpg
.tutsi\.de/tutsi-blog-bilder/usenext-download-kostenlos\.gif
.tv-huettenberg\.de/startpage/hauptsponsoren_intro\.png
.tv-huettenberg\.de/startpage/premiumpartner_intro\.png
.tv-kabel-plus\.de/kabelplus/banner/
.tv-kabel-plus\.de/kabelplus/icons/speedtest\.jpg
.tv-kabel-plus\.de/kabelplus/img/kptagpreis\.jpg
.tvb1898\.de/fileadmin/img/anz/
.tvb1898\.de/uploads/pics/kempa\.jpg
.tvb1898\.de/uploads/pics/Sponsoren_
.tvdigital\.de/files/images/browsergames/
.tvh1\.de/images/stories/logos/fb_formaxx-
.tvh1\.de/images/stories/sp_header/
.tvspielfilm\.de/_img/plogos/golf\.jpg
.tvspielfilm\.de[/&:?=_].*/partner/
.tvtoday\.de/_imgToday/plogos/golf\.jpg
.tweakpc\.de[/&:?=_].*/anzeige_v60\.gif
.u11\.de/cgi-bin/count/
.uhrzeit\.org/sys/banner_bigsize\.php
.uhrzeit\.org/sys/wallpaper/
.ultras\.ws/acab24\.jpg
.ultras\.ws/betfair\.gif
.ultras\.ws/bild\.php/.*banner
.ultras\.ws/cremers\.gif
.ultras\.ws/extrem\.jpg
.ultras\.ws/havics\.jpg
.ultras\.ws/hooliday\.gif
.ultras\.ws/label\.gif
.ultras\.ws/oben\.php
.ultras\.ws/pgwear\.gif
.ultras\.ws/red\.jpg
.ultras\.ws/supporter\.png
.ultras\.ws/supporterfilme\.php
.ultras\.ws/ultrasart\.gif
.underground-links\.com/out\.js
.underground-links\.com/ulinks_out\.js
.underground-links\.org/ulinksd_out\.js
.unitymediaforum\.de/images/unitymedia/
.unitymediakabelbwforum\.de/images/unitymedia/
.unterhaus\.at/ooe/images/banners/
.unternehmerkarte\.de/include/config/popup\.js
.unterwasserwelt\.de/assets/images/.*_banner_
.unterwasserwelt\.de/assets/images/banner-
.unterwasserwelt\.de/assets/images/banner_
.unterwasserwelt\.de/assets/images/fotowettbewerb_13_traun_01\.gif
.unterwasserwelt\.de/assets/images/inserat_
.unterwasserwelt\.de/assets/images/team_uww_03_beratungstelefo\.jpg
.uploaded-premium\.ru/giga\.gif
.v2load\.de/kamp/
.vampirediaries\.in/partner\.php
.vegan\.de/foren/templates/default/images/b_.*\.gif
.vegetarierforum\.com[/&:?=_].*/google_links\.jpg
.verboten\.to/unhverb/
.verbrechen\.info/images/abus_
.verbrechen\.info/images/leaderboard/
.verbrechen\.info/images/skyscraper/
.verbrechen\.info/kaspersky/
.vfb\.de/fileadmin/REDAKTION/Business/Partner/Sponsoren_
.vfl\.de/fileadmin/vfl/templates/flash/
.vfl\.de/sponsorenviewer/sponsoren\.swf
.vfl\.de/uploads/tx_macinabanners/
.vhs-ol\.de[/&:?=_].*/ewe-skyscraper_
.via-ferrata\.de/forum/templates/prosilverse/images/campz-banner\.jpg
.via-ferrata\.de/images/300x120px_
.via-ferrata\.de/images/verticalextreme\.jpg
.via-ferrata\.de/templates/forum/banner/
.vienna\.at[/&:?=_].*/gewinnabfrage-120-90\.swf
.vinschgerwind\.it/images/banners/
.vipbilder\.net[/&:?=_].*/layer\.js
.visions\.de/assets/visions_300x150_
.vitax\.abc-sms\.de[/&:?=_]
.viviano\.de/teaser
.viviano\.de[/&:?=_].*/ad_anzeige_
.vol\.at/flash/gewinnabfrage-120-90\.swf
.voltiforum\.de/images/banner2\.jpg
.voltigierforum\.de/images/banner2\.jpg
.voltigierzirkel\.de[/&:?=_].*/banner/
.vsg2001\.de/images/banners/
.w\.online-verlag-freiburg\.de[/&:?=_]
.w3-warez\.cc/images/hoster/ref_
.wallpaper-arena\.to/ad\.js
.wallstreet-online\.de/_plain/_shared/default/hvb\?
.wallstreet-online\.de/banners/
.wallstreet-online\.de/frontend/img/custom/hvb/icon\.png
.wallstreet-online\.de[/&:?=_].*/gafc/
.wallstreet-online\.de[/&:?=_].*/lynx_logobanner\.png
.wallstreetjournal\.de/static_html_files/jsframe\.html\?jsuri=.*doubleclick\.net/
.warez-load\.com/random\.php
.warezking\.in[/&:?=_].*/layer\.js
.waswiewo\.com/media/banner/
.watchever\.bild\.de[/&:?=_]
.wcm\.at/images/attingo\.gif
.web\.de/banner/
.web\.de/banner2/
.web\.de/banner\?
.web\.de/stv/img/global/wl/webde/img/nosteps/nosteps_.*_300x400_
.web\.de/v/home06/icons/buster/
.webmail\.sh/media/banner/
.webme\.com/pic/s/spieloase/banner_spieloase\.gif
.webmiles\.de/files/libs/css/moods/de_de/.*\.css
.webnews\.de[/&:?=_].*/layer_interactive\.swf
.webnews\.de[/&:?=_].*/sky_interactive\.swf
.websingles\.at[/&:?=_].*/images/banners/
.webstandard\.kulando\.de[/&:?=_].*/codingpeople-banner03\.jpg
.webwork-magazin\.net[/&:?=_].*/facebook_gsl_zu_breit\.jpg
.wegwerfemailadresse\.com/images/banner
.weihnachtsmarkt-deutschland\.de/anzeige/
.wein-plus\.de/images/banner/
.wein\.de[/&:?=_].*/anzeige_side\.
.welt\.de[/&:?=_].*/eas-
.weltuntergang-2012\.de/pub/
.wer-weiss-was\.de/cb/ARCHIVEARTICLE/AFTER_HEADLINE
.wer-weiss-was\.de/cb/ARCHIVEARTICLE/AFTER_QUESTION
.wer-weiss-was\.de/cb/ARCHIVEARTICLE/PRE_HEADLINE
.wer-weiss-was\.de/img\.r/logo_n24\.png
.wetter\.com/js/sda\.js\?1
.wetter\.com[/&:?=_].*/soi\.js
.wetter\.net/images/karten-tickets\.gif
.wetter\.net/images/karten-tickets2\.gif
.wetterauer-zeitung\.de/cms_media/module_wb/
.wettforum\.info/banner/
.wettforum\.info/phpbb2/content_rot\.php\?
.whudat\.de/images/lc_banner\.jpg
.whudat\.de/images/td-blogbanner\.gif
.wiiunews\.at/wp-content/uploads/.*/amazon\.jpg
.wiiunews\.at/wp-content/uploads/2012/06/wii_u_vorbestellen\.jpg
.wiiunews\.at/wp-content/uploads/2012/08/crazycase1\.gif
.willhaben\.apa\.net/clientscript/google/
.wilmaa\.com[/&:?=_].*/brandings/
.win-lan\.de[/&:?=_].*/banners/
.windows-tweaks\.info[/&:?=_].*/safersurf__
.winrar\.de/images/emsi\.jpg
.winrar\.de/images/emsi2\.jpg
.wintergarten-ratgeber\.de/uploads/tx_macinabanners/
.wirsiegen\.de/wp-content/plugins/wordpress-popup/popoverincludes/
.wirtschaftsblatt\.at[/&:?=_].*=adsense
.witz\.de/images/banners/
.wochenblitz\.com/images/banners/
.woelfe-handball\.de/uploads/tx_rlmpflashdetection/.*\.swf
.wohnmobilforum\.de/anhaengerkupplungen\.jpg
.wohnmobilforum\.de/aqua\.jpg
.wohnmobilforum\.de/basba\.jpg
.wohnmobilforum\.de/camping-preisbrecher_header\.jpg
.wohnmobilforum\.de/caravantechnik\.jpg
.wohnmobilforum\.de/fleig\.jpg
.wohnmobilforum\.de/kro\.png
.wohnmobilforum\.de/luftfederung\.jpg
.wohnmobilforum\.de/motorradtraeger\.jpg
.wohnmobilforum\.de/ott\.jpg
.wohnmobilforum\.de/safety\.jpg
.wohnmobilforum\.de/waeco\.jpg
.wohnmobilforum\.de/wget/ebay\.php
.wohnwagen\.net/forum/wget/get_xml\.php
.wolfenbuettelheute\.de/platzierungen/
.wonnemar\.de[/&:?=_].*/magnum_banner1\.swf
.world-of-hentai\.to/ahw\.php
.world-of-hentai\.to/bilder/2widesky_g\.php
.world-of-hentai\.to/bilder/leaderboard\.php
.wortfilter\.de[/&:?=_].*/4sellers\.gif
.wortfilter\.de[/&:?=_].*/klarna_banner\.gif
.wortfilter\.de[/&:?=_].*/yatego-shopping\.gif
.wowmopguide\.de[/&:?=_].*/layer\.js
.woz\.to/tipp/
.wuppertaler-rundschau\.de/web/promo/
.ww-kurier\.de/images/benderheader\.gif
.ww-kurier\.de/images/ferdihombach\.gif
.ww-kurier\.de/pic/dbeyer_250_200\.swf
.wz-newsline\.de/polopoly_fs/.*-900x120\.
.xbox-newz\.de/portal/images/brandings/
.xbox360freaks\.de/images/baner\.swf
.xdate\.ch/banners/
.xhamster\.info/banner/
.xhamster\.info[/&:?=_].*/slideimage\.js
.xp-antispy\.org[/&:?=_].*/sponsor_
.xtc-modified\.org/images/banner/
.xtream\.to/images/player/save\.png
.xup\.in/com/pop\.
.xxx-4-free\.net/gfx/layer/
.xxx-blog\.to/img/wbm/
.xxx-blog\.to[/&:?=_].*/pstreams\.js
.xxx-blog\.to[/&:?=_].*/rotator\.php
.yabeat\.com/generate_layer\.php
.yabeat\.com/i.*\.js$
.yabeat\.com[/&:?=_].*3\.js$
.yasni\.de[/&:?=_].*/partner/
.yigg\.de[/&:?=_].*/sponsorings/
.youfreetv\.net/js/jquery\.ad\.js
.yourdealz\.de/120\.gif
.youzap\.de/img/fraag\.de\.jpg
.zapper-hulda-clark\.de[/&:?=_].*-webbanner_.*\.swf
.zebradem\.com[/&:?=_].*/banner/
.zeckenwetter\.de/img/banner/
.zeno\.org/banner-
.zensiert\.to/anmeldung\.html
.zensiert\.to/geile-amateure\.html
.zensiert\.to/loeblich\.php
.zensiert\.to/sehr-geile-amateure\.html
.zensiert\.to/zwei\.html
.zonx\.de/layer/
.zumlink\.de/public/images/banner/
.zweinullig\.de/wp-content/uploads/125\.png
.zweinullig\.de/wp-content/uploads/chaershop\.jpg
.epochtimes\.de/js/chkba\.js
.gamona\.de/assets/.*\.swf
.gamona\.de/assets/.*_1000x140\.
.gamona\.de/assets/.*_160x800_
.gamona\.de/assets/lostsaga/
.gamona\.de/wp-content/1851/
.gamona\.de/wp-content/2014/
.gamona\.de/wp-content/45
.gamona\.de/wp-content/46
.gamona\.de/wp-content/66
.gamona\.de/wp-content/67
.gamona\.de/wp-content/up/
.media\.epochtimes\.de/img/
.mv-spion\.de/ajax/lc\?content=qwert
.mv-spion\.de/ajax/lc$
{ +filter{easylistgermany} }
*
{ -block }
^http://byte\.to/js/javascript\.js$
^http://byte\.to/js/wz_tooltip\.js$
.1000steine\.de/img/ads/
.ab-in-den-urlaub\.de[/&:?=_].*\.popunder\.js
.ad-tuning\.de[/&:?=_].*/ad-tuning-footer\.png
.anonza\.de[/&:?=_].*/adonline\.css
.anonza\.de[/&:?=_].*/adonline\.js
.askstudents\.de/optimizer\.php\?.*/adcontrol\.js
.berliner-zeitung-online\.de/specials/ads/scripts/standard_ads\.css
.bundesliga\.de/js/my_ad_integration\.js
.canoo\.net/services/wordformationdictionary/gifs/
.christoph-reischer\.at/wb/media/banner_468x60_2\.jpg
.cinebee\.org/wp-content/plugins/wp-.*\.js$
.classic-motorrad\.de/anzeigen/layout_images/new/top_ads_icon\.gif
.dtb-gymnet\.de[/&:?=_].*[/&:?=_]admID[/&:?=_]
.efiliale\.de/efiliale/pop/js/pop\.js
.exposegmbh\.de/css/mediaboxAdv-Dark\.css
.feuerwehr-borken-hessen\.de/de/banner\.php
.fewo-direkt\.de[/&:?=_].*/advertiser\.css
.fh-muenster\.de/leitbild/banner\.php
.fn-neon\.de/javascript/adserver_banner\.js
.forum\.froxlor\.org[/&:?=_].*/adsense\.css
.fussball\.sv-kehlen\.de/werbepartner\.htm
.g-stream\.in/lla2/smoothscroll\.js
.gamepro\.de/js/gamepro/my_ad_integration\.js
.gamers\.at/images/branding/.*/gamers_at\.jpg
.gamers\.at/images/branding/.*/header\.
.gamers\.at/images/branding/.*/header_
.gamers\.at/images/branding/.*_header\.
.gamersplus\.de/images/branding/.*/gamers_de\.jpg
.gamersplus\.de/images/branding/.*/header_
.gamersplus\.de/images/branding/.*_header\.
.gamersplus\.de/images/branding/.*_header_
.games\.myvideo\.de/ressource/js/sevengames/sevengames/adtags\..*\.js\?
.gamestar\.de[/&:?=_].*/my_ad_integration\.js
.geo\.de[/&:?=_].*/gujAd\.js
.googlewatchblog\.de[/&:?=_].*/adsense\.png
.gymnasium-august-dicke\.de[/&:?=_].*/ads/
.gynny\.de/img/affilinet/
.interhome\.at/javascript/ad-gallery\.js
.jade-hs\.de[/&:?=_].*/ext-adv\.js
.kurier\.at[/&:?=_].*/ac_oetags_clone\.js
.markt\.de[/&:?=_].*/advert_search_results\.gif
.msi-computer\.de/js/topad/topad\.css
.myfreefarm\.de/city/ajax/buyad\.php\?
.n24\.de[/&:?=_].*/my_ad_integration\.js
.nordclick\.de/js/colors/adsense_colors\.js
.oeko-komp\.de/evoAds2/
.openx\.musotalk\.de/crossdomain\.xml
.os1\.tv/js/omsvc_externalad\.js
.quadelite-forum\.de/images/misc/web-banner2_980x100\.jpg
.raumobil\.de/js/advertise\.js
.reaktion-talentschule\.de/tl_files/layout/rotation/banner
.rtl\.de[/&:?=_].*/player_modul_onclick_300x250\.jpg
.saugking\.net/css/ads\.css
.save\.tv/stv/img/global/trailer20sec\.swf\?
.sevengames\.at/ressource/js/sevengames/sevengames/adtags\..*\.js
.smartclip\.net/inpage/inpage\.js
.spielkarussell\.de[/&:?=_].*/ads_loader_new\.js
.sport1\.fm/ad/my_ad_integration\.js
.tape\.tv/tape2fs/images/campaign/teaser-redaktion\.swf\?
.toggo\.de/js/advertise\.js
.videostream4u\.com[/&:?=_].*/ac_oetags_clone\.js
.webdisk\.ads\.mwn\.de/Scripts/ext-adv\.js
.wetter\.com[/&:?=_].*/openx_fl\.js
.wm-druckarena\.de/scripts/Werbebanner\.
.wodas\.wetteronline\.de/static/womfkts\.js
.xara\.hse24\.de[/&:?=_].*/hse_videoplayer\.swf
.betreut-wohnen\.de/adserver/ad\.js
.blick\.ch[/&:?=_].*/advertisement\.js
.boardking\.de[/&:?=_].*/adframe\.js
.combatarms-game\.de/adframe\.js
.crackajack\.de[/&:?=_].*/advertising\.js
.david-forum\.de/advertisement\.css
.ddl-search\.biz/js/advertisement\.js
.ddl-search\.biz/js/advertisements\.js
.derlacher\.de/static/lib/advertisement\.js
.dokumente-online\.com[/&:?=_].*/adframe\.js
.ebook-hell\.to/js/ads\.js
.eclipso\..*/plugins/js/adframe\.js
.einrichtungsbeispiele\.de[/&:?=_].*/click\.js
.fastshare\.org/advertisement\.js
.fernsehen\.to/advertisement\.js
.forum-fuer-senioren\.de[/&:?=_].*/ad\.js
.free-klingeltoene-handy\.de/adframe\.js
.gamona\.de[/&:?=_].*/up/.*\.png
.gassi-tv\.de[/&:?=_].*/adframe\.js
.goolive\.de[/&:?=_].*\.js$
.hubbahotel\.cc[/&:?=_].*/advertisement\.js
.kaufn\.com/banner/ads/adserver/click/ad\.js
.mannfuermann\.com/mfm/static/adcode\.js
.mirror-archiv\.com/banner/ads/adserver/click/ad\.js
.mufa\.de/js/advertisement\.js
.mypolonia\.de[/&:?=_].*/adframe\.js
.myvideo\..*/ad\.js
.n-roms\.de/adframe\.js
.picload\.org/ads-1\.js
.ping-timeout\.de/banner/ads/adserver/click/ad\.js
.quoka\.de[/&:?=_].*/adframe\.js
.rechnungswesenforum\.de/abp/adblock_detector\.js
.schulzeux\.de/js/show_ads\.js
.starwars\.gamona\.de[/&:?=_].*_.*/.*\.png
.tape\.tv/js/adblockdetection\.js
.tiervermittlung\.de/adblock\.js
.tiervermittlung\.de/advertisement\.js
.tower-defense-spiele\.de/wp-content/themes/Denver/js/ads\.js
.ttads\.de/www/delivery/banner/ads/click\.js
.ttads\.de/www/delivery/banner/click\.js
.ttads\.de/www/delivery/click\.js
.u-hacks\.net/ads\.js
.uabp\.tk/adserver/ads\.js
.ul-load\.com/ads\.js
.werbeblocker-erkennen\.webconrad\.com/adframe\.js
.campact\.de[/&:?=_].*_300x250\.gif
.gardenparc\.ch/files/artikelbilder_
.social-media-hosting\.com[/&:?=_].*_120x60\.jpg
{ -block +handle-as-image }
.0815sms\.com/img/pagepeel\.php\?
.ad\.netzquadrat\.de/viewbanner\.php3\?bannerid=
.adition\.com/banners/
.adition\.com/banners/
.adserver\.devaki\.ch/www/images/
.adshot\.de/click/view\.php
.aka-cdn-ns\.adtech\.de/apps/
.altfarm\.mediaplex\.com/ad/ck/
.banner\.edll-fir\.de[/&:?=_]
.banners\.webmasterplan\.com/view\.asp\?ref=
.cache\.kalaydo\.de/mmo/logo/advert/
.devaki\.ch/www/delivery/lg\.php\?
.drei\.at/moma/adserver/adview\.php\?
.fcbayern\.t-com\.de[/&:?=_].*/fotogalerie_.*/sponsoren/
.gotv\.at/adimg/
.i\.computer-bild\.de/imgs/
.impde\.tradedoubler\.com/imp\?type\(img\)
.kmelektronik\.de/shop/images/advertising/
.marktplatzservice\.de/ads/
.media\.laendleauto\.at/topad/
.media\.laendleimmo\.at/topad/
.monetenlos\.com/components/com_marketplace/images/ads/
.mp\.apmebf\.com/ad/ck/
.mstat\.freent\.de[/&:?=_].*/sms_advertising/sms_teaser_
.n-tv\.de/ads/images/kompakt_
.nonstoppartner\.net[/&:?=_]
.pagead2\.googlesyndication\.com/simgad/
.photo\.knuddels\.de/kde/ad2/
.re-publica\.de/banner/
.reimkultur-mv\.de/9products/images/ad/
.rlp-tennis\.de/adserve/www/delivery/ai\.php\?filename=dunlopchoice160x600\.gif
.rurweb\.de/kleinanzeigen/adverts_image\.php\?
.sport\.de/autoimg/.*/300x250/
.stadtlist\.de/images/ads/
.stadtlist\.de/images/advert-
.storm-chasing\.de[/&:?=_].*/ad-gallery/
.teufel-media\.de/www/delivery/avw\.php\?zoneid=
.thangkas\.com/thangkas/thangkas/
.thomann\.de[/&:?=_].*/adv/adv_
.tradedoubler\.com/file/
.wn\.de/var/storage/images/.*_300_250\.
^http://.*\.com[/&:?=_]
^http://.*\.de[/&:?=_]
^http://.*\.net[/&:?=_]
.alle-news\.com[/&:?=_]
.buffed\.de[/&:?=_]
.cuiron\.de[/&:?=_]
.ethnarc\.de[/&:?=_]
.feed-reader\.net[/&:?=_]
.feropt\.de[/&:?=_]
.fribre\.de[/&:?=_]
.fribre\.de[/&:?=_]
.g\.doubleclick\.net/activity;.*/DE-AudiencePixel/Gamestar;dc_seg=
.gamesaktuell\.de[/&:?=_]
.lustich\.de[/&:?=_]
.news-reader\.info[/&:?=_]
.pcaction\.de[/&:?=_]
.pcgameshardware\.de[/&:?=_]
.starwars\.gamona\.de[/&:?=_]
.videogameszone\.de[/&:?=_]
_120x60\.
.bueropartner24\.de/out/pictures/generated/category/icon/728_90_
.dira-netzwerk\.de/cache/multithumb_thumbs/.*_300_250_
.gronkh\.de/media/thumbs/.*/300x250/
.internetworld\.de/img/.*_300x250_
.wetter\.com/layout/1/woys/300_250/300_250_
